import {readCommercePrices} from '../src/commerce-prices.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {walletValue,debitWallet,convertMoney} from '../src/commerce-currency.js';
import {createCommerceSession,normalizeCommerce,prepareCommerceAction,applyCommerceDecision,applyCommerceRoleplay,commerceAvailable,commerceFundsValid} from '../src/commerce-engine.js';
import {normalizeMarketplaceEvent,confirmedMarketplaceEvent} from '../src/marketplace-events.js';
const source={messageId:1,turnKey:'1',variant:'v'};
const state=()=>({player:{name:'Player'},location:{place:'Hall'},progression:{currency:{name:'Coins',gold:2,silver:0,copper:0}},inventory:[{id:'p',name:'Potion',quantity:3},{id:'b',name:'Blade',quantity:1}],commerce:normalizeCommerce()});
const shop=()=>createCommerceSession(normalizeMarketplaceEvent({kind:'npcShop',id:'shop',location:'Hall',seller:{name:'Mira'},denomination:'silver',items:[{itemId:'p',name:'Potion',price:3,stock:5},{itemId:'r',name:'Rope',price:10,stock:2}]}),source);
const sale=()=>createCommerceSession(normalizeMarketplaceEvent({kind:'npcPurchase',id:'sale',location:'Hall',buyer:{name:'Mira',budget:20},denomination:'silver',items:[{itemId:'p',itemName:'Potion',quantity:2,askPrice:6},{itemId:'b',itemName:'Blade',quantity:1,askPrice:10}]}),source);
const auction=()=>createCommerceSession({id:'a',location:'Hall',denomination:'silver',entryFee:1,deposit:2,lots:[{id:'l',name:'Blade',openingBid:5,minIncrement:1,bidders:[{id:'m',name:'Mira',budget:18}],currentBid:10,currentBidder:'m'}]},source);
const apply=(s,session,action,decision,input={})=>applyCommerceDecision(s,prepareCommerceAction(s,session,action,input),{narrative:'Mira considers the complete proposal.',decision});

test('denomination hierarchy compares exact copper value and never rounds a bid',()=>{assert.equal(convertMoney(1,'gold','silver'),100);assert.equal(convertMoney(1,'silver','copper'),100);assert.equal(convertMoney(99,'copper','silver'),null);});
test('paying silver from gold makes exact change and preserves total wealth less price',()=>{const wallet={gold:1,silver:0,copper:0},before=walletValue(wallet);assert.equal(debitWallet(wallet,7,'silver'),true);assert.deepEqual(wallet,{gold:0,silver:93,copper:0});assert.equal(walletValue(wallet),before-700);});
test('insufficient conversion leaves the wallet unchanged',()=>{const wallet={gold:0,silver:0,copper:99},before=structuredClone(wallet);assert.equal(debitWallet(wallet,1,'silver'),false);assert.deepEqual(wallet,before);});
test('one gold role-play bid beats ten silver with entry fee, deposit hold and exact settlement',()=>{const s=state(),session=auction();const r=applyCommerceRoleplay(s,session,{sessionId:session.id,revision:0,action:'bid',amount:1,denomination:'gold',evidence:'1 เหรียญทอง',decision:{outcome:'open',participants:[{id:'m',action:'withdraw',reason:'Beyond my actual funds'}]}},{user:'"1 เหรียญทอง" ฉันยกป้าย',userMessageId:2,narrative:'One gold from the back row.',source:{...source,messageId:3}});assert.equal(r.ok,true);assert.equal(r.session.lots[0].price,100);assert.equal(walletValue(r.next.progression.currency),19900);assert.equal(commerceAvailable(r.next).silver,97);assert.equal(commerceFundsValid(r.next),true);const closed=apply(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(closed.ok,true);assert.equal(walletValue(closed.next.progression.currency),9900);assert.equal(commerceAvailable(closed.next).silver,99);assert.equal(closed.next.inventory.find(i=>i.name==='Blade').quantity,2);assert.equal(closed.next.commerce.receipts.filter(r=>r.lotId==='@join').length,1);});
test('role-play amount already normalized to silver still validates original gold evidence',()=>{const s=state(),session=auction();const r=applyCommerceRoleplay(s,session,{sessionId:session.id,revision:0,action:'bid',amount:100,denomination:'silver',evidence:'หนึ่งเหรียญทอง',decision:{outcome:'open',participants:[{id:'m',action:'pass',reason:'Over budget'}]}},{user:'หนึ่งเหรียญทอง',userMessageId:2,narrative:'One gold!',source:{...source,messageId:3}});assert.equal(r.ok,true);assert.equal(r.session.lots[0].price,100);});
test('button bid in gold uses the same conversion and insufficient total including fees fails before API',()=>{const s=state(),session=auction();assert.equal(prepareCommerceAction(s,session,'bid',{amount:1,denomination:'gold'}).session.lots[0].price,100);s.progression.currency.gold=1;assert.equal(prepareCommerceAction(s,session,'bid',{amount:1,denomination:'gold'}).error,'funds');});
test('shop basket buys quantities of several items with one total and once-only receipt',()=>{const s=state(),session=shop(),items=[{itemId:session.items[0].id,quantity:2},{itemId:session.items[1].id,quantity:1}],r=apply(s,session,'confirm',{outcome:'accept',amount:16},{items});assert.equal(r.ok,true);assert.equal(walletValue(r.next.progression.currency),walletValue(s.progression.currency)-1600);assert.equal(r.next.inventory.find(i=>i.name==='Potion').quantity,5);assert.equal(r.next.inventory.find(i=>i.name==='Rope').quantity,1);assert.equal(r.next.commerce.receipts.length,1);assert.equal(r.next.commerce.receipts[0].items.length,2);assert.equal(apply(r.next,r.session,'confirm',{outcome:'accept',amount:16},{items}).ok,false);});
test('oversized, duplicate and unknown basket lines cannot partially transfer goods or money',()=>{const s=state(),session=shop();for(const items of [[{itemId:session.items[0].id,quantity:6}],[{itemId:'absent',quantity:1}],[{itemId:session.items[0].id,quantity:1},{itemId:session.items[0].id,quantity:1}]]){const before=structuredClone(s),prepared=prepareCommerceAction(s,session,'confirm',{items});assert.equal(prepared.ok,false);assert.deepEqual(s,before);}});
test('NPC can quote several owned items but unowned, duplicated or unsupported quantities cannot open',()=>{const s=state(),raw={kind:'npcPurchase',location:'Hall',denomination:'silver',buyer:{name:'Mira',budget:20},evidence:'Mira offers to buy Potion and Blade.',items:[{itemId:'p',itemName:'Potion',quantity:2,askPrice:6},{itemId:'b',itemName:'Blade',quantity:1,askPrice:10}]};assert.equal(confirmedMarketplaceEvent(raw,raw.evidence,'I listen.','Hall',s.inventory).items.length,2);for(const items of [[...raw.items,{itemName:'Unowned',quantity:1,askPrice:2}],[raw.items[0],raw.items[0]],[{...raw.items[0],quantity:4}]])assert.equal(confirmedMarketplaceEvent({...raw,items},raw.evidence,'I listen.','Hall',s.inventory),null);});
test('user excludes the blade, negotiates remaining potions and confirms one total sale',()=>{let s=state(),session=sale();assert.equal(session.quote,16);const items=[{itemId:session.items[0].id,quantity:2}];let r=applyCommerceRoleplay(s,session,{sessionId:session.id,revision:0,action:'talk',items,evidence:'ไม่ขาย Blade',decision:{outcome:'unchanged'}},{user:'ไม่ขาย Blade',userMessageId:2,narrative:'Mira removes the blade from her offer.',source:{...source,messageId:3}});assert.equal(r.ok,true);assert.equal(r.session.quote,6);assert.deepEqual(r.next.inventory,s.inventory);r=apply(r.next,r.session,'offer',{outcome:'accept',amount:7},{amount:7,items});assert.equal(r.ok,true);assert.deepEqual(r.next.inventory,s.inventory);r=apply(r.next,r.session,'confirm',{outcome:'accept',amount:7},{items});assert.equal(r.ok,true);assert.equal(r.next.inventory.find(i=>i.id==='p').quantity,1);assert.equal(r.next.inventory.find(i=>i.id==='b').quantity,1);assert.equal(walletValue(r.next.progression.currency),walletValue(s.progression.currency)+700);});
test('silent exclusion, price mismatch and insufficient buyer total never settle a basket',()=>{const s=state(),session=sale(),items=[{itemId:session.items[0].id,quantity:2}];assert.equal(applyCommerceRoleplay(s,session,{sessionId:session.id,revision:0,action:'confirm',items,amount:6,evidence:'ตกลง',decision:{outcome:'accept',amount:6}},{user:'ตกลง',userMessageId:2,narrative:'Accepted.'}).error,'evidence');assert.equal(apply(s,session,'confirm',{outcome:'accept',amount:15}).error,'consent');session.npcBudget=15;assert.equal(apply(s,session,'confirm',{outcome:'accept',amount:16}).error,'budget');});

test('explicit money reader keeps thousands intact and never misreads decimal fragments as whole coins',()=>{assert.equal(readCommercePrices('1,000 เหรียญทอง')[0].amount,1000);assert.deepEqual(readCommercePrices('0.5 เหรียญทอง'),[]);assert.deepEqual(readCommercePrices('1,00 เหรียญทอง'),[]);});
test('failure after one basket item was staged rolls back the complete wallet, items and receipt',()=>{const s=state();s.inventory=Array.from({length:199},(_,i)=>({id:`old-${i}`,name:`Old item ${i}`,quantity:1}));const before=structuredClone(s),session=shop(),items=session.items.map(entry=>({itemId:entry.id,quantity:1})),r=apply(s,session,'confirm',{outcome:'accept',amount:13},{items});assert.equal(r.ok,false);assert.deepEqual(r.next,before);assert.deepEqual(s,before);});
test('AI cannot silently increase a newly named basket item quantity',()=>{const s=state(),session=shop(),r=applyCommerceRoleplay(s,session,{sessionId:session.id,revision:0,action:'talk',items:[{itemId:session.items[0].id,quantity:1},{itemId:session.items[1].id,quantity:2}],evidence:'ขอซื้อ Rope',decision:{outcome:'unchanged'}},{user:'ขอซื้อ Rope',userMessageId:2,narrative:'Mira shows the rope.'});assert.equal(r.ok,false);assert.equal(r.error,'evidence');assert.deepEqual(r.next,s);});

test('an empty local basket can still cancel without a transfer',()=>{const s=state(),r=apply(s,shop(),'cancel',{outcome:'cancel'},{items:[]});assert.equal(r.ok,true);assert.deepEqual(r.next.inventory,s.inventory);assert.deepEqual(r.next.progression,s.progression);});
