import test from 'node:test';
import assert from 'node:assert/strict';
import {createCommerceSession,normalizeCommerce,prepareCommerceAction,applyCommerceDecision,commerceAvailable,commerceDecisionPrompt} from '../src/commerce-engine.js';
import {normalizeMarketplaceEvent} from '../src/marketplace-events.js';
const auction=(extra={})=>createCommerceSession({id:'auction',location:'Hall',denomination:'silver',entryFee:1,deposit:2,lots:[{id:'blade',name:'Blade',openingBid:3,minIncrement:1,bidders:[{id:'rally',name:'Rally',budget:20},{id:'mira',name:'Mira',budget:8}]}],...extra},{messageId:3,variant:'v',turnKey:'3'});
const state=()=>({player:{name:'Player'},location:{place:'Hall'},progression:{currency:{name:'Coins',gold:0,silver:30,copper:0}},inventory:[],commerce:normalizeCommerce()});
const decide=(s,session,action,decision,input={})=>applyCommerceDecision(s,prepareCommerceAction(s,session,action,input),{narrative:'Rally considers the price carefully.',decision});
const join=(session=auction())=>{const s=state(),r=decide(s,session,'join',{outcome:'joined'});assert.equal(r.ok,true);return r;};
const pass=()=>[{id:'rally',action:'pass',reason:'Saving for another lot'},{id:'mira',action:'withdraw',reason:'This weapon does not suit me'}];
const shop=(kind='npcShop')=>createCommerceSession(normalizeMarketplaceEvent({kind,id:'shop',location:'Hall',denomination:'silver',seller:{name:'Rally'},buyer:{name:'Mira',budget:12},item:{id:'blade',name:'Blade',quantity:1},askPrice:6,items:[{id:'potion',name:'Potion',price:6,stock:2},{id:'rope',name:'Rope',price:10,stock:1}]}),{messageId:3,variant:'v',turnKey:'3'});

test('rival AI can withdraw early and player wins well below both wallets; settlement once only',()=>{
 let r=join();r=decide(r.next,r.session,'bid',{outcome:'sold',participants:pass()},{amount:4});assert.equal(r.ok,true);assert.equal(r.session.status,'completed');assert.equal(r.next.progression.currency.silver,25);assert.equal(r.next.inventory[0].name,'Blade');assert.equal(commerceAvailable(r.next).silver,25);
 const replay=decide(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(replay.ok,false);assert.equal(replay.next.progression.currency.silver,25);
});
test('AI can jump directly all-in and win instead of forcing user victory',()=>{
 let r=join();r=decide(r.next,r.session,'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:20,reason:'This heirloom is my entire reason for coming'},{id:'mira',action:'withdraw',reason:'Over budget'}]},{amount:4});assert.equal(r.ok,true);assert.equal(r.session.lots[0].price,20);assert.equal(commerceAvailable(r.next).silver,27);
 r=decide(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(r.ok,true);assert.equal(r.session.participants[0].spent,20);assert.equal(r.next.inventory.length,0);assert.equal(r.next.progression.currency.silver,29);
});
for(const [name,decision] of [
 ['overspending',{outcome:'open',participants:[{id:'rally',action:'bid',amount:21,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]}],
 ['invented rival',{outcome:'open',participants:[{id:'new',action:'bid',amount:5,reason:'Want it'}]}],
 ['missing decision',{outcome:'sold',participants:[{id:'rally',action:'pass',reason:'Waiting'}]}],
 ['fresh counter sold immediately',{outcome:'sold',participants:[{id:'rally',action:'bid',amount:9,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]}],
 ['invalid increment',{outcome:'open',participants:[{id:'rally',action:'bid',amount:4,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]}],
 ['missing motive',{outcome:'sold',participants:[{id:'rally',action:'pass'},{id:'mira',action:'pass',reason:'Waiting'}]}],
])test(`invalid auction ${name} leaves wallet and goods untouched`,()=>{const r=join(),snapshot=structuredClone(r.next),result=decide(r.next,r.session,'bid',decision,{amount:4});assert.equal(result.ok,false);assert.deepEqual(r.next,snapshot);assert.deepEqual(result.next,snapshot);});
test('no fixed countdown: successive considered passes leave open until AI closes it',()=>{let r=join();r=decide(r.next,r.session,'bid',{outcome:'open',participants:pass()},{amount:4});for(let i=0;i<5;i++){r=decide(r.next,r.session,'wait',{outcome:'open',participants:[{id:'rally',action:'pass',reason:'Thinking about authenticity'}]});assert.equal(r.ok,true);assert.equal(r.session.status,'open');}assert.equal(r.next.inventory.length,0);});
test('declining offered auction is an AI action with no fee',()=>{const s=state(),r=decide(s,auction(),'leave',{outcome:'left'});assert.equal(r.ok,true);assert.equal(r.session.status,'cancelled');assert.equal(r.next.progression.currency.silver,30);});
test('leading player cannot discard payment obligation',()=>{let r=join();r=decide(r.next,r.session,'bid',{outcome:'open',participants:pass()},{amount:4});const result=decide(r.next,r.session,'leave',{outcome:'left',participants:[{id:'rally',action:'pass',reason:'No interest'}]});assert.equal(result.error,'committed');assert.equal(commerceAvailable(r.next).silver,23);});
test('spent NPC funds are shared across lots',()=>{const base=auction();base.lots.push({...structuredClone(base.lots[0]),id:'potion',name:'Potion'});let r=join(base);r=decide(r.next,r.session,'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:18,reason:'A rare blade'},{id:'mira',action:'withdraw',reason:'Too costly'}]},{amount:4});r=decide(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(r.ok,true);r=decide(r.next,r.session,'next',{outcome:'next'});assert.equal(r.ok,true);const bad=decide(r.next,r.session,'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:5,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]},{amount:4});assert.equal(bad.error,'budget');assert.equal(r.session.participants[0].budget-r.session.participants[0].spent,2);});
test('auction cannot invent different budgets for same NPC across lots',()=>{const base=auction();const event={...base,id:'bad',lots:base.lots.map(l=>({...l,bidders:[{id:'rally',name:'Rally',budget:20}]}))};event.lots.push({...event.lots[0],id:'second',bidders:[{id:'rally',name:'Rally',budget:40}]});assert.equal(createCommerceSession(event),null);});
test('proposed purchase agreement awaits explicit confirm then settles atomically',()=>{let s=state(),session=shop();let r=decide(s,session,'offer',{outcome:'accept',amount:4},{amount:4});assert.equal(r.ok,true);assert.equal(r.next.progression.currency.silver,30);assert.equal(r.next.inventory.length,0);assert.equal(r.session.agreed,true);r=decide(r.next,r.session,'confirm',{outcome:'accept',amount:4});assert.equal(r.ok,true);assert.equal(r.session.status,'completed');assert.equal(r.next.progression.currency.silver,26);assert.equal(r.next.inventory[0].quantity,1);assert.equal(r.next.commerce.receipts.length,1);});
test('confirm never consents to higher price, counter awaits consent',()=>{const s=state(),session=shop();assert.equal(decide(s,session,'confirm',{outcome:'accept',amount:8}).error,'consent');const r=decide(s,session,'confirm',{outcome:'counter',amount:8});assert.equal(r.ok,true);assert.equal(r.session.status,'open');assert.equal(r.session.quote,8);assert.equal(r.next.progression.currency.silver,30);});
test('selected catalog item resets consent and settles only that item',()=>{let r=decide(state(),shop(),'offer',{outcome:'accept',amount:4},{amount:4});r=decide(r.next,r.session,'confirm',{outcome:'accept',amount:10},{itemId:'rope'});assert.equal(r.ok,true);assert.equal(r.next.inventory[0].name,'Rope');assert.equal(r.next.progression.currency.silver,20);});
test('NPC buys actual owned quantity for negotiated price within known funds',()=>{const s=state();s.inventory=[{id:'blade',name:'Blade',quantity:2}];let r=decide(s,shop('npcPurchase'),'offer',{outcome:'counter',amount:8},{amount:10});assert.equal(r.ok,true);assert.equal(r.next.inventory[0].quantity,2);r=decide(r.next,r.session,'confirm',{outcome:'accept',amount:8});assert.equal(r.ok,true);assert.equal(r.next.progression.currency.silver,38);assert.equal(r.next.inventory[0].quantity,1);});
test('known NPC purchase budget cannot increase; cancel has no transfer',()=>{const s=state();s.inventory=[{id:'blade',name:'Blade',quantity:1}];assert.equal(shop('npcPurchase').npcBudget,12);assert.equal(decide(s,shop('npcPurchase'),'offer',{outcome:'counter',amount:13},{amount:11}).error,'budget');const r=decide(s,shop('npcPurchase'),'cancel',{outcome:'cancel'});assert.equal(r.ok,true);assert.deepEqual(r.next.inventory,s.inventory);assert.equal(r.next.progression.currency.silver,30);});
test('cancel may not settle accepted price',()=>assert.equal(decide(state(),shop(),'cancel',{outcome:'accept',amount:6}).error,'outcome'));
test('insufficient funds prevent paid API preparation and no free item results',()=>{const s=state();s.progression.currency.silver=1;assert.equal(prepareCommerceAction(s,shop(),'confirm').error,'funds');assert.equal(prepareCommerceAction(s,auction(),'join').error,'funds');});
test('legacy reservations and paid receipts migrate without charging again',()=>{const s=state();s.auctions=[{id:'old',location:'Hall',denomination:'silver',status:'Joined',revision:5,index:1,entryFee:1,deposit:2,lots:[{id:'one',name:'One',openingBid:3,minIncrement:1,status:'Sold',price:7,highestBidder:'rally',bidders:[{id:'rally',name:'Rally',maxBid:10}]},{id:'two',name:'Two',openingBid:3,minIncrement:1,status:'Open',price:4,highestBidder:'player',bidders:[{id:'rally',name:'Rally',maxBid:10}]}]}];s.auctionReceipts=[{auctionId:'old',lotId:'one',winner:'rally',amount:7,itemName:'One',quantity:1,denomination:'silver'}];s.commerce=normalizeCommerce({},s);assert.equal(s.commerce.sessions[0].participants[0].spent,7);assert.equal(commerceAvailable(s).silver,24);assert.equal(normalizeCommerce(s.commerce,s).sessions.length,1);assert.equal(normalizeCommerce(s.commerce,s).receipts.length,1);assert.equal(s.progression.currency.silver,30);});
test('decision prompt preserves motives and omits explicit player wallet, fixed ceilings and deterministic actions',()=>{const s=state(),prepared=prepareCommerceAction(s,auction(),'join');const prompt=commerceDecisionPrompt(prepared,{npcs:[{id:'rally',name:'Rally',personality:'Proud but cautious',goals:'Save for rent'}]});assert.match(prompt,/Proud but cautious/);assert.match(prompt,/Save for rent/);assert.doesNotMatch(prompt,/"currency"|"maxBid"|closingCount/);assert.match(prompt,/ALL remaining budget/);assert.match(prompt,/no fixed three-click/);});
