import test from 'node:test';
import assert from 'node:assert/strict';
import {createCommerceSession,normalizeCommerce,prepareCommerceAction,applyCommerceDecision,commerceAvailable,commerceDecisionPrompt,applyCommerceRoleplay,commerceRoleplayPrompt} from '../src/commerce-engine.js';
import {normalizeMarketplaceEvent} from '../src/marketplace-events.js';
const auction=(extra={})=>createCommerceSession({id:'auction',location:'Hall',denomination:'silver',entryFee:1,deposit:2,lots:[{id:'blade',name:'Blade',openingBid:3,minIncrement:1,bidders:[{id:'rally',name:'Rally',budget:20},{id:'mira',name:'Mira',budget:8}]}],...extra},{messageId:3,variant:'v',turnKey:'3'});
const state=()=>({player:{name:'Player'},location:{place:'Hall'},progression:{currency:{name:'Coins',gold:0,silver:30,copper:0}},inventory:[],commerce:normalizeCommerce()});
const decide=(s,session,action,decision,input={})=>applyCommerceDecision(s,prepareCommerceAction(s,session,action,input),{narrative:'Rally considers the price carefully.',decision});
const join=(session=auction())=>{const s=state(),r=decide(s,session,'join',{outcome:'joined'});assert.equal(r.ok,true);return r;};
const pass=()=>[{id:'rally',action:'pass',reason:'Saving for another lot'},{id:'mira',action:'withdraw',reason:'This weapon does not suit me'}];
const shop=(kind='npcShop')=>createCommerceSession(normalizeMarketplaceEvent({kind,id:'shop',location:'Hall',denomination:'silver',seller:{name:'Rally'},buyer:{name:'Mira',budget:12},item:{id:'blade',name:'Blade',quantity:1},askPrice:6,items:[{id:'potion',name:'Potion',price:6,stock:2},{id:'rope',name:'Rope',price:10,stock:1}]}),{messageId:3,variant:'v',turnKey:'3'});

test('rival AI can withdraw early and player wins well below both wallets; settlement once only',()=>{
 let r=join();r=decide(r.next,r.session,'bid',{outcome:'sold',participants:pass()},{amount:4});assert.equal(r.ok,true);assert.equal(r.session.status,'completed');assert.equal(r.next.progression.currency.silver,25);assert.equal(r.next.inventory[0].name,'Blade');assert.equal(commerceAvailable(r.next).silver,25);
 const replay=decide(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(replay.ok,false);assert.equal(replay.next.progression.currency.silver,25);
});
test('AI can jump directly all-in and win instead of forcing user victory',()=>{
 let r=join();r=decide(r.next,r.session,'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:20,reason:'This heirloom is my entire reason for coming'},{id:'mira',action:'withdraw',reason:'Over budget'}]},{amount:4});assert.equal(r.ok,true);assert.equal(r.session.lots[0].price,20);assert.equal(commerceAvailable(r.next).silver,27);
 r=decide(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(r.ok,true);assert.equal(r.session.participants[0].spent,20);assert.equal(r.next.inventory.length,0);assert.equal(r.next.progression.currency.silver,29);
});
for(const [name,decision] of [
 ['overspending',{outcome:'open',participants:[{id:'rally',action:'bid',amount:21,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]}],
 ['invented rival',{outcome:'open',participants:[{id:'new',action:'bid',amount:5,reason:'Want it'}]}],
 ['missing decision',{outcome:'sold',participants:[{id:'rally',action:'pass',reason:'Waiting'}]}],
 ['fresh counter sold immediately',{outcome:'sold',participants:[{id:'rally',action:'bid',amount:9,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]}],
 ['invalid increment',{outcome:'open',participants:[{id:'rally',action:'bid',amount:4,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]}],
 ['missing motive',{outcome:'sold',participants:[{id:'rally',action:'pass'},{id:'mira',action:'pass',reason:'Waiting'}]}],
])test(`invalid auction ${name} leaves wallet and goods untouched`,()=>{const r=join(),snapshot=structuredClone(r.next),result=decide(r.next,r.session,'bid',decision,{amount:4});assert.equal(result.ok,false);assert.deepEqual(r.next,snapshot);assert.deepEqual(result.next,snapshot);});
test('no fixed countdown: successive considered passes leave open until AI closes it',()=>{let r=join();r=decide(r.next,r.session,'bid',{outcome:'open',participants:pass()},{amount:4});for(let i=0;i<5;i++){r=decide(r.next,r.session,'wait',{outcome:'open',participants:[{id:'rally',action:'pass',reason:'Thinking about authenticity'}]});assert.equal(r.ok,true);assert.equal(r.session.status,'open');}assert.equal(r.next.inventory.length,0);});
test('declining offered auction is an AI action with no fee',()=>{const s=state(),r=decide(s,auction(),'leave',{outcome:'left'});assert.equal(r.ok,true);assert.equal(r.session.status,'cancelled');assert.equal(r.next.progression.currency.silver,30);});
test('leading player cannot discard payment obligation',()=>{let r=join();r=decide(r.next,r.session,'bid',{outcome:'open',participants:pass()},{amount:4});const result=decide(r.next,r.session,'leave',{outcome:'left',participants:[{id:'rally',action:'pass',reason:'No interest'}]});assert.equal(result.error,'committed');assert.equal(commerceAvailable(r.next).silver,23);});
test('spent NPC funds are shared across lots',()=>{const base=auction();base.lots.push({...structuredClone(base.lots[0]),id:'potion',name:'Potion'});let r=join(base);r=decide(r.next,r.session,'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:18,reason:'A rare blade'},{id:'mira',action:'withdraw',reason:'Too costly'}]},{amount:4});r=decide(r.next,r.session,'wait',{outcome:'sold',participants:[]});assert.equal(r.ok,true);r=decide(r.next,r.session,'next',{outcome:'next'});assert.equal(r.ok,true);const bad=decide(r.next,r.session,'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:5,reason:'Want it'},{id:'mira',action:'pass',reason:'Waiting'}]},{amount:4});assert.equal(bad.error,'budget');assert.equal(r.session.participants[0].budget-r.session.participants[0].spent,2);});
test('auction cannot invent different budgets for same NPC across lots',()=>{const base=auction();const event={...base,id:'bad',lots:base.lots.map(l=>({...l,bidders:[{id:'rally',name:'Rally',budget:20}]}))};event.lots.push({...event.lots[0],id:'second',bidders:[{id:'rally',name:'Rally',budget:40}]});assert.equal(createCommerceSession(event),null);});
test('proposed purchase agreement awaits explicit confirm then settles atomically',()=>{let s=state(),session=shop();let r=decide(s,session,'offer',{outcome:'accept',amount:4},{amount:4});assert.equal(r.ok,true);assert.equal(r.next.progression.currency.silver,30);assert.equal(r.next.inventory.length,0);assert.equal(r.session.agreed,true);r=decide(r.next,r.session,'confirm',{outcome:'accept',amount:4});assert.equal(r.ok,true);assert.equal(r.session.status,'completed');assert.equal(r.next.progression.currency.silver,26);assert.equal(r.next.inventory[0].quantity,1);assert.equal(r.next.commerce.receipts.length,1);});
test('confirm never consents to higher price, counter awaits consent',()=>{const s=state(),session=shop();assert.equal(decide(s,session,'confirm',{outcome:'accept',amount:8}).error,'consent');const r=decide(s,session,'confirm',{outcome:'counter',amount:8});assert.equal(r.ok,true);assert.equal(r.session.status,'open');assert.equal(r.session.quote,8);assert.equal(r.next.progression.currency.silver,30);});
test('selected catalog item resets consent and settles only that item',()=>{let r=decide(state(),shop(),'offer',{outcome:'accept',amount:4},{amount:4});r=decide(r.next,r.session,'confirm',{outcome:'accept',amount:10},{itemId:'rope'});assert.equal(r.ok,true);assert.equal(r.next.inventory[0].name,'Rope');assert.equal(r.next.progression.currency.silver,20);});
test('NPC buys actual owned quantity for negotiated price within known funds',()=>{const s=state();s.inventory=[{id:'blade',name:'Blade',quantity:2}];let r=decide(s,shop('npcPurchase'),'offer',{outcome:'counter',amount:8},{amount:10});assert.equal(r.ok,true);assert.equal(r.next.inventory[0].quantity,2);r=decide(r.next,r.session,'confirm',{outcome:'accept',amount:8});assert.equal(r.ok,true);assert.equal(r.next.progression.currency.silver,38);assert.equal(r.next.inventory[0].quantity,1);});
test('known NPC purchase budget cannot increase; cancel has no transfer',()=>{const s=state();s.inventory=[{id:'blade',name:'Blade',quantity:1}];assert.equal(shop('npcPurchase').npcBudget,12);assert.equal(decide(s,shop('npcPurchase'),'offer',{outcome:'counter',amount:13},{amount:11}).error,'budget');const r=decide(s,shop('npcPurchase'),'cancel',{outcome:'cancel'});assert.equal(r.ok,true);assert.deepEqual(r.next.inventory,s.inventory);assert.equal(r.next.progression.currency.silver,30);});
test('cancel may not settle accepted price',()=>assert.equal(decide(state(),shop(),'cancel',{outcome:'accept',amount:6}).error,'outcome'));
test('insufficient funds prevent paid API preparation and no free item results',()=>{const s=state();s.progression.currency.silver=1;assert.equal(prepareCommerceAction(s,shop(),'confirm').error,'funds');assert.equal(prepareCommerceAction(s,auction(),'join').error,'funds');});
test('legacy reservations and paid receipts migrate without charging again',()=>{const s=state();s.auctions=[{id:'old',location:'Hall',denomination:'silver',status:'Joined',revision:5,index:1,entryFee:1,deposit:2,lots:[{id:'one',name:'One',openingBid:3,minIncrement:1,status:'Sold',price:7,highestBidder:'rally',bidders:[{id:'rally',name:'Rally',maxBid:10}]},{id:'two',name:'Two',openingBid:3,minIncrement:1,status:'Open',price:4,highestBidder:'player',bidders:[{id:'rally',name:'Rally',maxBid:10}]}]}];s.auctionReceipts=[{auctionId:'old',lotId:'one',winner:'rally',amount:7,itemName:'One',quantity:1,denomination:'silver'}];s.commerce=normalizeCommerce({},s);assert.equal(s.commerce.sessions[0].participants[0].spent,7);assert.equal(commerceAvailable(s).silver,24);assert.equal(normalizeCommerce(s.commerce,s).sessions.length,1);assert.equal(normalizeCommerce(s.commerce,s).receipts.length,1);assert.equal(s.progression.currency.silver,30);});
test('decision prompt preserves motives and omits explicit player wallet, fixed ceilings and deterministic actions',()=>{const s=state(),prepared=prepareCommerceAction(s,auction(),'join');const prompt=commerceDecisionPrompt(prepared,{npcs:[{id:'rally',name:'Rally',personality:'Proud but cautious',goals:'Save for rent'}]});assert.match(prompt,/Proud but cautious/);assert.match(prompt,/Save for rent/);assert.doesNotMatch(prompt,/"currency"|"maxBid"|closingCount/);assert.match(prompt,/ALL remaining budget/);assert.match(prompt,/no fixed three-click/);});

const role=(s,session,action,decision,{user,amount,itemId,revision=session.revision,evidence=user,...extra}={})=>applyCommerceRoleplay(s,session,{sessionId:session.id,revision,action,decision,amount,itemId,evidence,...extra},{user,narrative:'Rally thoughtfully responds to your role-play.',source:{messageId:5,variant:'new',turnKey:'5'}});
test('role-play proposes a price without paying, buttons and chat confirm the same quote',()=>{const s=state(),session=shop();const offer=role(s,session,'offer',{outcome:'accept',amount:2},{user:'ผมวางเหรียญ เสนอ 2 เหรียญเงิน',amount:2});assert.equal(offer.ok,true);assert.equal(offer.next.progression.currency.silver,30);assert.equal(offer.session.quote,2);assert.equal(offer.session.source.messageId,5);const paid=decide(offer.next,offer.session,'confirm',{outcome:'accept',amount:2});assert.equal(paid.ok,true);assert.equal(paid.next.progression.currency.silver,28);assert.equal(paid.next.commerce.receipts.length,1);});
test('button counteroffer can be confirmed by free role-play and cannot be replayed',()=>{const offered=decide(state(),shop(),'offer',{outcome:'counter',amount:3},{amount:2});const paid=role(offered.next,offered.session,'confirm',{outcome:'accept',amount:3},{user:'ตกลง ซื้อราคา 3 เหรียญเงิน',amount:3});assert.equal(paid.ok,true);assert.equal(paid.session.status,'completed');assert.equal(paid.next.progression.currency.silver,27);assert.equal(role(paid.next,paid.session,'confirm',{outcome:'accept',amount:3},{user:'ตกลง',amount:3}).ok,false);});
for(const user of ['ถ้าลดเหลือ 6 เหรียญเงินก็น่าสนใจ','ยังไม่ตกลงซื้อ 6 เหรียญเงิน','I would buy for 6 silver if you fix it','สมมุติตกลงซื้อ 6 เหรียญเงิน'])test(`conditional/refusal never settles: ${user}`,()=>{assert.equal(role(state(),shop(),'confirm',{outcome:'accept',amount:6},{user,amount:6}).ok,false);});
test('ambiguous price, missing evidence, fabricated offer and wrong denomination cannot transfer resources',()=>{const s=state(),session=shop();for(const args of [{user:'ขอเสนอ 2 เหรียญเงิน',amount:3},{user:'ขอเสนอ 2 เหรียญทอง',amount:2},{user:'I have 14 silver saved for rent',amount:14},{user:'ขอดูสินค้า',evidence:'ตกลงซื้อ',amount:6}]){assert.equal(role(s,session,'offer',{outcome:'accept',amount:args.amount},args).ok,false);}assert.equal(s.progression.currency.silver,30);assert.equal(s.inventory.length,0);});
test('Thai written numbers and Thai digits authorize the stated offer',()=>{for(const [user,amount]of [['ขอเสนอ สองเหรียญเงิน',2],['เสนอ ยี่สิบสี่เหรียญเงิน',24],['ขอเสนอ ๒ เหรียญเงิน',2]])assert.equal(role(state(),shop(),'offer',{outcome:'accept',amount},{user,amount}).ok,true);});
test('questions and persuasion preserve auction price, budgets and progress',()=>{const r=join(),next=role(r.next,r.session,'talk',{outcome:'unchanged'},{user:'ทำไมคุณถึงอยากได้ดาบเล่มนี้'});assert.equal(next.ok,true);assert.deepEqual(next.session.lots,r.session.lots);assert.deepEqual(next.session.participants,r.session.participants);assert.equal(next.next.progression.currency.silver,r.next.progression.currency.silver);});
test('inspection selects an existing shop item but cannot secretly change its price or terms',()=>{let next=role(state(),shop(),'talk',{outcome:'unchanged'},{user:'ขอดู Rope',itemId:'rope'});assert.equal(next.ok,true);assert.equal(next.session.selectedId,'rope');assert.equal(next.session.quote,10);assert.equal(role(state(),shop(),'talk',{outcome:'counter',amount:1},{user:'ขอดู Potion'}).ok,false);});
test('role-play bid implicitly joins with real fees, while a rival can jump all-in',()=>{const next=role(state(),auction(),'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:20,reason:'Family heirloom'},{id:'mira',action:'withdraw',reason:'Not worth it'}]},{user:'ผมยกป้ายบิด 4 เหรียญเงิน',amount:4});assert.equal(next.ok,true);assert.equal(next.session.status,'open');assert.equal(next.session.lots[0].leader,'rally');assert.equal(next.next.progression.currency.silver,29);assert.equal(commerceAvailable(next.next).silver,27);assert.equal(next.next.commerce.receipts.length,1);});
test('invalid rival response rolls back implicit entry fee as well as the bid',()=>{const s=state(),next=role(s,auction(),'bid',{outcome:'open',participants:[{id:'rally',action:'bid',amount:21,reason:'Want it'},{id:'mira',action:'pass',reason:'Wait'}]},{user:'บิด 4 เหรียญเงิน',amount:4});assert.equal(next.ok,false);assert.equal(next.next.progression.currency.silver,30);assert.equal(next.next.commerce.sessions.length,0);});
test('role-play sale cannot exceed real NPC budget',()=>{const s=state();s.inventory=[{id:'blade',name:'Blade',quantity:1}];const session=shop('npcPurchase');assert.equal(role(s,session,'offer',{outcome:'counter',amount:13},{user:'เสนอขาย 10 เหรียญเงิน',amount:10}).ok,false);const paid=role(s,session,'confirm',{outcome:'accept',amount:6},{user:'ตกลง ขายให้ราคา 6 เหรียญเงิน',amount:6});assert.equal(paid.ok,true);assert.equal(paid.next.inventory.length,0);assert.equal(paid.next.progression.currency.silver,36);});
test('role-play cancellation and stale decisions preserve resource safety',()=>{const session=shop();assert.equal(role(state(),session,'cancel',{outcome:'cancel'},{user:'ไม่ซื้อแล้ว ยกเลิก'}).session.status,'cancelled');assert.equal(role(state(),session,'offer',{outcome:'accept',amount:2},{user:'เสนอ 2 เหรียญเงิน',amount:2,revision:8}).error,'stale');});
test('normal chat contract uses invisible commerce decision and no second API call',()=>{const prompt=commerceRoleplayPrompt(shop());assert.match(prompt,/NORMAL CHAT COMMERCE/);assert.match(prompt,/LATEST user message/);assert.match(prompt,/do not append to an older bubble/);assert.match(prompt,/another API call/);assert.match(prompt,/commerce.decision/);});

test('explicit named-item purchase consents to that item price, while silent item switching is rejected',()=>{const session=shop();const paid=role(state(),session,'confirm',{outcome:'accept',amount:10},{user:'ตกลง ขอซื้อ Rope ราคา 10 เหรียญเงิน',amount:10,itemId:'rope'});assert.equal(paid.ok,true);assert.equal(paid.next.inventory[0].name,'Rope');assert.equal(paid.next.progression.currency.silver,20);assert.equal(role(state(),session,'confirm',{outcome:'accept',amount:10},{user:'ตกลง',itemId:'rope'}).ok,false);});

test('bare quoted price is a valid contextual offer but negative numbers are not rewritten as positive',()=>{assert.equal(role(state(),shop(),'offer',{outcome:'accept',amount:2},{user:'2 เหรียญเงิน!',amount:2}).ok,true);assert.equal(role(state(),shop(),'offer',{outcome:'accept',amount:2},{user:'เสนอ -2 เหรียญเงิน',amount:2}).ok,false);});

test('continuing an NPC reply cannot reuse an older user offer as another financial action',()=>{const session=shop();const next=applyCommerceRoleplay(state(),session,{sessionId:session.id,revision:session.revision,action:'confirm',evidence:'ตกลง',decision:{outcome:'accept',amount:6}},{user:'ตกลง',userMessageId:2,narrative:'Rally hands over another potion.',source:{messageId:4,variant:'continue',turnKey:'4'}});assert.equal(next.error,'stale');assert.equal(next.next.progression.currency.silver,30);});

test('direct Bid opens offered auction and charges entry once after explicit AI decisions',()=>{const s=state(),session=auction();s.commerce.sessions.push(session);const r=decide(s,session,'bid',{outcome:'open',npcActions:[{name:'Rally',choice:'raise',bid_amount:'18',motive:'Heirloom'},{name:'Mira',choice:'withdrawn',motive:'Saving for rent'}]},{amount:4});assert.equal(r.ok,true);assert.equal(r.next.progression.currency.silver,29);assert.equal(r.next.commerce.receipts.length,1);assert.equal(r.session.lots[0].leader,'rally');const done=decide(r.next,r.session,'wait',{outcome:'sold',participants:[{name:'Rally',action:'bid',amount:18},{name:'Mira',action:'withdraw'}]});assert.equal(done.ok,true);assert.equal(done.next.commerce.receipts.length,2);assert.equal(done.next.progression.currency.silver,29);});
test('direct Bid with incomplete AI choices rolls back implicit fees and stored offered session',()=>{const s=state(),session=auction();s.commerce.sessions.push(session);const before=structuredClone(s);const r=decide(s,session,'bid',{outcome:'sold',participants:[{id:'rally',action:'pass',reason:'Saving'}]},{amount:4});assert.equal(r.error,'participants-missing');assert.deepEqual(r.next,before);assert.deepEqual(s,before);});
test('direct Bid validates entry, deposit and price before requesting a decision',()=>{const s=state();s.progression.currency.silver=6;assert.equal(prepareCommerceAction(s,auction(),'bid',{amount:4}).error,'funds');assert.equal(s.progression.currency.silver,6);});
test('unordered valid rival bids do not fail just because highest was listed first',()=>{const r=decide(state(),auction(),'bid',{outcome:'open',participants:[{name:'Rally',action:'bid',amount:18,reason:'Heirloom'},{name:'Mira',action:'bid',amount:7,reason:'Useful'}]},{amount:4});assert.equal(r.ok,true);assert.equal(r.session.lots[0].price,18);});

test('auction AI cannot route an ordinary bid into trade confirmation or its price-consent error',()=>{const result=role(state(),auction(),'confirm',{outcome:'accept',amount:6},{user:'ผมยกป้ายบิด 6 เหรียญเงิน',amount:6});assert.equal(result.error,'action');assert.equal(result.next.progression.currency.silver,30);assert.match(commerceRoleplayPrompt(auction()),/This is AUCTION ONLY/);assert.doesNotMatch(commerceRoleplayPrompt(auction()),/A price proposal or request to lower the price is offer|CURRENT quote is confirm/);});
test('unrelated negation in role prose is not a refusal to bid',()=>{for(const user of ['ผมไม่อยากเสียเวลา ยกป้ายบิด 6 เหรียญเงิน','I do not want to waste time; I bid 6 silver']){const r=role(state(),auction(),'bid',{outcome:'open',participants:pass()},{user,amount:6});assert.equal(r.ok,true);assert.equal(r.session.lots[0].price,6);}});
for(const user of ['ผมไม่อยากบิด 6 เหรียญเงิน','ผมไม่ให้ 6 เหรียญเงิน','I do not want to bid 6 silver','ถ้าทุกคนถอนตัว ผมบิด 6 เหรียญเงิน'])test(`explicit refusal or conditional bid does not authorize entry: ${user}`,()=>{const r=role(state(),auction(),'bid',{outcome:'open',participants:pass()},{user,amount:6});assert.equal(r.error,'intent');assert.equal(r.next.progression.currency.silver,30);});
test('entry fee insufficiency on direct Bid is reported as funds before any API request',()=>{const s=state();s.progression.currency.silver=0;assert.equal(prepareCommerceAction(s,auction(),'bid',{amount:6}).error,'funds');});
