import test from 'node:test';
import assert from 'node:assert/strict';
import {createCommerceRuntime} from '../src/commerce-runtime.js';
import {normalizeMarketplaceEvent} from '../src/marketplace-events.js';
const deferred=()=>{let resolve;return{promise:new Promise(r=>{resolve=r}),resolve:v=>resolve(v)};};
function fixture(){
 let state={player:{name:'Player'},npcs:[],location:{place:'Hall'},progression:{currency:{gold:0,silver:30,copper:0}},inventory:[]},busy=false,calls=0,commits=0;
 const event=normalizeMarketplaceEvent({kind:'npcShop',id:'shop',location:'Hall',seller:{name:'Rally'},denomination:'silver',items:[{name:'Potion',price:6}]});
 const settings={enableMarketplace:true,enableAuctions:true,language:'en'};
 const metadata={},context={chatMetadata:metadata,chat:[{is_user:true,mes:'Show goods'},{is_user:false,mes:'Rally shows a Potion.'}],getCurrentChatId:()=> 'chat',saveMetadata:async()=>{},generateQuietPrompt:async()=>{calls++;return JSON.stringify({narrative:'Rally hands you the potion.',decision:{outcome:'accept',amount:6}});}};
 const runtime=createCommerceRuntime({document:{},context:()=>context,state:()=>structuredClone(state),settings:()=>settings,turnKey:id=>String(id),variant:m=>m.mes,record:id=>({marketplace:{event:context.chat[id]?.event||event,status:context.chat[id]?.eventStatus}}),isBusy:()=>busy,visible:v=>v,parse:JSON.parse,recordRequest(){},setBusy:v=>{busy=v;},commit:async({message,result,unchanged})=>{assert.equal(unchanged(),true);commits++;message.mes+='\n\n'+result.narrative;result.session.source.variant=message.mes;state=result.next;}});
 return{runtime,context,settings,setState:fn=>fn(state),calls:()=>calls,commits:()=>commits,state:()=>state,perform:action=>{const v=runtime.view();return runtime.perform({id:v.session.id,token:v.token,action});}};
}
test('one game action makes one native API call, appends same message, hides on completion',async()=>{const f=fixture(),before=f.context.chat[1].mes;const result=await f.perform('confirm');assert.equal(result.ok,true);assert.equal(f.calls(),1);assert.equal(f.commits(),1);assert.equal(f.context.chat.length,2);assert.equal(f.context.chat[0].mes,'Show goods');assert.ok(f.context.chat[1].mes.startsWith(before));assert.match(f.context.chat[1].mes,/hands you/);assert.equal(f.state().progression.currency.silver,24);assert.equal(f.runtime.view(),null);});
test('read-only view and refresh make no calls',()=>{const f=fixture();f.runtime.view();f.runtime.refresh();assert.equal(f.calls(),0);assert.equal(f.commits(),0);});
test('double click cannot duplicate request',async()=>{const f=fixture(),gate=deferred();f.context.generateQuietPrompt=()=>gate.promise;const first=f.perform('confirm');const second=await f.perform('confirm');assert.equal(second.ok,false);gate.resolve(JSON.stringify({narrative:'Done',decision:{outcome:'accept',amount:6}}));assert.equal((await first).ok,true);assert.equal(f.commits(),1);});
for(const [name,mutate] of [
 ['chat switch',f=>{f.context.chatMetadata={};}],['message edit',f=>{f.context.chat[1].mes='Edited';}],['swipe',f=>{f.context.chat[1]={is_user:false,mes:'Alternate'};}],['new turn',f=>{f.context.chat.push({is_user:true,mes:'Next'});}],['wallet changed',f=>f.setState(s=>{s.progression.currency.silver=12;})],['stop',f=>f.runtime.cancel()],['feature disabled',f=>{f.settings.enableMarketplace=false;}],
])test(`late decision discarded after ${name}`,async()=>{const f=fixture(),gate=deferred();f.context.generateQuietPrompt=()=>gate.promise;const pending=f.perform('confirm');mutate(f);gate.resolve(JSON.stringify({narrative:'Done',decision:{outcome:'accept',amount:6}}));assert.equal((await pending).ok,false);assert.equal(f.commits(),0);assert.equal(f.state().inventory.length,0);});
test('failed API never retries automatically or changes resources',async()=>{const f=fixture();let calls=0;f.context.generateQuietPrompt=async()=>{calls++;throw Error('Offline');};assert.equal((await f.perform('confirm')).ok,false);assert.equal(calls,1);assert.equal(f.commits(),0);assert.equal(f.state().progression.currency.silver,30);assert.ok(f.runtime.view().error);});
test('invalid decision never saves prose or money and remains explicitly retryable',async()=>{const f=fixture();f.context.generateQuietPrompt=async()=>JSON.stringify({narrative:'Done',decision:{outcome:'accept',amount:7}});assert.equal((await f.perform('confirm')).error,'consent');assert.equal(f.commits(),0);assert.equal(f.state().progression.currency.silver,30);assert.equal(f.context.chat[1].mes,'Rally shows a Potion.');});

test('finishing newest interaction does not reopen an older unanswered catalog',async()=>{const f=fixture();f.context.chat.push({is_user:true,mes:'Show the new catalog'},{is_user:false,mes:'Rally shows a new Potion.',event:normalizeMarketplaceEvent({kind:'npcShop',id:'new-shop',location:'Hall',seller:{name:'Rally'},denomination:'silver',items:[{name:'Potion',price:6}]})});assert.equal((await f.perform('confirm')).ok,true);assert.equal(f.runtime.view(),null);assert.equal(f.commits(),1);});
test('resolved legacy offers never reopen or duplicate a narrative settlement',()=>{const f=fixture();f.context.chat[1].eventStatus='resolved';assert.equal(f.runtime.view(),null);assert.equal(f.calls(),0);});
test('incidental normalization timestamps do not invalidate a genuine action',async()=>{const f=fixture();f.context.generateQuietPrompt=async()=>{f.setState(s=>{s.updatedAt=new Date().toISOString();});return JSON.stringify({narrative:'Done',decision:{outcome:'accept',amount:6}});};assert.equal((await f.perform('confirm')).ok,true);assert.equal(f.commits(),1);});

test('a purchase request opens a waiting composer before the NPC reply without an API call',()=>{const f=fixture();f.context.chat=[{is_user:true,mes:'อยากซื้อของ'}];assert.deepEqual(f.runtime.view().pending,{kind:'buy',waiting:true});assert.equal(f.runtime.view().session,undefined);assert.equal(f.calls(),0);});
test('auction requests with goods vocabulary show only the auction pending state',()=>{const f=fixture();f.context.chat=[{is_user:true,mes:'ขอดูสินค้าประมูล'}];assert.equal(f.runtime.view().pending.kind,'auction');f.settings.enableAuctions=false;assert.equal(f.runtime.view(),null);});
test('future or OOC requests do not open a pending commerce UI',()=>{for(const mes of ['OOC: อยากประมูล','พรุ่งนี้อยากซื้อของ','ยังไม่อยากขาย']){const f=fixture();f.context.chat=[{is_user:true,mes}];assert.equal(f.runtime.view(),null);}});

test('raw native API succeeds while the normal preset would return prose only',async()=>{const f=fixture();let calls=0,quiet=0;f.context.generateQuietPrompt=async()=>{quiet++;return 'Rally offers five silver.';};f.context.generateRaw=async args=>{calls++;assert.match(args.systemPrompt,/Current system: buy/);return 'Rally hands you the potion.\n'+JSON.stringify({decision:{outcome:'accept',amount:6}});};assert.equal((await f.perform('confirm')).ok,true);assert.equal(calls,1);assert.equal(quiet,0);assert.equal(f.state().progression.currency.silver,24);});
for(const [code,raw]of [['response-empty',''],['response-decision','<tr-dialogue name="พ่อค้าผ้าคลุมดำ">ห้าเหรียญเงิน</tr-dialogue>'],['response-narrative','{"decision":{"outcome":"accept","amount":6}}']])test(`failure ${code} exposes copyable raw-response diagnosis and never settles`,async()=>{const f=fixture();f.context.generateRaw=async()=>raw;assert.equal((await f.perform('confirm')).error,code);const report=JSON.parse(f.runtime.view().diagnostics);assert.equal(report.channel,'button');assert.equal(report.action,'confirm');assert.equal(report.system,'buy');assert.equal(report.error,code);assert.equal(report.rawResponse,raw);assert.equal(f.state().progression.currency.silver,30);assert.equal(f.commits(),0);});
test('native No message generated is identified as an empty provider reply instead of a consent or connection error',async()=>{const f=fixture();f.context.generateRaw=async()=>{throw Error('No message generated');};assert.equal((await f.perform('confirm')).error,'response-empty');assert.match(f.runtime.view().error,/empty reply/);assert.equal(f.state().progression.currency.silver,30);});

test('missing opening data triggers one task only and preserves standing NPC bid without touching funds or prose',async()=>{
 const f=fixture(),story='<tr-dialogue name="Auctioneer">Blade เริ่มต้นที่ 5 เหรียญเงิน</tr-dialogue>\n<tr-dialogue name="Fat Merchant">6 เหรียญเงิน!</tr-dialogue>';
 f.context.chat=[{is_user:true,mes:'เข้าร่วมประมูล'},{is_user:false,mes:story}];let calls=0;
 f.context.generateRaw=async args=>{calls++;assert.match(args.systemPrompt,/Recover ONE/);assert.doesNotMatch(args.prompt,/"currency"/);return JSON.stringify({auction:{location:'Hall',evidence:'Blade เริ่มต้นที่ 5 เหรียญเงิน',denomination:'silver',lots:[{id:'blade',name:'Blade',openingBid:5,minIncrement:1,bidders:[{name:'Fat Merchant',budget:18}],currentBid:6,currentBidder:'Fat Merchant'}]}});};
 const input={messageId:1,kind:'auction',user:'เข้าร่วมประมูล',story,location:'Hall'};
 const result=await f.runtime.recoverOpening(input);assert.equal(result.ok,true);assert.equal(result.auction.lots[0].currentBid,6);assert.equal(result.auction.lots[0].bidders[0].budget,18);
 assert.equal((await f.runtime.recoverOpening(input)).error,'skipped');assert.equal(calls,1);assert.equal(f.context.chat[1].mes,story);assert.equal(f.state().progression.currency.silver,30);assert.equal(f.commits(),0);
});
for(const [name,mutate]of [['chat switch',f=>f.context.chatMetadata={}],['new turn',f=>f.context.chat.push({is_user:true,mes:'Next'})],['edit',f=>f.context.chat[1].mes='Edited'],['disable',f=>f.settings.enableAuctions=false],['stop',f=>f.runtime.cancel()]])test(`opening recovery discards stale data after ${name}`,async()=>{
 const f=fixture(),gate=deferred();f.context.generateRaw=()=>gate.promise;
 const request=f.runtime.recoverOpening({messageId:1,kind:'auction',user:'เข้าร่วมประมูล',story:f.context.chat[1].mes,location:'Hall'});mutate(f);gate.resolve('{}');assert.equal((await request).error,'stale');assert.equal(f.commits(),0);assert.equal(f.state().progression.currency.silver,30);
});

test('completed normal replies stop the pending wait even when the host generation flag is late',()=>{
 const f=fixture();f.context.chat=[{is_user:true,mes:'เข้าร่วมประมูล'},{is_user:false,mes:'ไม่มีราคาเปิดรายการในคำตอบนี้'}];
 // Separate instance with no offered event, reproducing a completed prose-only reply.
 let live=true,complete=false;const runtime=createCommerceRuntime({document:{},context:()=>f.context,state:f.state,settings:()=>f.settings,isBusy:()=>live,isReplyComplete:()=>complete,record:()=>null,variant:m=>m.mes,turnKey:id=>String(id),visible:v=>v});
 assert.equal(runtime.view().pending.waiting,true);complete=true;assert.equal(runtime.view().pending.waiting,false);runtime.refresh();runtime.refresh();assert.equal(f.calls(),0);live=false;assert.equal(runtime.view().pending.waiting,false);runtime.destroy();
});
