import test from 'node:test';
import assert from 'node:assert/strict';
import {requestCommerceOpening,validateCommerceOpening,commerceOpeningRefused} from '../src/commerce-opening.js';
import {normalizeAuctionOffer} from '../src/auction-core.js';
import {createCommerceSession,prepareCommerceAction} from '../src/commerce-engine.js';
const story='<tr-dialogue name="Auctioneer">Blade เริ่มต้นที่ 5 เหรียญเงิน</tr-dialogue>\n<tr-dialogue name="Fat Merchant">6 เหรียญเงิน!</tr-dialogue>';
const input={kind:'auction',story,user:'เข้าร่วมประมูล',location:'Hall',eventId:'recovered-turn-1'};
const raw=()=>({auction:{location:'Hall',evidence:'Blade เริ่มต้นที่ 5 เหรียญเงิน',denomination:'silver',lots:[{id:'blade',name:'Blade',openingBid:5,minIncrement:1,bidders:[{name:'Fat Merchant',budget:18}],currentBid:6,currentBidder:'Fat Merchant'}]}});
test('recovered auction survives normalization and direct bid enters above the existing NPC price',()=>{
 const offer=validateCommerceOpening(raw(),input).auction,session=createCommerceSession(normalizeAuctionOffer(offer));assert.equal(offer.id,input.eventId);assert.equal(session.lots[0].price,6);assert.equal(session.participants[0].budget,18);
 const state={commerce:{sessions:[],receipts:[]},progression:{currency:{gold:0,silver:30,copper:0,name:"Coins"}},inventory:[]};assert.equal(prepareCommerceAction(state,session,'bid',{amount:6}).error,'amount');assert.equal(prepareCommerceAction(state,session,'bid',{amount:7}).ok,true);assert.equal(state.progression.currency.silver,30);
});
for(const [name,mutate]of [['omitted standing bid',r=>{delete r.auction.lots[0].currentBid;delete r.auction.lots[0].currentBidder;}],['missing rival',r=>{r.auction.lots[0].bidders=[];delete r.auction.lots[0].currentBid;delete r.auction.lots[0].currentBidder;}],['invented fee',r=>r.auction.entryFee=2],['invented deposit',r=>r.auction.deposit=2],['invented increment',r=>r.auction.lots[0].minIncrement=5],['invented goods',r=>r.auction.lots[0].name='Shield'],['invented price',r=>r.auction.lots[0].openingBid=9],['invented rival',r=>r.auction.lots[0].bidders.push({name:'Mira',budget:18})],['missing budget',r=>delete r.auction.lots[0].bidders[0].budget],['invalid budget',r=>r.auction.lots[0].bidders[0].budget='18'],['unaffordable bid',r=>r.auction.lots[0].bidders[0].budget=5],['player leader',r=>r.auction.lots[0].currentBidder='player'],['invented current bid',r=>r.auction.lots[0].currentBid=7],['invented evidence',r=>r.auction.evidence='The auctioneer displays an auction catalog.'],['wrong location',r=>r.auction.location='Elsewhere'],['money ops',r=>r.ops=[['inc','progression.currency.silver',-6]]]])test(`opening recovery rejects ${name}`,()=>{const r=raw();mutate(r);assert.equal(validateCommerceOpening(r,input),null);});
test('a price attributed only by the auctioneer is not assigned to a different NPC',()=>{assert.equal(validateCommerceOpening(raw(),{...input,story:story.replace('name="Fat Merchant"','name="Auctioneer"')}),null);});
test('opening price may come from the previous reply but current evidence and standing bid must come from this reply',()=>{const latest='<tr-dialogue name="Fat Merchant">6 เหรียญเงิน!</tr-dialogue>';const r=raw();r.auction.evidence='6 เหรียญเงิน!';assert.ok(validateCommerceOpening(r,{...input,story:latest,facts:story}));});
test('shop recovery keeps stock unknown and cannot turn a catalog into a completed purchase',()=>{
 const story='<tr-dialogue name="Rally">ข้าแสดงสินค้าที่ขายในร้านให้ดู Potion: 3 silver</tr-dialogue>',shop={marketplace:{kind:'npcShop',location:'Hall',evidence:'ข้าแสดงสินค้าที่ขายในร้านให้ดู Potion: 3 silver',seller:{name:'Rally'},denomination:'silver',items:[{name:'Potion',price:3,stockKnown:false,negotiableKnown:false}]}};
 const result=validateCommerceOpening(shop,{kind:'buy',story,user:'ขอดูสินค้า',location:'Hall'});assert.equal(result.marketplace.items[0].stockKnown,false);assert.equal(validateCommerceOpening(shop,{kind:'sell',story,user:'ขายสินค้า',location:'Hall'}),null);
});
test('sell recovery needs an owned item and explicit current buyer terms',()=>{
 const story='<tr-dialogue name="Mira">I offer to buy your Potion for 5 silver.</tr-dialogue>',offer={marketplace:{kind:'npcPurchase',location:'Hall',buyer:{name:'Mira',budget:10},item:{itemName:'Potion',quantity:1},askPrice:5,denomination:'silver'}};
 assert.ok(validateCommerceOpening(offer,{kind:'sell',story,user:'ขาย Potion',location:'Hall',inventory:[{name:'Potion',quantity:1}]}));assert.equal(validateCommerceOpening(offer,{kind:'sell',story,user:'ขาย Potion',location:'Hall',inventory:[]}),null);
});
test('refusal detection does not close a present auction for a separate conditional pricing remark',()=>{assert.equal(commerceOpeningRefused('งานประมูลจบแล้ว'),true);assert.equal(commerceOpeningRefused('Blade: 5 silver. หากไม่มีสินค้ารอบหน้าข้าจะปิดประมูล'),false);assert.equal(commerceOpeningRefused('ข้าไม่ขายให้ต่ำกว่า 5 เหรียญเงิน'),false);});
test('native opening task uses one current API request and no story preset',async()=>{let calls=0,quiet=0;await requestCommerceOpening({generateRaw:async args=>{calls++;assert.match(args.systemPrompt,/Return only JSON/);assert.equal(args.responseLength,4096);assert.equal(args.trimNames,false);return '{}';},generateQuietPrompt:async()=>quiet++,chat:[]},input);assert.equal(calls,1);assert.equal(quiet,0);});
test('failed native opening task never retries through the legacy preset',async()=>{let quiet=0;await assert.rejects(requestCommerceOpening({generateRaw:async()=>{throw Error('Offline');},generateQuietPrompt:async()=>quiet++},input));assert.equal(quiet,0);});
