// Production loader, ordinary reply events, saved settings and actual Main Chat DOM.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? `${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright` : 'playwright');
const root=new URL('../',import.meta.url), base='/scripts/extensions/third-party/rpg-systems/';
const server=http.createServer(async(req,res)=>{
 try{const url=new URL(req.url,'http://localhost');
  if(url.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');res.end('[]');return;}
  if(!url.pathname.startsWith(base)||url.pathname.includes('..')){res.writeHead(404).end();return;}
  const path=url.pathname.slice(base.length),body=await readFile(new URL(path,root));
  res.setHeader('content-type',path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.json')?'application/json':path.endsWith('.js')?'text/javascript':'image/webp');res.end(body);
 }catch{res.writeHead(404).end();}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}${base}docs/previews/preview-h-stats.html?lang=th`;
async function captureCard(card,path){
 const style=await card.page().addStyleTag({content:'#send_form,#tretaresia-event-stack,#tretaresia-activity-island{display:none!important}'});
 try{await card.screenshot({path});}finally{await style.evaluate(el=>el.remove());}
}
async function receive(page,user,story,patch){
 await page.evaluate(async user=>{
  window.host.chat.push({is_user:true,name:'Player',mes:user});
  await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_SENT,window.host.chat.length-1);
  await window.host.eventSource.emit(window.host.eventTypes.GENERATION_STARTED,'normal',{},false);
  await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');window.lastNormalPrompt=[...window.prompts.values()].join('\n');window.lastGenerationInjections=structuredClone(window.promptInjections);window.normalCalls=(window.normalCalls||0)+1;
 },user);
 if(user.startsWith('หลังจากจบการประมูล'))assert.equal(await page.locator('.rf-commerce-composer').count(),0,'collection must not reopen a composer during generation');
 if(user==='ขอดูสินค้าประมูล'){await page.locator('.rf-commerce-pending-title').waitFor();assert.equal(await page.locator('.rf-commerce-composer').getAttribute('data-kind'),'auction');assert.equal(await page.locator('.rf-commerce-composer button').count(),0);if(page.viewportSize().width===390&&process.env.COMMERCE_ARTIFACT_DIR){await mkdir(process.env.COMMERCE_ARTIFACT_DIR,{recursive:true});await page.locator(".rf-commerce-composer").screenshot({path:`${process.env.COMMERCE_ARTIFACT_DIR}/auction-waiting-390.png`});}}
 const id=await page.evaluate(({story,patch})=>{
  const id=window.host.chat.length,mes=story+(patch?`\n<!--tretaresia_patch:${JSON.stringify(patch)}-->`:'');
  window.host.chat.push({is_user:false,name:'Narrator',mes,swipe_id:0,swipes:[mes]});
  document.querySelector('#chat').replaceChildren(...window.host.chat.map((message,index)=>{
   const row=document.createElement('div');row.className='mes';row.setAttribute('mesid',index);
   const text=document.createElement('div');text.className='mes_text';text.textContent=message.mes.replace(/<!--tretaresia_patch:[\s\S]*?-->/gu,'');row.append(text);return row;
  })); return id;
 },{story,patch});
 await page.evaluate(async id=>{await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,id,'normal');await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);},id);
 await page.waitForFunction(id=>Object.keys(window.host.chatMetadata.tretaresia_rpg_scene_history||{}).some(key=>key.startsWith(`${id}:`)),id);
 await page.waitForTimeout(200);return page.locator(`#chat .mes[mesid="${id}"]`);
}

let browser;
const spell={kind:'magic',effect:'รวมเปลวไฟแล้วส่งไปยังเป้าหมาย',element:'ไฟ',range:'12 เมตร',target:'หนึ่งเป้าหมาย',costKnown:true,costs:[{resource:'MP',amount:12,note:'เมื่อร่ายจริง'}],cooldown:{value:2,unit:'turns',remaining:0,ready:true,condition:'เริ่มเมื่อใช้เวทสำเร็จ'},strengths:['โจมตีระยะไกล'],weaknesses:['ขัดจังหวะได้'],advantages:['น้ำแข็ง'],disadvantages:['น้ำ'],conditions:['ต้องมีสมาธิ'],incantation:{required:true,language:'th',short:'เปลวเพลิง จงรวมตัวและพุ่งไป!',full:'อัคคีซึ่งหลับใหลในสายลม\nจงตื่นขึ้นและรวมประกายเป็นหนึ่ง\nรับเจตนาของข้าและมุ่งสู่เป้าหมาย\nจงแผดเผา — ลูกไฟแห่งอัคคี!',silent:{available:false,reason:'ยังควบคุมเวทโดยไม่เอ่ยไม่ได้'}}};
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const width of [320,390,1280]){
  const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
  await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
  await page.addInitScript(()=>{localStorage.setItem('roleforge-hstats-preview-settings',JSON.stringify({tretaresia_rpg:{language:'th',enableIncantation:true,npcIncantation:true,autoTrack:true,autoContinuity:false,showSceneTracker:true,enableMarketplace:true,enableAuctions:true,memoryAutoSummary:false}}));localStorage.setItem('roleforge-hstats-preview-metadata',JSON.stringify({tretaresia_rpg_state:{player:{name:'Player'},skills:[],proficiencies:{techniques:[]},location:{narrativeVersion:1,place:'Guild'},onboarding:{locationSeeded:true},progression:{currency:{gold:50,silver:100}}}}));});
  await page.goto(url);await page.waitForFunction(()=>window.hStatsPreview?.ready);
  await page.evaluate(()=>{document.querySelector('#tretaresia-rpg-close').click();document.querySelector('.preview-host').style.display='none';document.querySelector('#chat').style.cssText='display:block;height:600px;overflow:auto;padding:12px';const style=document.createElement('style');style.textContent='#send_form{position:fixed;bottom:0;left:0;width:100%;padding:10px;background:#191919;box-sizing:border-box}#send_textarea{display:block;width:100%;height:60px;box-sizing:border-box;border:1px solid #555;background:#171717;color:#ddd;border-radius:12px}#send_but{height:30px}';document.head.append(style);const form=document.createElement('form');form.id='send_form';form.append(document.querySelector('#send_textarea'));const send=document.createElement('button');send.type='button';send.id='send_but';send.textContent='ส่ง';form.append(send);document.body.append(form);window.calls=0;window.apiNotices=[];window.toastr.info=(message,title,options)=>{if(title==='RoleForge · API')window.apiNotices.push({message,options});};window.prompts=new Map();window.promptInjections={};window.host.setExtensionPrompt=(key,value)=>window.prompts.set(key,value);window.host.generateQuietPrompt=async args=>{window.calls++;if(window.apiNotices.length!==window.calls)throw Error("API notice must precede the training request");window.lastTrainingPrompt=args.quietPrompt;if(window.deferTraining){window.deferTraining=false;await new Promise(resolve=>window.releaseTraining=resolve);}return JSON.stringify({outcome:'success',title:'ควบคุมได้ดีขึ้น',narration:'คุณรักษารูปเปลวไฟได้มั่นคงขึ้น',masteryDelta:2,reason:'ฝึกจริง',nextPrompt:'ฝึกต่อ'});};Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.copied=value}});});
  await receive(page,'ฉันเรียน Fire Ball','<tr-narrative>คุณเรียนรู้วิชา Fire Ball พร้อมบทร่าย</tr-narrative>',{ops:[['upsert','proficiencies.customMagic',{id:'frost',name:'Frost',proficiency:0,description:'เวทที่เริ่มฝึก'}],['upsert','proficiencies.techniques',{id:'fire',name:'Fire Ball',category:'Magic',proficiency:39,description:'ลูกไฟ',ability:spell}],['upsert','skills',{id:'blade',name:'เพลงดาบ',type:'Physical',mastery:10,description:'วิชาดาบ',ability:{kind:'physical',effect:'ฟันดาบ',incantation:{required:false}}}]]});
  const ability=page.locator('.rf-incantation').first();await ability.locator('[data-ability-select]').selectOption('technique:fire');await ability.locator('[data-ability-action="mode-full"]').click();await ability.locator('[data-ability-action="copy"]').click();assert.equal(await page.evaluate(()=>window.copied),spell.incantation.full);assert.equal(await page.evaluate(()=>window.calls),0);assert.equal(await page.evaluate(()=>window.apiNotices.length),0);assert.equal(await ability.locator('[data-ability-action="mode-silent"]').isDisabled(),true);assert.match(await page.evaluate(()=>window.lastNormalPrompt),/NPC INCANTATION FAIRNESS ENABLED/);
  if(width===390){await mkdir('/workspace/artifacts/incantation-v05111',{recursive:true});await ability.screenshot({path:'/workspace/artifacts/incantation-v05111/full-chant-390.png'});}
  await ability.locator('[data-ability-action="train"]').click();const training=page.locator('.rf-training-composer');await training.locator('[data-ability-action="practice-control"]').click();await training.locator('.rf-training-result').waitFor();assert.equal(await page.evaluate(()=>window.calls),1);assert.match(await page.evaluate(()=>window.apiNotices.at(-1).message),/ฝึก.*API เพิ่ม/);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.proficiencies.techniques[0].proficiency),41);assert.equal(await training.locator('[data-ability-action="again"]').isEnabled(),true);await training.locator('[data-ability-action="stop"]').first().click();await training.waitFor({state:'detached'});
  await ability.locator('[data-ability-select]').selectOption('skill:blade');assert.equal(await ability.locator('.rf-ability-modes').count(),0);await ability.locator('[data-ability-action="train"]').click();await training.locator('[data-ability-action="practice-application"]').click();await training.locator('.rf-training-result').waitFor();assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.skills[0].mastery),12);await training.locator('[data-ability-action="stop"]').first().click();
  // Moving from the real Power page closes its overlay and opens separate training.
  await page.locator('#tretaresia-rpg-wand-launcher').evaluate(b=>b.click());await page.locator('[data-tab="techniques"]').evaluate(b=>b.click());await page.locator('[data-panel="techniques"] [data-power-id="technique:fire"]').click();assert.equal(await page.locator('#tretaresia-rpg-overlay').evaluate(el=>el.classList.contains('is-open')),false);await training.locator('[data-ability-action="stop"]').first().click();
  await page.locator('#tretaresia-rpg-wand-launcher').evaluate(b=>b.click());await page.locator('[data-tab="techniques"]').evaluate(b=>b.click());await page.locator('[data-panel="techniques"] [data-power-id="frost"]').click();assert.match(await training.innerText(),/Frost/);await training.locator('[data-ability-action="stop"]').first().click();
  // A cancelled pending result must not grant mastery later.
  await ability.locator('[data-ability-select]').selectOption('technique:fire');await ability.locator('[data-ability-action="train"]').click();await page.evaluate(()=>window.deferTraining=true);await training.locator('[data-ability-action="practice-control"]').click();await page.waitForFunction(()=>Boolean(window.releaseTraining));await training.locator('[data-ability-action="stop"]').first().click();await page.evaluate(()=>window.releaseTraining());await page.waitForFunction(()=>!document.querySelector('.rf-training-composer'));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.proficiencies.techniques[0].proficiency),41);
  // Normal patch updates chant mastery once; partial metadata preserves full chants.
  await receive(page,'เปลวเพลิง จงรวมตัวและพุ่งไป! ฉันซ้อมการควบคุม','<tr-narrative>คุณฝึกควบคุมไฟ</tr-narrative>',{ops:[['upsert','proficiencies.techniques',{id:'fire',proficiency:42,ability:{cooldown:{remaining:1,ready:false}}}]]});assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.proficiencies.techniques[0].ability.incantation.full),spell.incantation.full);
  // Duplicate completion and an alternate swipe use the saved variant base, not additive replays.
  await page.evaluate(async()=>{const id=window.host.chat.length-1;await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,id,'normal');await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);});assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.proficiencies.techniques[0].proficiency),42);
  await page.evaluate(async()=>{const id=window.host.chat.length-1,m=window.host.chat[id],mes='<tr-narrative>คุณเข้าใจการควบคุมไฟมากขึ้น</tr-narrative><!--tretaresia_patch:'+JSON.stringify({ops:[['upsert','proficiencies.techniques',{id:'fire',proficiency:43}]]})+'-->';m.swipe_id=1;m.mes=mes;m.swipes[1]=mes;await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_SWIPED,id);await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);});await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.proficiencies.techniques[0].proficiency===43);
  // Several independently preserved windows use conditional tabs; minimize is a flat strip.
  await receive(page,'ขอซื้อ Potion','<tr-dialogue name="Rally">Potion สามเหรียญเงิน</tr-dialogue>',{sceneTracker:{loc:'Guild'},marketplace:{kind:'npcShop',id:'test-buy',seller:{name:'Rally'},evidence:'Potion สามเหรียญเงิน',denomination:'silver',items:[{name:'Potion',price:3}]},ops:[]});const commerce=page.locator('.rf-commerce-composer');await commerce.locator('[data-commerce-action="confirm"]').waitFor();await commerce.locator('.rf-commerce-amount').fill('7');await page.locator('[data-dock-panel="abilities"]').click();await ability.locator('[data-ability-action="train"]').click();await training.locator('[data-ability-action="training-minimize"]').click();
  let geometry=await page.evaluate(()=>{const root=document.querySelector('.rf-composer-dock'),form=document.querySelector('#send_form');return {bottom:root.getBoundingClientRect().bottom,top:form.getBoundingClientRect().top,height:root.getBoundingClientRect().height,tabs:root.querySelectorAll('[role="tab"]').length};});assert.equal(geometry.tabs,3);assert.ok(geometry.bottom<=geometry.top);assert.ok(geometry.height<=45);assert.equal(await commerce.isVisible(),false);assert.equal(await ability.isVisible(),false);
  if(width===390){await page.locator('.rf-composer-dock').screenshot({path:'/workspace/artifacts/incantation-v05111/minimized-tabs-390.png'});}
  await page.locator('[data-dock-panel="commerce"]').click();assert.equal(await commerce.locator('.rf-commerce-amount').inputValue(),'7');assert.equal(await training.isVisible(),false);await page.locator('[data-dock-panel="training"]').click();assert.equal(await training.isVisible(),true);assert.equal(await commerce.isVisible(),false);
  if(width===390)await page.locator('.rf-composer-dock').screenshot({path:'/workspace/artifacts/incantation-v05111/separate-windows-390.png'});
  await training.locator('[data-ability-action="stop"]').first().click();
  // Hiding the window does not remove the instruction; NPC enforcement is independent.
  await page.evaluate(async()=>{document.querySelector('#tretaresia-rpg-incantation').click();await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');});assert.equal(await page.locator('.rf-incantation').count(),0);assert.match(await page.evaluate(()=>window.prompts.get('tretaresia_rpg_response_contract')),/even when.*hidden/);
  await page.evaluate(async()=>{document.querySelector('#tretaresia-rpg-npc-incantation').click();await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');});assert.match(await page.evaluate(()=>window.prompts.get('tretaresia_rpg_response_contract')),/NPC incantation enforcement is disabled/);
  assert.equal(errors.length,0,errors.join('\n'));console.log('Incantation production integration passed at '+width+'px');await page.close();
 }

 const dockPage=await browser.newPage({viewport:{width:390,height:800}});await dockPage.goto(url);await dockPage.waitForFunction(()=>window.hStatsPreview?.ready);await dockPage.evaluate(()=>document.querySelector('#tretaresia-rpg-close').click());
 await dockPage.evaluate(async base=>{
  document.querySelector('.preview-host').style.display='none';const input=document.querySelector('#send_textarea');input.style.display='block';const form=document.createElement('form');form.id='send_form';form.style.cssText='position:fixed;bottom:0;left:0;width:100%;height:110px;background:#111';form.append(input);const send=document.createElement('button');send.id='send_but';send.textContent='Send';form.append(send);document.body.append(form);
  const {createComposerDock}=await import(base+'src/composer-dock.js');const {createMemoryComposerStatus}=await import(base+'src/memory-composer-status.js');window.testDock=createComposerDock({language:()=> 'th'});for(const id of ['abilities','training','commerce']){const n=document.createElement('section');n.dataset.testPanel=id;n.style.cssText='height:150px;flex-shrink:0;border:1px solid #777';n.textContent=id;window.testDock.panel(id,n);}
  window.testMemory=createMemoryComposerStatus({dock:window.testDock,language:()=> 'th'});window.testMemory.update({enabled:true,chatId:'test',settings:{enableMemorySummaries:true,language:'th'},job:{status:'summarizing',startedAt:new Date().toISOString(),requestActive:true}},{liveGeneration:false});
 },base);await dockPage.waitForTimeout(150);const separate=await dockPage.evaluate(()=>{const root=document.querySelector('.rf-composer-dock'),form=document.querySelector('#send_form');return {panels:root.querySelectorAll('[data-test-panel]').length,status:root.querySelectorAll('.rf-memory-composer-status').length,bottom:root.getBoundingClientRect().bottom,top:form.getBoundingClientRect().top};});assert.equal(separate.panels,3);assert.equal(separate.status,1);assert.ok(separate.bottom<=separate.top);await dockPage.evaluate(()=>{window.testMemory.destroy();window.testDock.destroy();});await dockPage.close();console.log('Conditional window tabs and passive Summary placement passed');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
