import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeAbility,learnedAbilities,abilityLevel,abilityTrainingTargets,writeAbilityTrainingMastery,abilityPromptReference,incantationInstructions} from '../src/incantation-core.js';
import {beginPowerTraining,applyPowerTrainingResult,normalizePowerMastery} from '../src/power-mastery.js';
const spell={kind:'magic',effect:'Fire',costKnown:false,incantation:{required:true,short:'fire now',full:'embers wake\nfire gather\nflame fly',silent:{available:false,reason:'learn control'}}};
test('partial cost and cooldown updates preserve established chants and explicit unknown costs',()=>{const a=normalizeAbility(spell);assert.equal(normalizeAbility(a).costKnown,false);const b=normalizeAbility({cooldown:{remaining:1}},a);assert.equal(b.incantation.full,spell.incantation.full);assert.equal(b.cooldown.remaining,1);assert.equal(b.cooldown.ready,null);const c=normalizeAbility({incantation:{silent:{available:true}}},b);assert.equal(c.incantation.silent.reason,'learn control');assert.equal(c.incantation.short,'fire now');assert.equal(normalizeAbility(null,c),null);});
test('skill and technique with same id train separately and mastery never resets across rank boundaries',()=>{const state={skills:[{id:'fire',name:'Fire',mastery:39,ability:spell}],proficiencies:{techniques:[{id:'fire',name:'Blade',proficiency:59}]}};const targets=abilityTrainingTargets(state);assert.notEqual(targets[0].id,targets[1].id);const session=beginPowerTraining(targets[0]);assert.equal(normalizePowerMastery({session}).session.kind,'skill');const result=applyPowerTrainingResult({entries:{'skill:fire':{value:39}}},{...session,choiceId:'control'},{outcome:'success',title:'Practice',narration:'Good',masteryDelta:2});writeAbilityTrainingMastery(state,targets[0],result.entries['skill:fire'].value);assert.equal(state.skills[0].mastery,41);assert.equal(learnedAbilities(state)[0].level,'Adept');assert.equal(state.proficiencies.techniques[0].proficiency,59);assert.equal(abilityLevel(100),'Mythic');});
test('multiline full chants survive normalization and own nonapplicable values stay distinct from unknown',()=>{const a=normalizeAbility({...spell,costKnown:true,costs:[],cooldown:{unit:'none',value:0,ready:true},weaknesses:['water']});assert.equal(a.incantation.full.split('\n').length,3);assert.equal(a.costKnown,true);assert.equal(a.cooldown.unit,'none');assert.equal(normalizeAbility({effect:'unknown'}).cooldown,null);});
test('normal prompt obeys hidden-window rules, NPC switch and chant power mechanics',()=>{const hidden=incantationInstructions({enableIncantation:false,npcIncantation:true,incantationLanguage:'custom',incantationCustomLanguage:'Elven'});assert.match(hidden,/even when.*hidden/);assert.match(hidden,/Elven/);assert.match(hidden,/NPC INCANTATION FAIRNESS ENABLED/);assert.match(hidden,/extremely powerful/);assert.match(hidden,/never reset/);assert.match(hidden,/SAME normal story reply/);assert.match(incantationInstructions({npcIncantation:false}),/enforcement is disabled/);});
test('named or pasted chants include relevant full metadata while unrelated references omit chant payload',()=>{const state={skills:[{id:'fire',name:'Fire',mastery:2,ability:spell}],proficiencies:{techniques:[]}};assert.equal(abilityPromptReference(state,'travel')[0].ability.incantation.full,undefined);assert.equal(abilityPromptReference(state,'fire now')[0].ability.incantation.full,spell.incantation.full);});
