import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`:'playwright');
const root=new URL('../',import.meta.url),base='/scripts/extensions/third-party/rpg-systems/',artifacts=new URL('docs/previews/items-v0560/',root).pathname;await mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');res.end('[]');return;}if(!u.pathname.startsWith(base)||u.pathname.includes('..')){res.writeHead(404).end();return;}const file=u.pathname.slice(base.length);res.setHeader('content-type',file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.json')?'application/json':file.endsWith('.js')?'text/javascript':'image/webp');res.end(await readFile(new URL(file,root)));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}${base}docs/previews/preview-h-stats.html?lang=th`;
const potion={id:'potion',name:'ยาฟื้นกำลัง',category:'Potion',quantity:3,description:'ยาฟื้นกำลังลดความอ่อนล้า',usage:{action:'drink',consumable:true,effect:'ฟื้นกำลังเล็กน้อย',conditions:[],target:'self',cooldown:{unit:'none',value:0}}};
const apple={id:'apple',name:'Red Apple',category:'Food',quantity:4,description:'A fresh red apple.'};
async function start(page,user){await page.evaluate(async user=>{window.host.chat.push({is_user:true,name:'Noah',mes:user});await window.host.eventSource.emit('MESSAGE_SENT',window.host.chat.length-1);await window.host.eventSource.emit('GENERATION_STARTED','normal',{},false);await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');},user);}
async function finish(page,story,patch){const id=await page.evaluate(({story,patch})=>{const id=window.host.chat.length,mes=story+(patch?`\n<!--tretaresia_patch:${JSON.stringify(patch)}-->`:'');window.host.chat.push({is_user:false,name:'Narrator',mes,swipe_id:0,swipes:[mes]});const row=document.createElement('div');row.className='mes';row.setAttribute('mesid',id);const text=document.createElement('div');text.className='mes_text';text.textContent=story;row.append(text);document.querySelector('#chat').append(row);return id;},{story,patch});await page.evaluate(async id=>{await window.host.eventSource.emit('MESSAGE_RECEIVED',id,'normal');await window.host.eventSource.emit('GENERATION_ENDED');},id);await page.waitForFunction(id=>Object.keys(window.host.chatMetadata.tretaresia_rpg_scene_history||{}).some(k=>k.startsWith(id+':')),id);await page.waitForTimeout(300);return id;}
async function openItem(page,id){await page.evaluate(()=>document.querySelector('#tretaresia-rpg-wand-launcher').click());await page.locator('#tretaresia-rpg-overlay').waitFor({state:'visible'});await page.evaluate(()=>document.querySelector('[data-tab="inventory"]').click());await page.locator(`[data-action="select-item"][data-id="${id}"]`).waitFor({state:'visible'});if(!await page.evaluate(()=>window.inventoryCaptured)){await page.waitForTimeout(350);await page.screenshot({animations:'disabled',path:artifacts+`inventory-${page.viewportSize().width}.png`});await page.evaluate(()=>window.inventoryCaptured=true);}await page.locator(`[data-action="select-item"][data-id="${id}"]`).click();await page.locator('#rf-dock-panel-items').waitFor({state:'visible'});assert.equal(await page.locator('#tretaresia-rpg-overlay').isVisible(),false);}
const receipts=page=>page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.itemSystem.receipts.length);
const amount=(page,id)=>page.evaluate(id=>window.host.chatMetadata.tretaresia_rpg_state.inventory.find(i=>i.id===id)?.quantity||0,id);
async function done(page,count){await page.waitForFunction(count=>window.host.chatMetadata.tretaresia_rpg_state.itemSystem?.receipts?.length===count,count);await page.waitForTimeout(100);}
let browser;
try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const width of [320,390,1280]){
 const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message);});page.setDefaultTimeout(12000);await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
 await page.addInitScript(({potion,apple})=>{localStorage.setItem('roleforge-hstats-preview-settings',JSON.stringify({tretaresia_rpg:{language:'th',autoTrack:true,autoContinuity:false,chatPresentation:true,enableMemorySummaries:false,enableVoiceAddon:false,enableIncantation:true,enableMarketplace:true,enableAuctions:false,eventNotifications:false}}));localStorage.setItem('roleforge-hstats-preview-metadata',JSON.stringify({tretaresia_rpg_state:{player:{name:'Noah',stamina:{current:50,max:100}},inventory:[potion,apple,{id:'sword',name:'ดาบเหล็ก',quantity:1,category:'Weapon',description:'ดาบธรรมดา'},{id:'unknown',name:'ขวดน้ำยาที่ไม่มีฉลาก',quantity:1,category:'Potion',description:'ของเหลวที่ยังไม่ทราบคุณสมบัติ'},{id:'key',name:'กุญแจห้องพักเดี่ยวชั้นบน',quantity:1,category:'Key',description:'เปิดห้องพักของคุณ',commerceRightId:'room-right'},...Array.from({length:7},(_,i)=>({id:'tool-'+i,name:'เครื่องมือ '+i,category:'Tool',quantity:1,description:'เครื่องมือทั่วไป'}))],commerce:{rights:[{id:'room-right',itemName:'ห้องพักเดี่ยวชั้นบน',location:'Oakland Inn',provider:{name:'Garrick',npcId:'g'},history:[],revision:0,status:'active',paid:190,depositPaid:0,depositRefunded:0,remainingUses:0,denomination:'copper',starts:{day:1,time:'09:00'},ends:{day:2,time:'12:00'},terms:{mode:'access',scope:'ห้องพักเดี่ยวชั้นบน',durationMinutes:1440,delivery:{name:'กุญแจห้องพักเดี่ยวชั้นบน',category:'Key'}},inventoryItemId:'key'}]},npcs:[{id:'g',name:'Garrick',title:'เจ้าของโรงเตี๊ยม',met:true,enabled:true},{id:'m',name:'Mira',met:true,enabled:true}],location:{place:'Oakland Inn',narrativeVersion:1},onboarding:{identitySeeded:true,locationSeeded:true,loadoutSeeded:true},worldClock:{day:1,time:'10:00'}}}));},{potion,apple});
 await page.goto(url);await page.waitForFunction(()=>window.hStatsPreview?.ready);
 await page.evaluate(()=>{document.querySelector('#tretaresia-rpg-close').click();document.querySelector('.preview-hstats-bar')?.remove();const chat=document.querySelector('#chat');chat.style.display='block';const form=document.createElement('form');form.id='send_form';const input=document.querySelector('#send_textarea');input.style.cssText='display:block;width:100%;min-height:48px';input.placeholder='พิมพ์โรล…';form.append(input);const send=document.createElement('button');send.id='send_but';send.type='button';send.textContent='ส่ง';send.hidden=true;form.append(send);form.style.cssText='position:fixed;bottom:0;left:8px;right:8px;height:72px;background:#18191d;z-index:10;padding:12px';document.body.append(form);window.calls=[];window.prompts=new Map();window.host.setExtensionPrompt=(key,value)=>window.prompts.set(key,value);window.outcome='success';window.host.generateRaw=async options=>{window.calls.push(options);await window.host.eventSource.emit('GENERATION_STARTED','quiet',{},false);await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'quiet');window.itemInjected=[...window.prompts.values()].join('\n');const request=JSON.parse(options.prompt.split('REQUEST:\n')[1].split('\nREFERENCE DATA:')[0]);if(request.action==='enrich'){if(window.holdDetails)await new Promise(resolve=>window.resolveDetails=resolve);const result={requestId:request.id,items:request.items.map(({item,missing})=>({id:item.id,description:missing.includes('description')?'เครื่องมือทั่วไปที่มีอยู่ในคลัง':item.description,usage:{action:item.id==='unknown'?'unknown':item.usage.action==='unknown'?'use':item.usage.action,consumable:item.usage.consumable,effect:item.id==='unknown'?'ยังไม่ทราบ':'ใช้งานตามคุณสมบัติที่ระบุในเรื่อง',conditions:[item.id==='unknown'?'ต้องตรวจสอบก่อนใช้งาน':'ไม่มีเงื่อนไขพิเศษ'],target:item.id==='unknown'?'ยังไม่ทราบ':'เป้าหมายตามชนิดไอเทม',cooldown:{unit:item.id==='unknown'?'unknown':'none',value:0}}}))};if(window.failDetailsOnce&&request.id.endsWith('-6')){window.failDetailsOnce=false;result.requestId='wrong-request';}await window.host.eventSource.emit('GENERATION_ENDED');return JSON.stringify(result);}const names=request.entries?.map(e=>e.item.name).join(' และ ')||request.item.name;const evidence=(request.action==='gift'?request.npc.name+(window.outcome==='refused'?' ไม่รับ ':' รับ '):request.action==='drop'?'วางทิ้ง ':request.action==='collect'?'เก็บ ':'ใช้ ')+names+' เรียบร้อย';const raw={narrative:`<tr-narrative>${evidence}</tr-narrative>`,itemAction:{requestId:request.id,outcome:window.outcome,reason:'ผลตามการกระทำที่ยืนยัน',evidence,meters:request.action==='use'&&request.item.id==='potion'?[{meter:'stamina',delta:5,reason:'ฟื้นกำลัง',evidence}]:[]}};if(window.plain)raw.narrative=evidence;if(window.hold){await new Promise(resolve=>window.resolveTask=resolve);}await window.host.eventSource.emit('GENERATION_ENDED');return JSON.stringify(raw);};});
 await start(page,'ฉันเปิดหีบและดูว่ามีอะไรให้เก็บบ้าง');const lootStory='<tr-narrative>พบยาฟื้นกำลัง 3 ขวด และดาบเหล็ก 1 เล่มในหีบไม้</tr-narrative><tr-dialogue name="Garrick">เลือกเก็บของที่ต้องการได้</tr-dialogue>';
 const originalId=await finish(page,lootStory,{loot:[{id:'chest',title:'หีบไม้ข้างเคาน์เตอร์',evidence:'พบยาฟื้นกำลัง 3 ขวด และดาบเหล็ก 1 เล่มในหีบไม้',items:[potion,{id:'sword',name:'ดาบเหล็ก',quantity:1,category:'Weapon',description:'ดาบธรรมดา'}]}],sceneTracker:{location:'Oakland Inn',participants:['Garrick','Mira'],day:1,time:'10:00'}});
 assert.equal(await page.evaluate(()=>window.calls.length),0);assert.equal(await amount(page,'potion'),3);const loot=page.locator('#rf-dock-panel-loot');if(!await loot.count())console.log('LOOT DEBUG',await page.evaluate(()=>({system:JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.itemSystem),mes:window.host.chat.at(-1).mes,dom:document.querySelector('.rf-composer-dock')?.innerHTML,checkpoints:window.host.chatMetadata.tretaresia_rpg_turn_history})));await loot.waitFor({state:'visible'});await page.locator('.rf-composer-dock').screenshot({path:artifacts+`loot-compact-${width}.png`});await loot.locator('[data-item-action="loot-expand"]').click();await loot.locator('[data-item-loot]').first().check();await loot.locator('[data-item-quantity]').fill('2');await loot.locator('[data-item-quantity]').dispatchEvent('change');await page.locator('.rf-composer-dock').screenshot({path:artifacts+`loot-selected-${width}.png`});await loot.locator('[data-item-action="loot-detail"]').first().click();await page.locator('.rf-composer-dock').screenshot({path:artifacts+`loot-details-${width}.png`});await loot.locator('[data-item-action="loot-back"]').click();const original=await page.evaluate(id=>window.host.chat[id].mes,originalId);await loot.locator('[data-item-action="collect"]').click();await done(page,1);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`result-success-${width}.png`});assert.equal(await amount(page,'potion'),5);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.itemSystem.loot[0].entries[0].remaining),1);assert.ok((await page.evaluate(id=>window.host.chat[id].mes,originalId)).startsWith(original));assert.equal(await page.evaluate(()=>window.calls.length),1);assert.equal(await page.evaluate(()=>window.itemInjected.trim()), '');
 await openItem(page,'potion');const item=page.locator('#rf-dock-panel-items');await page.locator('.rf-composer-dock').screenshot({path:artifacts+`item-summary-${width}.png`});await item.locator('[data-item-action="details"]').click();await page.locator('.rf-composer-dock').screenshot({path:artifacts+`drink-details-${width}.png`});await item.locator('[data-item-action="details"]').click();await item.locator('[data-item-action="use"]').click();await done(page,2);assert.equal(await amount(page,'potion'),4);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.stamina.current),55);
 await openItem(page,'apple');await page.locator('.rf-composer-dock').screenshot({path:artifacts+`eat-summary-${width}.png`});await item.locator('[data-item-action="gift"]').click();assert.equal(await item.locator('[data-item-action="recipient"]').count(),2);await item.locator('[data-item-action="recipient"][data-item-id="g"]').click();await page.locator('.rf-composer-dock').screenshot({path:artifacts+`gift-${width}.png`});await page.evaluate(()=>window.outcome='refused');await item.locator('[data-item-action="confirm-gift"]').click();await done(page,3);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`result-refusal-${width}.png`});assert.equal(await amount(page,'apple'),4);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.itemSystem.transfers.length),0);await page.evaluate(()=>window.outcome='success');
 await openItem(page,'apple');await item.locator('[data-item-action="gift"]').click();await item.locator('[data-item-action="recipient"][data-item-id="m"]').click();await item.locator('[data-item-action="confirm-gift"]').click();await done(page,4);assert.equal(await amount(page,'apple'),3);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.itemSystem.transfers[0].npcId),'m');
 await openItem(page,'apple');await item.locator('[data-item-action="drop"]').click();await page.locator('.rf-composer-dock').screenshot({path:artifacts+`drop-${width}.png`});await item.locator('[data-item-action="confirm-drop"]').click();await done(page,5);assert.equal(await amount(page,'apple'),2);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.itemSystem.loot.filter(p=>p.origin==='drop').length),1);
 await openItem(page,'sword');await item.locator('[data-item-action="use"]').click();await done(page,6);assert.equal(await amount(page,'sword'),1);
 // A request queued while the main reply is generating is appended to the new reply, not the old bubble.
 await openItem(page,'potion');await start(page,'ฉันย้ายมานั่งที่โต๊ะริมหน้าต่าง');const oldBefore=await page.evaluate(id=>window.host.chat[id].mes,originalId),callsBefore=await page.evaluate(()=>window.calls.length);await item.locator('[data-item-action="use"]').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.calls.length),callsBefore);assert.match(await item.innerText(),/รอคำตอบถัดไป/);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`queued-${width}.png`});const nextId=await finish(page,'<tr-narrative>เสียงพูดคุยในโรงเตี๊ยมดังคลอเบา ๆ</tr-narrative><tr-dialogue name="Garrick">นั่งพักก่อนได้</tr-dialogue>',{sceneTracker:{participants:['Garrick','Mira'],location:'Oakland Inn'}});await done(page,7);assert.equal(await page.evaluate(id=>window.host.chat[id].mes,originalId),oldBefore);assert.match(await page.evaluate(id=>window.host.chat[id].mes,nextId),/ใช้ ยาฟื้นกำลัง/);assert.equal(await amount(page,'potion'),3);
 // Plain prose is rejected. Retrying is explicit and produces only one accepted delta.
 await openItem(page,'apple');await page.evaluate(()=>window.plain=true);await item.locator('[data-item-action="use"]').click();await page.waitForFunction(()=>document.querySelector('#rf-dock-panel-items [role="alert"]'));assert.equal(await amount(page,'apple'),2);assert.equal(await receipts(page),7);await page.evaluate(()=>window.plain=false);await item.locator('[data-item-action="retry"]').click();await done(page,8);assert.equal(await amount(page,'apple'),1);
 // Failed save restores the appended text, inventory, receipts and scene/checkpoint metadata before retry.
 await openItem(page,'potion');const before=await page.evaluate(id=>({text:window.host.chat[id].mes,inventory:window.host.chatMetadata.tretaresia_rpg_state.inventory,receipts:window.host.chatMetadata.tretaresia_rpg_state.itemSystem.receipts}),nextId);await page.evaluate(()=>{const save=window.host.saveMetadata;window.host.saveMetadata=async()=>{window.host.saveMetadata=save;throw Error('test disk full');};});await item.locator('[data-item-action="use"]').click();await page.waitForFunction(()=>document.querySelector('#rf-dock-panel-items [role="alert"]'));assert.equal(await amount(page,'potion'),3);assert.equal(await receipts(page),8);assert.equal(await page.evaluate(id=>window.host.chat[id].mes,nextId),before.text);await item.locator('[data-item-action="retry"]').click();await done(page,9);assert.equal(await amount(page,'potion'),2);
 // A typed action with both itemEvents and a duplicate inventory op is applied exactly once, no API.
 const typed='ฉันกิน Red Apple 1 ผล';await start(page,typed);const typedCalls=await page.evaluate(()=>window.calls.length);await finish(page,'<tr-narrative>ใช้ Red Apple เรียบร้อย</tr-narrative>',{itemEvents:[{id:'typed-eat',action:'use',itemId:'apple',quantity:1,outcome:'success',userEvidence:typed,evidence:'ใช้ Red Apple เรียบร้อย',reason:'กินแอปเปิล'}],ops:[['inc','inventory',{id:'apple',name:'Red Apple',quantity:-1},{category:'use'}]],sceneTracker:{participants:[],location:'Oakland Inn'}});assert.equal(await amount(page,'apple'),0);assert.equal(await receipts(page),10);assert.equal(await page.evaluate(()=>window.calls.length),typedCalls);
 // No NPC is chosen from registry outside the current scene.
 await openItem(page,'potion');assert.equal(await item.locator('[data-item-action="gift"]').isEnabled(),false);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`no-npc-${width}.png`});
 // Minimize and tab navigation preserve separate panels; no layout overflows at narrow widths.
 await item.locator('[data-item-action="minimize"]').click();await page.locator('.rf-composer-dock').screenshot({path:artifacts+`minimized-${width}.png`});assert.equal(await page.locator('.rf-composer-dock').getAttribute('class').then(x=>x.includes('is-minimized')),true);await page.locator('[data-dock-collapse]').click();await page.locator('[data-dock-panel="items"]').click();const fit=await item.evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));assert.ok(fit.scroll<=fit.client+1,JSON.stringify(fit));// Unknown contents have an explicit disabled explanation; existing rented keys use their entitlement.
 const browsingCalls=await page.evaluate(()=>window.calls.length);await openItem(page,'unknown');assert.equal(await item.locator('[data-item-action="use"]').isEnabled(),false);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`unknown-${width}.png`});await item.locator('[data-item-action="inspect"]').click();assert.match(await page.locator('#send_textarea').inputValue(),/ตรวจสอบ.*ขวดน้ำยาที่ไม่มีฉลาก/);await openItem(page,'key');assert.equal(await item.locator('[data-item-action="use"]').isEnabled(),true);assert.equal(await item.locator('[data-item-action="drop"]').isEnabled(),false);assert.equal(await item.locator('[data-item-action="gift"]').isEnabled(),false);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`key-${width}.png`});assert.equal(await page.evaluate(()=>window.calls.length),browsingCalls);await openItem(page,'potion');
 // Discarding an in-flight result must not save narration or consume an item.
 const cancelledText=await page.evaluate(()=>window.host.chat.at(-1).mes);await page.evaluate(()=>{window.hold=true;window.resolveTask=null;});await item.locator('[data-item-action="use"]').click();await page.waitForFunction(()=>typeof window.resolveTask==='function');await item.locator('[data-item-action="cancel"]').click();await page.evaluate(()=>{window.hold=false;window.resolveTask();});await page.waitForTimeout(350);assert.equal(await amount(page,'potion'),2);assert.equal(await receipts(page),10);assert.equal(await page.evaluate(()=>window.host.chat.at(-1).mes),cancelledText);
 // Filling details scans all inventory and batches only incomplete entries, keeping saved batches after a later failure.
 await openItem(page,'potion');const detailsBefore=await page.evaluate(()=>({quantities:window.host.chatMetadata.tretaresia_rpg_state.inventory.map(i=>[i.id,i.quantity]),currency:window.host.chatMetadata.tretaresia_rpg_state.progression.currency,text:window.host.chat.at(-1).mes,calls:window.calls.length}));await page.evaluate(()=>window.failDetailsOnce=true);await item.locator('[data-item-action="enrich"]').click();await page.waitForFunction(()=>document.querySelector('#rf-dock-panel-items [role="alert"]'));assert.equal(await page.evaluate(()=>window.calls.length),detailsBefore.calls+2);assert.match(await item.innerText(),/6 \/ 11/);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`details-partial-${width}.png`});await page.evaluate(()=>{window.holdDetails=true;window.resolveDetails=null;});await item.locator('[data-item-action="retry"]').click();await page.waitForFunction(()=>typeof window.resolveDetails==='function');await page.locator('.rf-composer-dock').screenshot({path:artifacts+`details-working-${width}.png`});await openItem(page,'sword');assert.match(await item.innerText(),/เติมข้อมูล.*0 \/ 6/s);await page.evaluate(()=>{window.holdDetails=false;window.resolveDetails();});await page.waitForFunction(()=>document.querySelector('#rf-dock-panel-items .rf-item-result-title')?.textContent.includes('บันทึกผล'));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.calls.length),detailsBefore.calls+3);assert.deepEqual(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.map(i=>[i.id,i.quantity])),detailsBefore.quantities);assert.deepEqual(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency),detailsBefore.currency);assert.equal(await page.evaluate(()=>window.host.chat.at(-1).mes),detailsBefore.text);assert.equal(await receipts(page),10);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.find(i=>i.id==='potion').usage.conditions.length),1);await page.locator('.rf-composer-dock').screenshot({path:artifacts+`details-updated-${width}.png`});await item.locator('[data-item-action="continue"]').click();await item.locator('[data-item-action="pick"][data-item-id="unknown"]').click();assert.equal(await item.locator('[data-item-action="use"]').isEnabled(),false);
 // Scene changes while queued stop the request without dispatching another API.
 await openItem(page,'potion');await start(page,'ฉันเดินออกไปยังถนน');const sceneCalls=await page.evaluate(()=>window.calls.length);await item.locator('[data-item-action="use"]').click();await finish(page,'<tr-narrative>ออกมายังถนนใน Oakland</tr-narrative>',{sceneTracker:{participants:[],location:'Oakland Road'}});await page.waitForFunction(()=>document.querySelector('#rf-dock-panel-items [role="alert"]'));assert.equal(await amount(page,'potion'),2);assert.equal(await receipts(page),10);assert.equal(await page.evaluate(()=>window.calls.length),sceneCalls);await item.locator('[data-item-action="back"]').click();assert.equal(await item.locator('[role="alert"]').count(),0);
 assert.deepEqual(errors,[]);console.log(`PASS ${width}px: actual loader, inline Loot without API, partial collection, consumption/meters, refusal and gift custody, recoverable drop, reusable weapon, next-reply queue, explicit retry, save rollback, typed action once, NPC scene filter, tabs/minimize, inventory-wide detail batches with partial failure/retry and preserved facts/quantities, and responsive UI.`);await page.close();
}
}finally{await browser?.close();await new Promise(r=>server.close(r));}
