import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeItemUsage,normalizeItemSystem,itemRecord,ingestLoot,currentItemNpcs,itemAvailability,prepareItemAction,validateItemResponse,applyItemDecision,applyStoryItemEvents} from '../src/item-core.js';
const apple=()=>itemRecord({id:'apple',name:'Red Apple',category:'Food',description:'A fresh apple.',quantity:4});
const potion=()=>itemRecord({id:'potion',name:'ยาฟื้นกำลัง',category:'Potion',quantity:3,description:'ยาลดความอ่อนล้า',usage:{action:'drink',consumable:true,effect:'ลดความอ่อนล้า',cooldown:{unit:'minutes',value:10}}});
const state=()=>({inventory:[apple(),potion()],itemSystem:normalizeItemSystem(),npcs:[{id:'g',name:'Garrick',enabled:true},{id:'m',name:'Mira',aliases:['มีร่า'],enabled:true},{id:'off',name:'Disabled',enabled:false}],location:{place:'Oakland Inn'},worldClock:{day:1,time:'10:00'},player:{hp:{current:40,max:100},mp:{current:10,max:100},stamina:{current:20,max:100},survival:{hunger:30,thirst:40}},commerce:{rights:[]}});
const source={messageId:3,turnKey:'turn-3',variant:'v1'};
function prep(s,input,id='r1'){const r=prepareItemAction(s,input,{requestId:id,participants:['Garrick','มีร่า'],turn:5});assert.equal(r.ok,true,JSON.stringify(r));return{...r.request,source};}
function response(r,{outcome='success',meters=[],narrative}={}){const names=r.entries?.map(e=>e.item.name).join(' และ ')||r.item.name;const evidence=(r.action==='gift'?r.npc.name+' รับ ':r.action==='drop'?'วางทิ้ง ':r.action==='collect'?'เก็บ ':'ใช้ ')+names+' เรียบร้อย';return{narrative:narrative||`<tr-narrative>${evidence}</tr-narrative>`,itemAction:{requestId:r.id,outcome,reason:'confirmed outcome',evidence,meters}};}
function commit(s,r,options={}){return applyItemDecision(s,r,validateItemResponse(response(r,options),r));}
function loot(s=state()){return ingestLoot(s,[{id:'chest',title:'หีบไม้',location:'Oakland Inn',evidence:'พบ Red Apple 3 ผล และดาบเหล็ก 1 เล่ม',items:[{...apple(),quantity:3},{id:'sword',name:'ดาบเหล็ก',quantity:1,category:'Weapon'}]}],{story:'<tr-narrative>พบ Red Apple 3 ผล และดาบเหล็ก 1 เล่ม</tr-narrative>',source});}

test('known legacy food/key/tools migrate; unknown liquid cannot become a drink',()=>{assert.equal(normalizeItemUsage(null,apple()).action,'eat');assert.equal(normalizeItemUsage(null,{category:'Key'}).consumable,false);assert.equal(normalizeItemUsage(null,{name:'Unlabelled liquid',category:'Potion'}).action,'unknown');assert.equal(prepareItemAction({...state(),inventory:[itemRecord({id:'u',name:'ขวด',quantity:1})]},{action:'use',itemId:'u',quantity:1}).error,'unknown');});
test('Loot discovery is separate from collection and persists once per source variant',()=>{const s=state(),r=loot(s);assert.equal(r.added.length,1);assert.deepEqual(r.next.inventory,s.inventory);const twice=ingestLoot(r.next,[{id:'chest',title:'หีบไม้',location:'Oakland Inn',evidence:'พบ Red Apple 3 ผล และดาบเหล็ก 1 เล่ม',items:[{...apple(),quantity:3}]}],{story:'พบ Red Apple 3 ผล และดาบเหล็ก 1 เล่ม',source});assert.equal(twice.added.length,0);assert.equal(twice.next.itemSystem.loot.length,1);});
for(const [label,patch]of [['wrong evidence',{evidence:'never stated'}],['item absent',{items:[{id:'x',name:'Diamond',quantity:1}]}],['unknown quantity',{items:[{...apple(),quantity:null}]}],['zero quantity',{items:[{...apple(),quantity:0}]}],['negative quantity',{items:[{...apple(),quantity:-2}]}]])test(`Loot rejects ${label} without granting anything`,()=>{const raw={id:'x',title:'Chest',location:'Oakland Inn',evidence:'พบ Red Apple',items:[{...apple(),quantity:1}],...patch};const r=ingestLoot(state(),[raw],{story:'พบ Red Apple',source});assert.equal(r.added.length,0);assert.equal(r.next.inventory[0].quantity,4);});
test('partial pickup merges identical stack, preserves remainder, duplicates and stale revisions are blocked',()=>{const s=loot().next,p=s.itemSystem.loot[0],r=prep(s,{action:'collect',poolId:p.id,revision:p.revision,entries:[{id:p.entries[0].id,quantity:2}]});const a=commit(s,r);assert.equal(a.ok,true);assert.equal(a.next.inventory[0].quantity,6);assert.equal(a.next.itemSystem.loot[0].entries[0].remaining,1);assert.equal(a.next.itemSystem.loot[0].revision,1);assert.equal(commit(a.next,r).error,'duplicate');assert.equal(prepareItemAction(a.next,{action:'collect',poolId:p.id,revision:0,entries:[{id:p.entries[0].id,quantity:1}]},{requestId:'new'}).error,'stale');assert.equal(s.inventory[0].quantity,4);});
test('duplicate selected entry IDs and collecting outside its location are rejected',()=>{const s=loot().next,p=s.itemSystem.loot[0],pick={id:p.entries[0].id,quantity:1};assert.equal(prepareItemAction(s,{action:'collect',poolId:p.id,revision:0,entries:[pick,pick]}).ok,false);s.location.place='Forest';assert.equal(prepareItemAction(s,{action:'collect',poolId:p.id,revision:0,entries:[pick]}).error,'stale');});
test('same display name with different properties does not merge',()=>{const s=state(),l=ingestLoot(s,[{id:'x',title:'Chest',evidence:'พบ Red Apple',items:[{...apple(),description:'Poisoned apple',quantity:1}]}],{story:'พบ Red Apple',source}).next,p=l.itemSystem.loot[0],r=prep(l,{action:'collect',poolId:p.id,revision:0,entries:[{id:p.entries[0].id,quantity:1}]});const next=commit(l,r).next;assert.equal(next.inventory.filter(i=>i.name==='Red Apple').length,2);assert.equal(next.inventory[0].quantity,4);});
test('food use consumes only requested quantity after success and meter effects clamp',()=>{const s=state(),r=prep(s,{action:'use',itemId:'apple',quantity:2});const evidence='ใช้ Red Apple เรียบร้อย';const a=commit(s,r,{meters:[{meter:'hunger',delta:90,reason:'ate',evidence}]});assert.equal(a.next.inventory[0].quantity,2);assert.equal(a.next.player.survival.hunger,100);assert.equal(s.inventory[0].quantity,4);});
for(const outcome of ['refused','failed'])test(`${outcome} use/collect/gift/drop keeps quantities`,()=>{for(const input of [{action:'use',itemId:'apple',quantity:1},{action:'gift',itemId:'apple',quantity:2,npcId:'g'},{action:'drop',itemId:'apple',quantity:3}]){const s=state(),r=prep(s,input),a=commit(s,r,{outcome});assert.equal(a.ok,true);assert.deepEqual(a.next.inventory,s.inventory);assert.equal(a.next.itemSystem.transfers.length,0);assert.equal(a.next.itemSystem.loot.length,0);assert.equal(a.next.itemSystem.receipts.length,1);}});
test('reusable weapon does not decrement and supports finite charges and turn cooldown',()=>{const s=state();s.inventory.push(itemRecord({id:'w',name:'Wand',quantity:1,category:'Weapon',usage:{action:'use',consumable:false,charges:{max:2,remaining:2},cooldown:{unit:'turns',value:2}}}));const r=prep(s,{action:'use',itemId:'w',quantity:1}),a=commit(s,r);assert.equal(a.next.inventory.find(i=>i.id==='w').quantity,1);assert.equal(a.next.inventory.find(i=>i.id==='w').usage.charges.remaining,1);assert.equal(itemAvailability(a.next,a.next.inventory.find(i=>i.id==='w'),{turn:6}).error,'cooldown');assert.equal(itemAvailability(a.next,a.next.inventory.find(i=>i.id==='w'),{turn:7}).ok,true);});
test('story-clock cooldown uses story time, not wall clock',()=>{const s=state(),a=commit(s,prep(s,{action:'use',itemId:'potion',quantity:1})).next;assert.equal(itemAvailability(a,a.inventory.find(i=>i.id==='potion'),{turn:8}).error,'cooldown');a.worldClock.time='10:10';assert.equal(itemAvailability(a,a.inventory.find(i=>i.id==='potion'),{turn:8}).ok,true);});
test('gift recipients must be enabled scene participants and transfer is persisted only on success',()=>{const s=state();assert.deepEqual(currentItemNpcs(s,['มีร่า','Disabled']).map(n=>n.id),['m']);assert.equal(prepareItemAction(s,{action:'gift',itemId:'apple',quantity:1,npcId:'g'},{participants:['Mira']}).error,'npc');const r=prep(s,{action:'gift',itemId:'apple',quantity:2,npcId:'g'}),a=commit(s,r);assert.equal(a.next.inventory[0].quantity,2);assert.equal(a.next.itemSystem.transfers[0].npcId,'g');assert.equal(a.next.itemSystem.transfers[0].item.quantity,2);});
test('drop moves exact quantity to a recoverable pool; collection restores ownership once',()=>{const s=state(),r=prep(s,{action:'drop',itemId:'apple',quantity:3}),a=commit(s,r);assert.equal(a.next.inventory[0].quantity,1);const p=a.next.itemSystem.loot[0];assert.equal(p.origin,'drop');assert.equal(p.entries[0].remaining,3);const collected=commit(a.next,prep(a.next,{action:'collect',poolId:p.id,revision:0,entries:[{id:p.entries[0].id,quantity:3}]},'take-back'));assert.equal(collected.next.inventory[0].quantity,4);assert.equal(collected.next.itemSystem.loot[0].entries[0].remaining,0);});
test('active rented key can be used, never dropped/gifted; expired key cannot be used',()=>{const s=state();s.inventory.push(itemRecord({id:'key',name:'Room key',quantity:1,category:'Key',commerceRightId:'right'}));s.commerce.rights=[{id:'right',revision:0,status:'active',paid:2,depositPaid:0,depositRefunded:0,remainingUses:0,denomination:'silver',starts:{day:1,time:'09:00'},ends:{day:2,time:'12:00'},terms:{mode:'access',scope:'Room',durationMinutes:1440,delivery:{name:'Room key',category:'Key'}},inventoryItemId:'key'}];assert.equal(itemAvailability(s,s.inventory[2]).ok,true);assert.equal(prepareItemAction(s,{action:'drop',itemId:'key',quantity:1}).error,'ownership');s.worldClock={day:3,time:'08:00'};assert.equal(itemAvailability(s,s.inventory[2]).error,'expired');});
for(const [label,mutate]of [['wrong request',o=>o.itemAction.requestId='other'],['plain prose',o=>o.narrative='ใช้ Red Apple เรียบร้อย'],['missing item',o=>{o.narrative='<tr-narrative>Nothing</tr-narrative>';o.itemAction.evidence='Nothing';}],['missing evidence',o=>o.itemAction.evidence='not here'],['currency effect',o=>o.itemAction.meters=[{meter:'gold',delta:10,reason:'x',evidence:'ใช้ Red Apple เรียบร้อย'}]],['script',o=>o.narrative+='<script>evil()</script>']])test(`invalid result ${label} cannot mutate inventory`,()=>{const s=state(),r=prep(s,{action:'use',itemId:'apple',quantity:1}),o=response(r);mutate(o);assert.equal(applyItemDecision(s,r,validateItemResponse(o,r)).ok,false);assert.equal(s.inventory[0].quantity,4);});
test('normal typed use shares receipt engine, precise user evidence and no double invocation',()=>{const s=state(),user='ฉันกิน Red Apple 1 ผล',story='ใช้ Red Apple เรียบร้อย',raw={id:'eat-1',action:'use',itemId:'apple',quantity:1,outcome:'success',userEvidence:user,evidence:story,reason:'ate'};const a=applyStoryItemEvents(s,[raw],{story,user,source,participants:['Garrick'],turn:5});assert.equal(a.next.inventory[0].quantity,3);assert.equal(a.owned.has('apple'),true);assert.equal(applyStoryItemEvents(a.next,[raw],{story,user,source,turn:5}).next.inventory[0].quantity,3);});
for(const user of ['ถ้าฉันกิน Red Apple 1 ผล','ฉันแค่พูดว่าจะกิน Red Apple','ฉันไม่กิน Red Apple'])test(`typed mention does not consume: ${user}`,()=>{const s=state(),raw={id:'x',action:'use',itemId:'apple',quantity:1,outcome:'success',userEvidence:user,evidence:'ใช้ Red Apple เรียบร้อย',reason:'ate'};const a=applyStoryItemEvents(s,[raw],{story:raw.evidence,user,source});assert.equal(a.next.inventory[0].quantity,4);assert.equal(a.errors[0],'consent');});
test('new known metadata survives normalization and default empty state is stable',()=>{assert.deepEqual(normalizeItemSystem(),{version:1,loot:[],transfers:[],receipts:[]});const u=normalizeItemUsage({action:'drink',consumable:true,effect:'Restores stamina',cooldown:{unit:'turns',value:2,lastUse:{day:1,time:'10:00',turn:4}},charges:{max:2,remaining:1}});assert.equal(u.cooldown.lastUse.turn,4);assert.equal(u.charges.remaining,1);});

test('unwrapped trailing text and duplicate meter effects are rejected',()=>{const s=state(),r=prep(s,{action:'use',itemId:'apple',quantity:1}),o=response(r);o.narrative+='plain trailing narration';assert.equal(validateItemResponse(o,r).error,'narrative');const raw=response(r,{meters:[{meter:'hp',delta:3,reason:'food',evidence:'ใช้ Red Apple เรียบร้อย'},{meter:'hp',delta:3,reason:'food',evidence:'ใช้ Red Apple เรียบร้อย'}]});assert.equal(validateItemResponse(raw,r).error,'effects');});
test('batch consumable use cannot exceed finite charges',()=>{const s=state();s.inventory[1].usage.charges={max:3,remaining:1};assert.equal(prepareItemAction(s,{action:'use',itemId:'potion',quantity:2}).error,'charges');const r=prep(s,{action:'use',itemId:'potion',quantity:1});assert.equal(commit(s,r).next.inventory[1].usage.charges.remaining,0);});
test('bounded receipt ledger still reports a newly committed typed event',()=>{const s=state();s.itemSystem.receipts=Array.from({length:240},(_,i)=>({id:'prior-'+i,outcome:'success'}));const user='ฉันกิน Red Apple 1 ผล',story='ใช้ Red Apple เรียบร้อย';const a=applyStoryItemEvents(s,[{id:'eat',action:'use',itemId:'apple',quantity:1,outcome:'success',userEvidence:user,evidence:story,reason:'ate'}],{story,user,source});assert.equal(a.changes,1);assert.equal(a.next.itemSystem.receipts.length,240);assert.equal(a.next.inventory[0].quantity,3);});
test('items reserved for market sale cannot be consumed, dropped or gifted before any API',()=>{const s=state();s.marketplace={listings:[{status:'Active',itemId:'apple',quantity:4}]};for(const action of ['use','drop','gift'])assert.equal(prepareItemAction(s,{action,itemId:'apple',quantity:1,npcId:'g'},{participants:['Garrick']}).error,'reserved');assert.equal(itemAvailability(s,s.inventory[0]).error,'reserved');});
test('dropping reuses an exhausted pool slot without evicting uncollected items',()=>{const s=state(),sample=loot(s).added[0];s.itemSystem.loot=Array.from({length:120},(_,i)=>({...structuredClone(sample),id:'pool-'+i,entries:sample.entries.map(e=>({...e,remaining:0}))}));const a=commit(s,prep(s,{action:'drop',itemId:'apple',quantity:1}));assert.equal(a.ok,true);assert.equal(a.next.itemSystem.loot.length,120);assert.equal(a.next.itemSystem.loot.at(-1).origin,'drop');assert.equal(a.next.inventory[0].quantity,3);});

for(const ending of ['ยังไม่ได้เก็บ','ยังไม่หยิบ','ยังไม่ได้รับ','not yet collected'])test(`discovered but uncollected Loot is valid: ${ending}`,()=>{
 const evidence=`พบ Red Apple 2 ผล ${ending}`;
 const r=ingestLoot(state(),[{id:'basket',evidence,items:[{...apple(),quantity:2}]}],{story:`<tr-narrative>${evidence}</tr-narrative>`,source});
 assert.deepEqual(r.errors,[]);assert.equal(r.added[0].title,'Red Apple');assert.equal(r.added[0].entries[0].remaining,2);assert.deepEqual(r.next.inventory,state().inventory);
});
for(const evidence of ['ยังไม่ได้พบ Red Apple','ไม่ได้พบ Red Apple','ไม่พบ Red Apple','Red Apple not found','did not find Red Apple','hypothetical Red Apple'])test(`undiscovered Loot stays blocked: ${evidence}`,()=>{
 const r=ingestLoot(state(),[{title:'Basket',evidence,items:[{...apple(),quantity:2}]}],{story:evidence,source});assert.equal(r.added.length,0);assert.ok(r.errors.includes('loot-evidence'));
});
test('a malformed entry does not discard confirmed Loot or throw, and repeats cannot duplicate it',()=>{
 const evidence='พบ Red Apple 2 ผล',input=[{id:'basket',title:'Basket',evidence,items:[null,{...apple(),quantity:2},{name:'Unknown contents',quantity:null}]}];
 const r=ingestLoot(state(),input,{story:evidence,source});assert.equal(r.added.length,1);assert.equal(r.added[0].entries.length,1);assert.ok(r.errors.includes('loot-item'));assert.deepEqual(r.next.inventory,state().inventory);
 const again=ingestLoot(r.next,input,{story:evidence,source});assert.equal(again.added.length,0);assert.equal(again.next.itemSystem.loot[0].entries[0].remaining,2);
});
test('another item mentioned elsewhere cannot supply discovery evidence',()=>{
 const evidence='พบ Red Apple 2 ผล',r=ingestLoot(state(),[{title:'Basket',evidence,items:[{...apple(),quantity:2},{id:'sword',name:'ดาบเหล็ก',quantity:1}]}],{story:evidence+' เขาถือดาบเหล็กอยู่',source});
 assert.equal(r.added[0].entries.length,1);assert.equal(r.added[0].entries[0].item.name,'Red Apple');assert.ok(r.errors.includes('loot-item'));
});
