import test from 'node:test';
import assert from 'node:assert/strict';
import {lootOpportunity,prepareLootPayload,resolveReplyLoot,acquiredItemNames} from '../src/loot-discovery.js';
import {ingestLoot,normalizeItemSystem,prepareItemAction,validateItemResponse,applyItemDecision} from '../src/item-core.js';
const state=()=>({location:{place:'Forest'},worldClock:{day:1,time:'10:00'},player:{hp:{current:100,max:100}},inventory:[],itemSystem:normalizeItemSystem(),commerce:{sessions:[]}});
const source={messageId:1,turnKey:'t1',variant:'v1'};
for(const [story,kind]of [['สังหารก็อบลินลาดตระเวน 4 ตน','combat'],['You defeated the goblin.','combat'],['พิชิตดันเจี้ยนสำเร็จ','dungeon'],['You completed the dungeon.','dungeon'],['เปิดหีบไม้เก่า','container'],['You open the chest.','container'],['เดินไปที่ชั้นหนังสือแล้วค้นดู','search'],['You examine the bookshelf.','search'],['ตรวจดูศพที่ริมทาง','combat'],['ขุดแร่ในเหมือง','gathering'],['ตกปลาที่บึง','gathering'],['You harvest herbs.','gathering']])test(`Loot opportunity covers ${story}`,()=>assert.equal(lootOpportunity(`<tr-narrative>${story}</tr-narrative>`,'ฉันสำรวจ').kind,kind));
for(const story of ['เดินไปตามถนน','You attack the goblin; the fight continues.','พรุ่งนี้จะเปิดหีบ','ยังไม่ได้เปิดหีบ','เปิดหีบไม่ได้','The chest is locked; you did not open it.','ถ้าเปิดหีบจะได้อะไร','ฉันจะฆ่าก็อบลิน','ล้มตัวนอนพัก','ฉันเกือบตายจากบาดแผล','ก็อบลินไม่ตาย','เมื่อวานฉันฆ่าก็อบลิน','The goblin is not dead.','You almost died.','You plan to inspect the bookshelf.'])test(`no Loot from unconfirmed scenario: ${story}`,()=>assert.equal(lootOpportunity(story,'ลองดู'),null));
test('OOC requests never discover new goods',()=>assert.equal(lootOpportunity('You killed the goblin.','OOC: explain loot'),null));
test('completed combat evidence may anchor AI-designed rewards without forcing their names into an earlier quote',()=>{const story='สังหารก็อบลินลาดตระเวน 4 ตน',raw={id:'goblins',sourceId:'forest-goblins-1',kind:'combat',title:'สัมภาระก็อบลิน',evidence:story,items:[{id:'proof',name:'เหรียญตราก็อบลิน',category:'Quest',quantity:4},{id:'water',name:'น้ำเปล่า',category:'Drink',quantity:2}]},r=ingestLoot(state(),[raw],{story,source});assert.deepEqual(r.errors,[]);assert.equal(r.added[0].entries.length,2);assert.equal(r.next.inventory.length,0);for(const e of r.added[0].entries){assert.ok(e.item.description);assert.ok(e.item.usage.effect);assert.ok(Array.isArray(e.item.usage.stats));}});
test('integer strings normalize, but null/unknown quantities remain invalid instead of becoming zero or one',()=>{const story='เปิดหีบไม้',input=prepareLootPayload([{title:'หีบ',evidence:story,kind:'container',items:[{name:'น้ำเปล่า',quantity:'2'},{name:'ของลึกลับ',quantity:null}]}],{story});const r=ingestLoot(state(),input,{story,source});assert.equal(r.added[0].entries[0].remaining,2);assert.equal(r.added[0].entries.length,1);assert.ok(r.errors.includes('loot-item'));});
test('a stable exhausted physical source cannot refill on a later turn or revisit',()=>{const s=state(),story='เปิดหีบไม้',raw={sourceId:'old-chest',title:'หีบ',kind:'container',evidence:story,items:[{name:'น้ำเปล่า',category:'Drink',quantity:2}]},r=ingestLoot(s,[raw],{story,source}),pool=r.added[0];const prepared=prepareItemAction(r.next,{action:'collect',poolId:pool.id,revision:0,entries:[{id:pool.entries[0].id,quantity:2}]},{requestId:'pick',turn:1});assert.equal(prepared.ok,true);const evidence='เก็บ น้ำเปล่า เรียบร้อย',picked=applyItemDecision(r.next,prepared.request,validateItemResponse({narrative:`<tr-narrative>${evidence}</tr-narrative>`,itemAction:{requestId:'pick',outcome:'success',reason:'picked',evidence}},prepared.request));assert.equal(picked.ok,true);const again=ingestLoot(picked.next,[raw],{story,source:{...source,turnKey:'t2'}});assert.equal(again.added.length,0);assert.equal(again.next.itemSystem.loot[0].entries[0].remaining,0);assert.equal(again.next.inventory[0].quantity,2);});
test('missing combat payload is recovered once with complete properties, without collecting or changing stats',async()=>{const s=state(),story='สังหารก็อบลินลาดตระเวน 4 ตน';let calls=0;const context={generateRaw:async()=>{calls++;return JSON.stringify({loot:[{sourceId:'g4',title:'Goblin remains',evidence:story,items:[{name:'เหรียญตราก็อบลิน',quantity:4}]}]});}},args={state:s,story,user:'ฉันจัดการก็อบลิน',source,location:'Forest',context,parse:JSON.parse};const r=await resolveReplyLoot(args);assert.equal(r.recovered,true);assert.equal(r.checked,true);assert.equal(calls,1);const next=ingestLoot(s,r.payload,{story,source}).next;next.itemSystem.checks.push(r.check);const again=await resolveReplyLoot({...args,state:next});assert.equal(again.recovered,false);assert.equal(calls,1);assert.equal(next.inventory.length,0);assert.equal(next.player.hp.current,100);});
test('an empty shelf is persisted as a completed check, rather than causing an API retry loop',async()=>{const s=state(),story='เดินไปที่ชั้นหนังสือแล้วค้นดู';let calls=0;const args={state:s,story,user:'ฉันตรวจชั้นหนังสือ',source,location:'Forest',context:{generateRaw:async()=>{calls++;return{loot:[],emptyReason:'ชั้นว่าง ไม่มีของที่เก็บได้'};}},parse:JSON.parse};const r=await resolveReplyLoot(args);assert.equal(r.check.outcome,'empty');s.itemSystem.checks.push(r.check);await resolveReplyLoot(args);assert.equal(calls,1);});
test('valid same-reply Loot needs no recovery API; invalid recovery and stale results never grant anything',async()=>{const s=state(),story='เปิดหีบไม้',raw=[{title:'หีบ',kind:'container',evidence:story,items:[{name:'น้ำเปล่า',quantity:2}]}];let calls=0;const args={state:s,raw,story,user:'เปิดหีบ',source,location:'Forest',context:{generateRaw:async()=>{calls++;return{loot:[]};}},parse:JSON.parse};assert.equal((await resolveReplyLoot(args)).recovered,false);assert.equal(calls,0);const bad=await resolveReplyLoot({...args,raw:[]});assert.equal(bad.error,'response');const stale=await resolveReplyLoot({...args,raw:[],stable:()=>false});assert.equal(stale.error,'stale');assert.equal(s.itemSystem.loot.length,0);});

test('already received quest/purchase goods cannot be duplicated as uncollected Loot',async()=>{const s=state(),story='สังหารก็อบลินและได้รับ เหรียญตราก็อบลิน เป็นรางวัล',raw=[{title:'Goblin remains',kind:'combat',evidence:story,items:[{name:'เหรียญตราก็อบลิน',quantity:4},{name:'ดาบเหล็ก',quantity:1}]}];const r=await resolveReplyLoot({state:s,raw,story,user:'ฉันฆ่าก็อบลิน',source,location:'Forest',acquired:['เหรียญตราก็อบลิน'],context:{generateRaw:async()=>assert.fail('valid remaining goods need no API')},parse:JSON.parse});assert.deepEqual(r.payload[0].items.map(i=>i.name),['ดาบเหล็ก']);});
test('completed source evidence remains valid when rewards have not been collected yet',()=>{const story='สังหารก็อบลินสำเร็จ ยังไม่ได้เก็บสัมภาระ',r=ingestLoot(state(),[{kind:'combat',title:'สัมภาระ',evidence:story,items:[{name:'เหรียญตราก็อบลิน',quantity:4}]}],{story,source});assert.deepEqual(r.errors,[]);assert.equal(r.added.length,1);});

test('confirmed ordinary pickup is owned, while discovery and not-yet-collected goods remain Loot',()=>{const ops=[['inc','inventory',{name:'น้ำเปล่า',quantity:1}]];assert.deepEqual(acquiredItemNames(ops,'ได้รับ น้ำเปล่า และเก็บใส่กระเป๋า'),['น้ำเปล่า']);assert.deepEqual(acquiredItemNames(ops,'พบ น้ำเปล่า ยังไม่ได้รับหรือเก็บใส่กระเป๋า'),[]);assert.deepEqual(acquiredItemNames(ops,'พบ น้ำเปล่า'),[]);});
