// Production loader, ordinary reply events, saved settings and actual Main Chat DOM.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? `${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright` : 'playwright');
const root=new URL('../',import.meta.url), base='/scripts/extensions/third-party/rpg-systems/';
const server=http.createServer(async(req,res)=>{
 try{const url=new URL(req.url,'http://localhost');
  if(url.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');res.end('[]');return;}
  if(!url.pathname.startsWith(base)||url.pathname.includes('..')){res.writeHead(404).end();return;}
  const path=url.pathname.slice(base.length),body=await readFile(new URL(path,root));
  res.setHeader('content-type',path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.json')?'application/json':path.endsWith('.js')?'text/javascript':'image/webp');res.end(body);
 }catch{res.writeHead(404).end();}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}${base}docs/previews/preview-h-stats.html?lang=th`;
async function captureCard(card,path){
 const style=await card.page().addStyleTag({content:'#send_form,#tretaresia-event-stack,#tretaresia-activity-island{display:none!important}'});
 try{await card.screenshot({path});}finally{await style.evaluate(el=>el.remove());}
}
async function receive(page,user,story,patch){
 await page.evaluate(async user=>{
  window.host.chat.push({is_user:true,name:'Player',mes:user});
  await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_SENT,window.host.chat.length-1);
  await window.host.eventSource.emit(window.host.eventTypes.GENERATION_STARTED,'normal',{},false);
  await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');window.lastNormalPrompt=[...window.prompts.values()].join('\n');window.lastGenerationInjections=structuredClone(window.promptInjections);window.normalCalls=(window.normalCalls||0)+1;
 },user);
 if(user.startsWith('หลังจากจบการประมูล'))assert.equal(await page.locator('.rf-commerce-composer').count(),0,'collection must not reopen a composer during generation');
 if(user==='ขอดูสินค้าประมูล'){await page.locator('.rf-commerce-pending-title').waitFor();assert.equal(await page.locator('.rf-commerce-composer').getAttribute('data-kind'),'auction');assert.equal(await page.locator('.rf-commerce-composer button').count(),0);if(page.viewportSize().width===390&&process.env.COMMERCE_ARTIFACT_DIR){await mkdir(process.env.COMMERCE_ARTIFACT_DIR,{recursive:true});await page.locator(".rf-commerce-composer").screenshot({path:`${process.env.COMMERCE_ARTIFACT_DIR}/auction-waiting-390.png`});}}
 const id=await page.evaluate(({story,patch})=>{
  const id=window.host.chat.length,mes=story+(patch?`\n<!--tretaresia_patch:${JSON.stringify(patch)}-->`:'');
  window.host.chat.push({is_user:false,name:'Narrator',mes,swipe_id:0,swipes:[mes]});
  document.querySelector('#chat').replaceChildren(...window.host.chat.map((message,index)=>{
   const row=document.createElement('div');row.className='mes';row.setAttribute('mesid',index);
   const text=document.createElement('div');text.className='mes_text';text.textContent=message.mes.replace(/<!--tretaresia_patch:[\s\S]*?-->/gu,'');row.append(text);return row;
  })); return id;
 },{story,patch});
 await page.evaluate(async id=>{await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,id,'normal');await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);},id);
 await page.waitForFunction(id=>Object.keys(window.host.chatMetadata.tretaresia_rpg_scene_history||{}).some(key=>key.startsWith(`${id}:`)),id);
 await page.waitForTimeout(200);return page.locator(`#chat .mes[mesid="${id}"]`);
}

let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const width of [320,390,1280]){
  const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('console',msg=>{if(msg.type()==='error'||msg.type()==='warning')console.log(msg.type(),msg.text());});page.on('pageerror',error=>errors.push(error.message));
  await page.route('https://fonts.googleapis.com/**',route=>route.fulfill({contentType:'text/css',body:''}));
  await page.addInitScript(()=>{
   localStorage.setItem('roleforge-hstats-preview-settings',JSON.stringify({tretaresia_rpg:{language:'th',autoTrack:true,autoContinuity:false,showSceneTracker:true,eventNotifications:false,enableMarketplace:true,enableAuctions:true,enableMissionBoard:true,enableGroupBoard:true,enableStoryMemory:true,enableStoryAgenda:true,enableQuestObjectives:true,enableMemorySummaries:true,memoryAutoSummary:false}}));
   localStorage.setItem('roleforge-hstats-preview-metadata',JSON.stringify({tretaresia_rpg_state:{player:{name:'Player'},npcs:[],quests:[],inventory:[],location:{narrativeVersion:1,place:'Guild'},onboarding:{locationSeeded:true},progression:{currency:{silver:10,gold:50}}}}));
  });
  await page.goto(url);await page.waitForFunction(()=>window.hStatsPreview?.ready);
  await page.evaluate(()=>{
   document.querySelector('#tretaresia-rpg-close').click();document.querySelector('.preview-host').style.display='none';document.querySelector('#chat').style.cssText='display:block;padding:12px 12px 240px;box-sizing:border-box';
   window.host.extensionSettings.tretaresia_rpg.chatPresentation=true;
   const style=document.createElement('style');style.textContent='#send_form{position:fixed;bottom:0;left:0;width:100%;padding:10px;background:#191816;box-sizing:border-box}#send_textarea{display:block;box-sizing:border-box;width:100%;height:60px;font:inherit;background:#191816;color:#eee;border:1px solid #53462e;border-radius:12px;padding:10px}#send_but{background:#d8c28c;color:#262016;border:0;border-radius:8px;padding:8px 14px;margin-top:5px}';document.head.append(style);
   const form=document.createElement('form');form.id='send_form';form.append(document.querySelector('#send_textarea'));const send=document.createElement('button');send.id='send_but';send.type='button';send.textContent='Send';form.append(send);document.body.append(form);
   window.calls=0;window.responses=[];window.legacyCommerceCalls=0;
   window.host.generateQuietPrompt=async()=>{window.legacyCommerceCalls++;return '<tr-dialogue name="พ่อค้าผ้าคลุมดำ">ห้าเหรียญเงิน</tr-dialogue>';};
   window.host.generateRaw=async args=>{window.calls++;window.lastCommercePrompt=args.prompt;window.lastTaskSystem=args.systemPrompt;const reply=window.responses.shift();if(reply===undefined)throw Error('Unexpected request');if(window.deferQuiet){window.deferQuiet=false;await new Promise(resolve=>{window.releaseQuiet=resolve;});}return typeof reply==='string'?reply:JSON.stringify(reply);};
   // Match SillyTavern's display override precedence when rerendering a reply.
   window.host.updateMessageBlock=(id,message)=>{document.querySelector(`#chat .mes[mesid="${id}"] .mes_text`).textContent=message.extra?.display_text??message.mes;};
   window.prompts=new Map();window.promptInjections={};window.host.setExtensionPrompt=(key,value,position,depth,scan,role)=>{window.prompts.set(key,value);window.promptInjections[key]={value,position,depth,scan,role};};
  });
  const bar=page.locator('.rf-commerce-composer');
  const action=async(name,decision,narrative='NPC considers your terms carefully.')=>{
   const before=await page.evaluate(()=>window.calls);await page.evaluate(reply=>window.responses.push(reply),{narrative,decision});
   await bar.locator(`[data-commerce-action="${name}"]`).click();await page.waitForFunction(()=>!document.querySelector('.rf-commerce-composer[aria-busy="true"]'));
   assert.equal(await page.evaluate(()=>window.calls),before+1);assert.equal(await bar.locator('[role="alert"]').count(),0);
  };
  const beforeRegular=await page.evaluate(()=>window.calls);
  const liveSession=()=>page.evaluate(async()=>{await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');const prompt=window.prompts.get('tretaresia_rpg_response_contract');return JSON.parse(prompt.split('REFERENCE DATA:\n').at(-1).split('\n')[0]).interaction;});
  const closeInChat=async(user,narrative,action,decision,amount)=>{const s=await liveSession();return receive(page,user,narrative,{commerce:{sessionId:s.id,revision:s.revision,evidence:user,action,decision,amount},ops:[]});};
  const regularBuy=await receive(page,'ขอซื้อ Potion','<tr-dialogue name="Rally">Potion สามเหรียญเงิน</tr-dialogue>',{sceneTracker:{loc:'Guild'},marketplace:{kind:'npcShop',id:'normal-buy',seller:{name:'Rally'},evidence:'Potion สามเหรียญเงิน',denomination:'silver',items:[{name:'Potion',price:3}]},ops:[]});
  await bar.locator('[data-commerce-action="confirm"]').waitFor();assert.equal(await page.evaluate(()=>window.calls),beforeRegular);assert.equal(await bar.getAttribute('data-kind'),'buy');assert.doesNotMatch(await regularBuy.innerText(),/(?:^|\n)null(?:\n|$)/u);
  if(process.env.PROMPT_ARTIFACT_DIR){await mkdir(process.env.PROMPT_ARTIFACT_DIR,{recursive:true});const capture=await page.evaluate(()=>({chat:window.host.chat.slice(0,-1).map(m=>({role:m.is_user?'user':'assistant',content:m.mes})),injections:window.lastGenerationInjections}));await (await import('node:fs/promises')).writeFile(`${process.env.PROMPT_ARTIFACT_DIR}/buy-${width}.json`,JSON.stringify(capture,null,2));}
  await closeInChat('ตกลง ซื้อราคา 3 เหรียญเงิน','Rally accepts three silver and hands you the potion.','confirm',{outcome:'accept',amount:3},3);assert.equal(await bar.count(),0);
  await receive(page,'ขาย Potion ให้ Mira','<tr-dialogue name="Mira">ข้ารับซื้อ Potion สามเหรียญเงิน</tr-dialogue>',{sceneTracker:{loc:'Guild'},marketplace:{kind:'npcPurchase',id:'normal-sell',buyer:{name:'Mira',budget:8},item:{itemName:'Potion',quantity:1},askPrice:3,denomination:'silver'},ops:[]});await bar.locator('[data-commerce-action="confirm"]').waitFor();assert.equal(await bar.getAttribute('data-kind'),'sell');assert.equal(await page.evaluate(()=>window.calls),beforeRegular);
  await closeInChat('ตกลง ขายราคา 3 เหรียญเงิน','Mira pays three silver and receives the potion.','confirm',{outcome:'accept',amount:3},3);assert.equal(await bar.count(),0);
  const normalAuctionPatch={sceneTracker:{loc:'Guild'},auction:{id:'normal-auction',location:'Guild',evidence:'สิบเหรียญเงิน!',denomination:'silver',lots:[{id:'shield',name:'Shield',openingBid:5,minIncrement:1,bidders:[{name:'Mira',budget:18}],currentBid:10,currentBidder:'Mira'}]},ops:[]};
  const regularAuction=await receive(page,'นั่งลงเข้าร่วมการประมูล','<tr-dialogue name="Mira">สิบเหรียญเงิน!</tr-dialogue>',normalAuctionPatch);await bar.locator('[data-commerce-action="bid"]').waitFor();assert.equal(await bar.getAttribute('data-kind'),'auction');assert.equal(await bar.locator('.rf-commerce-amount').inputValue(),'11');assert.equal(await page.evaluate(()=>window.calls),beforeRegular);
  if(process.env.COMPACT_ARTIFACT_DIR){await mkdir(process.env.COMPACT_ARTIFACT_DIR,{recursive:true});await bar.locator('.rf-commerce-unit').selectOption('gold');await bar.locator('.rf-commerce-amount').fill('1');await bar.screenshot({path:`${process.env.COMPACT_ARTIFACT_DIR}/auction-ready-${width}.png`});await bar.locator('.rf-commerce-unit').selectOption('silver');await bar.locator('.rf-commerce-amount').fill('11');}
  const output=await page.evaluate(()=>window.lastGenerationInjections.tretaresia_rpg_response_contract);assert.equal(output.position,1);assert.equal(output.depth,0);assert.equal(output.role,0);assert.match(output.value,/"auction":/);assert.match(output.value,/MEMORY SUMMARIES:/);assert.match(output.value,/NPC DOSSIER/);
  if(process.env.PROMPT_ARTIFACT_DIR){const capture=await page.evaluate(()=>({chat:window.host.chat.slice(0,-1).map(m=>({role:m.is_user?'user':'assistant',content:m.mes})),injections:window.lastGenerationInjections}));await (await import('node:fs/promises')).writeFile(`${process.env.PROMPT_ARTIFACT_DIR}/auction-${width}.json`,JSON.stringify(capture,null,2));}
  const originalAuction=await page.evaluate(()=>({id:window.host.chat.length-1,text:window.host.chat.at(-1).mes}));
  for(const type of ['regenerate','swipe']){
   await page.evaluate(async type=>{await window.host.eventSource.emit(window.host.eventTypes.GENERATION_STARTED,type,{},false);await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat.slice(0,-1)),100000,()=>{},type);window.replacementOutput=window.prompts.get('tretaresia_rpg_response_contract');window.lastGenerationInjections=structuredClone(window.promptInjections);},type);
   const replacement=await page.evaluate(()=>window.replacementOutput);assert.match(replacement,/"auction":/);assert.doesNotMatch(replacement,/CURRENT INTERACTION:/);
   if(process.env.PROMPT_ARTIFACT_DIR){const capture=await page.evaluate(()=>({chat:window.host.chat.slice(0,-1).map(m=>({role:m.is_user?'user':'assistant',content:m.mes})),injections:window.lastGenerationInjections}));await (await import('node:fs/promises')).writeFile(`${process.env.PROMPT_ARTIFACT_DIR}/${type}-${width}.json`,JSON.stringify(capture,null,2));}
   await page.evaluate(async patch=>{const id=window.host.chat.length-1,m=window.host.chat[id];m.swipe_id=(m.swipe_id||0)+1;patch.auction.evidence='สิบเอ็ดเหรียญเงิน!';patch.auction.lots[0].currentBid=11;const mes='<tr-dialogue name="Mira">สิบเอ็ดเหรียญเงิน!</tr-dialogue><!--tretaresia_patch:'+JSON.stringify(patch)+'-->';m.mes=mes;m.swipes[m.swipe_id]=mes;window.host.updateMessageBlock(id,m);await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,id,'normal');await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);},normalAuctionPatch);
   await page.waitForFunction(()=>document.querySelector('.rf-commerce-amount')?.value==='12');assert.equal(await page.evaluate(()=>window.calls),beforeRegular);
  }
  await page.evaluate(async original=>{const m=window.host.chat[original.id];m.swipe_id=0;m.mes=m.swipes[0];window.host.updateMessageBlock(original.id,m);await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_SWIPED,original.id);},originalAuction);await page.waitForFunction(()=>document.querySelector('.rf-commerce-amount')?.value==='11');
  await closeInChat('ออกประมูล','Mira keeps the current bid while you leave.','leave',{outcome:'left'});assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.calls),beforeRegular);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),10);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.length),0);
  const recovered=await receive(page,'ขอดูสินค้าที่ขาย','<tr-header name="Rally"></tr-header><tr-narrative>Rally shows goods for sale in the shop.\n- Potion: 2 silver\n- Antidote: 4 silver</tr-narrative>');
  await bar.waitFor({state:'visible'});assert.equal(await recovered.locator('.trpg-marketplace-event,.trpg-auction').count(),0);
  const original=await page.evaluate(()=>({text:window.host.chat.at(-1).mes,len:window.host.chat.length,user:window.host.chat.at(-2).mes}));
  await bar.locator('.rf-commerce-summary').click();await bar.locator('.rf-commerce-summary').click();assert.equal(await page.evaluate(()=>window.calls),0);
  await action('confirm',{outcome:'accept',amount:2},'<tr-dialogue name="Rally">ตกลง ข้ารับสองเหรียญเงิน นี่โพชั่นของเจ้า</tr-dialogue>');
  assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),8);
  assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory[0].quantity),1);
  assert.equal(await page.evaluate(()=>window.host.chat.length),original.len);assert.equal(await page.evaluate(()=>window.host.chat.at(-2).mes),original.user);assert.ok((await page.evaluate(()=>window.host.chat.at(-1).mes)).startsWith(original.text));
  await recovered.getByText('ตกลง ข้ารับสองเหรียญเงิน นี่โพชั่นของเจ้า',{exact:false}).waitFor();
  const sale=await receive(page,'ฉันเสนอขาย Potion ให้ Mira','<tr-header name="Mira"></tr-header><tr-dialogue name="Mira">I offer to buy your Potion for 5 silver.</tr-dialogue>',{sceneTracker:{loc:'Guild'},marketplace:{kind:'npcPurchase',id:'sale',buyer:{name:'Mira',budget:7},item:{itemName:'Potion',quantity:1},askPrice:5,denomination:'silver'},ops:[]});
  await bar.locator('.rf-commerce-amount').fill('6');await action('offer',{outcome:'counter',amount:5});
  assert.equal(await bar.locator('.rf-commerce-amount').inputValue(),'5');assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory[0].quantity),1);
  await action('confirm',{outcome:'accept',amount:5});assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),13);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.length),0);
  const auction=await receive(page,'ขอดูสินค้าประมูล','The auctioneer displays the auction catalog.',{sceneTracker:{loc:'Guild'},auction:{id:'new-ai-auction',denomination:'gold',entryFee:0,deposit:2,lots:[{id:'blade',name:'Blade',openingBid:3,minIncrement:1,bidders:[{name:'Rally',budget:20},{name:'Mira',budget:8}]}]},ops:[]});
  await bar.waitFor({state:'visible'});assert.equal(await auction.locator('.trpg-system-status').count(),0);assert.equal(await bar.locator('[data-commerce-action="bid"]').isEnabled(),true);assert.equal(await bar.locator('[data-commerce-action="join"]').count(),0);if(width===390&&process.env.COMMERCE_ARTIFACT_DIR)await bar.screenshot({path:`${process.env.COMMERCE_ARTIFACT_DIR}/auction-direct-bid-390.png`});await bar.locator('.rf-commerce-summary').click();assert.match(await bar.innerText(),/20 ทอง/);
  // Prose-only replies from the old preset must stay unpaid and expose the
  // exact failed response on mobile, then recover with one new native task.
  await page.evaluate(()=>window.responses.push('<tr-dialogue name="พ่อค้าผ้าคลุมดำ">ห้าเหรียญเงิน</tr-dialogue>'));
  await bar.locator('.rf-commerce-amount').fill('4');await bar.locator('[data-commerce-action="bid"]').click();await page.waitForFunction(()=>!document.querySelector('.rf-commerce-composer[aria-busy="true"]'));
  assert.match(await bar.locator('[role="alert"]').innerText(),/ไม่มีผลตัดสิน/);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.gold),50);
  await bar.locator('.rf-commerce-diagnostics summary').click();const failure=JSON.parse(await bar.locator('.rf-commerce-diagnostic-report').inputValue());assert.equal(failure.action,'bid');assert.equal(failure.system,'auction');assert.equal(failure.generation,'native-task');assert.equal(failure.error,'response-decision');assert.match(failure.rawResponse,/ห้าเหรียญเงิน/);
  if(width===390&&process.env.COMMERCE_ARTIFACT_DIR)await bar.screenshot({path:`${process.env.COMMERCE_ARTIFACT_DIR}/auction-diagnostic-390.png`});
  await bar.locator('.rf-commerce-diagnostics summary').click();
  await bar.locator('.rf-commerce-amount').fill('4');await action('bid',{outcome:'open',npcActions:[{name:'Rally',choice:'raise',bid_amount:'20',motive:'This heirloom is worth all my savings'},{name:'Mira',choice:'withdrawn',rationale:'Beyond my means'}]},'<tr-dialogue name="Rally">ข้าจะลงทั้งยี่สิบเหรียญเพื่อดาบเล่มนี้</tr-dialogue>');
  assert.equal(await auction.locator('.trpg-system-status').count(),0);assert.match(await bar.innerText(),/Rally/);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.length),0);
  await page.evaluate(()=>window.responses.push('The auctioneer closes the bidding.\n<!--tretaresia_patch:'+JSON.stringify({commerce:{decision:{outcome:'sold',participants:[{name:'Rally',action:'bid',amount:'20'},{name:'Mira',action:'withdraw'}]}}})+'-->'));await bar.locator('[data-commerce-action="wait"]').click();await page.waitForFunction(()=>!document.querySelector('.rf-commerce-composer'));assert.equal(await auction.locator('.trpg-system-status').count(),0);assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.gold),50);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.commerce.sessions.at(-1).participants[0].spent),20);
  // Real normal generation events use the user's role-play and one main reply,
  // followed by a button continuation anchored to that latest NPC reply.
  const quietBefore=await page.evaluate(()=>window.calls);
  const roleCatalog=await receive(page,'ขอดูสินค้าในร้านใหม่','Rally shows goods for sale. Potion: 3 silver.',{marketplace:{kind:'npcShop',id:'role-shop',seller:{name:'Rally'},denomination:'silver',items:[{name:'Potion',price:3}]},ops:[]});
  const openingText=await page.evaluate(()=>window.host.chat.at(-1).mes);
  const role=async(user,story,action,decision,amount)=>{
   // A catalog is persisted only once the first action occurs. Use the prompt's
   // interaction reference for an untouched opening session.
   const contract=await page.evaluate(async()=>{await window.TretaresiaRpgGenerateInterceptor();return [...window.prompts.values()].join('\n');});
   assert.match(contract,/NORMAL CHAT COMMERCE/);
   const reference=JSON.parse(contract.split('REFERENCE DATA:\n').at(-1).split('\n')[0]);
   const current=reference.interaction;
   return receive(page,user,story,{commerce:{sessionId:current.id,revision:current.revision,evidence:user,action,decision,amount},ops:[]});
  };
  const roleOffer=await role('ผมเสนอ 2 เหรียญเงิน','<tr-dialogue name="Rally">ตกลง สองเหรียญเงิน แต่ข้ารอเจ้ายืนยันก่อน</tr-dialogue>','offer',{outcome:'accept',amount:2},2);
  assert.equal(await page.evaluate(()=>window.calls),quietBefore);assert.equal(await bar.locator('.rf-commerce-amount').inputValue(),'2');assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),13);
  if(width===390&&process.env.ROLEPLAY_ARTIFACT_DIR){await mkdir(process.env.ROLEPLAY_ARTIFACT_DIR,{recursive:true});await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await page.screenshot({path:`${process.env.ROLEPLAY_ARTIFACT_DIR}/offer-390.png`});}
  const roleId=await roleOffer.getAttribute('mesid');await action('confirm',{outcome:'accept',amount:2},'<tr-dialogue name="Rally">นี่โพชั่นของเจ้า</tr-dialogue>');assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),11);assert.match(await roleOffer.innerText(),/นี่โพชั่นของเจ้า/);assert.equal(await page.evaluate(id=>window.host.chat[Number(id)-2].mes,roleId),openingText);
  await receive(page,'เสนอขาย Potion ให้ Mira','Mira offers to buy your Potion for 5 silver.',{marketplace:{kind:'npcPurchase',id:'role-sale',buyer:{name:'Mira',budget:7},item:{itemName:'Potion',quantity:1},askPrice:5,denomination:'silver'},ops:[]});
  const beforeRoleConfirm=await page.evaluate(()=>window.calls);
  await role('ตกลง ขายให้ราคา 5 เหรียญเงิน','Mira pays five silver and takes the potion.','confirm',{outcome:'accept',amount:5},5);assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.calls),beforeRoleConfirm);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),16);
  await receive(page,'ขอดูประมูลครั้งใหม่','The auctioneer displays the auction catalog.',{auction:{id:'role-auction',denomination:'gold',entryFee:1,deposit:2,lots:[{id:'shield',name:'Shield',openingBid:3,minIncrement:1,bidders:[{name:'Rally',budget:20}]}]},ops:[]});
  // Offered auction: the opening catalog has no saved canonical session yet.
  const prompt=await page.evaluate(async()=>{await window.TretaresiaRpgGenerateInterceptor();return [...window.prompts.values()].join('\n');});
  const referenceText=prompt.split('REFERENCE DATA:\n').at(-1);const payload=JSON.parse(referenceText.slice(0,referenceText.indexOf('\n')));
  const rival=payload.interaction.participants[0].id;
  await role('ผมยกป้ายบิด 4 เหรียญทอง','The auctioneer awards you the shield at four gold.','bid',{outcome:'sold',participants:[{id:rival,action:'withdraw',reason:'Saving my funds for a sword'}]},4);
  assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.calls),beforeRoleConfirm);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.gold),45);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.some(i=>i.name==='Shield')),true);
  const afterSale=await page.evaluate(()=>({calls:window.calls,normal:window.normalCalls,wallet:window.host.chatMetadata.tretaresia_rpg_state.progression.currency,inventory:window.host.chatMetadata.tretaresia_rpg_state.inventory}));
  const collection=await receive(page,'หลังจากจบการประมูลฉันก็ไปรับของมาก่อนจะทำความรู้จัก\nฉันยืนมองโล่ที่ตัวเองซื้อมาก่อนจะคิดต่อว่าเอาไงดี','เจ้าหน้าที่นำโล่ที่ชำระเงินแล้วมาส่งมอบ พร้อมยื่นเอกสารให้ตรวจสอบ',{sceneTracker:{loc:'Guild'},ops:[]});
  assert.equal(await bar.count(),0);assert.equal(await collection.locator('.trpg-system-status').count(),0);
  const afterCollection=await page.evaluate(()=>({calls:window.calls,normal:window.normalCalls,wallet:window.host.chatMetadata.tretaresia_rpg_state.progression.currency,inventory:window.host.chatMetadata.tretaresia_rpg_state.inventory}));
  assert.deepEqual(afterCollection,{...afterSale,normal:afterSale.normal+1});
  assert.doesNotMatch(await page.evaluate(()=>window.lastNormalPrompt),/"id":"unique-current-auction-id"/);assert.match(await page.evaluate(()=>window.lastNormalPrompt),/AFTER SETTLEMENT/);
  await page.evaluate(()=>{document.querySelector('#preview-open').click();document.querySelector('[data-tab="rank"]').click();});
  const rank=page.locator('[data-panel="rank"]');await rank.waitFor({state:'visible'});
  assert.equal(await rank.locator('.trpg-auction-wallet').count(),0);assert.doesNotMatch(await rank.innerText(),/ใช้แถบเหนือช่องพิมพ์|Continue auctions from| · completed/);
  if(width===390&&process.env.BOARD_ARTIFACT_DIR){await mkdir(process.env.BOARD_ARTIFACT_DIR,{recursive:true});await captureCard(rank,`${process.env.BOARD_ARTIFACT_DIR}/rank-clean-390.png`);}
  await page.evaluate(()=>document.querySelector('#tretaresia-rpg-close').click());
  await receive(page,'ขอดูร้านสุดท้าย','Rally shows shop goods for sale. Potion: 1 silver.',{marketplace:{kind:'npcShop',id:'race-shop',seller:{name:'Rally'},denomination:'silver',items:[{name:'Potion',price:1}]},ops:[]});
  const contract=await page.evaluate(async()=>{await window.TretaresiaRpgGenerateInterceptor();return [...window.prompts.values()].join('\n');});const raceSession=JSON.parse(contract.split('REFERENCE DATA:\n').at(-1).split('\n')[0]).interaction;
  await page.evaluate(()=>{window.deferQuiet=true;window.responses.push({narrative:'Rally receives your silver.',decision:{outcome:'accept',amount:1}});});
  await bar.locator('[data-commerce-action="confirm"]').click();await page.waitForFunction(()=>typeof window.releaseQuiet==='function');
  const cancelUser='ไม่ซื้อแล้ว ยกเลิก',cancellation=receive(page,cancelUser,'Rally puts the potion back.',{commerce:{sessionId:raceSession.id,revision:raceSession.revision,evidence:cancelUser,action:'cancel',decision:{outcome:'cancel'}},ops:[]});
  await page.waitForFunction(()=>window.host.chat.at(-1).mes.includes('Rally puts the potion back.'));
  assert.match(await page.evaluate(()=>window.lastNormalPrompt),/NORMAL CHAT COMMERCE/);
  await page.evaluate(()=>{window.releaseQuiet();delete window.releaseQuiet;});await cancellation;
  assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),16);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.commerce.sessions.at(-1).status),'cancelled');
  const boards=await receive(page,'ขออ่านกระดานภารกิจและกระดานกิลด์','You read the mission board. You browse the guild board.',{sceneTracker:{loc:'Guild'},missionBoard:{missions:[{name:'Delivery',objective:'Deliver the letter',reward:'3 silver'}]},groupBoard:{entries:[{kind:'guild',name:'Dawn'}]},ops:[['upsert','storyMemories',{id:'promise',title:'Return a book',kind:'Promise',detail:'Promised to return the book'}],['upsert','storyAgenda',{id:'meeting',title:'Meet Rally',dueDay:2}],['upsert','quests',{id:'job',name:'Errand',objectives:[{id:'step',title:'Bring the book'}]}]]});
  await boards.locator('.trpg-mission-board').waitFor();await boards.locator('.trpg-group-board').waitFor();await boards.locator('.trpg-story-events').waitFor();await boards.locator('.trpg-story-events>summary').click();assert.match(await boards.innerText(),/Return a book/);assert.match(await boards.innerText(),/Bring the book/);assert.match(await boards.innerText(),/Meet Rally/);
  const beforeBoards=await page.evaluate(()=>({calls:window.calls,normal:window.normalCalls,user:document.querySelector('#send_textarea').value,quests:window.host.chatMetadata.tretaresia_rpg_state.quests}));
  const thaiBoards=await receive(page,'ยืนดูกระดานภารกิจและกระดานปาร์ตี้และกิลด์','บนกระดานไม้มีใบประกาศรับสมัครสมาชิกปาร์ตี้ รูอิน สตาฟฟ์ ระบุเงื่อนไขและบทบาทที่ขาดแคลนไว้อย่างชัดเจน\nแผ่นประกาศภารกิจที่ติดอยู่ระดับสายตาระบุงานล่าหมาป่าเขี้ยวดาบและเงินรางวัล 5 เหรียญเงิน',{
   sceneTracker:{loc:'Guild'},ops:[],missionBoard:{title:'กระดานภารกิจสมาคม',missions:[{name:'ล่าหมาป่าเขี้ยวดาบ',objective:'กำจัดหมาป่าเขี้ยวดาบที่ขวางเส้นทาง',giver:'สมาคมนักผจญภัย',reward:'5 เหรียญเงิน'},...Array.from({length:3},(_,i)=>({name:['ส่งจดหมาย','คุ้มกันขบวนสินค้า','สำรวจเส้นทางป่า'][i],objective:['ส่งจดหมายถึงเจ้าหน้าที่หมู่บ้าน','นำขบวนสินค้าไปถึงจุดหมาย','บันทึกอุปสรรคบนเส้นทาง'][i],reward:['3 เหรียญเงิน','8 เหรียญเงิน','6 เหรียญเงิน'][i]}))]},
   groupBoard:{title:'กระดานปาร์ตี้และกิลด์',entries:[{kind:'party',name:'รูอิน สตาฟฟ์',description:'กลุ่มสำรวจซากโบราณสถาน เปิดรับสมาชิกแนวหน้า',leader:'เอซ',memberCount:3,maxMembers:5,requirements:['รับหน้าที่แนวหน้า'],notes:'แบ่งผลประโยชน์เท่ากันหลังหักค่าเสบียง'},...Array.from({length:6},(_,i)=>({kind:i%2?'party':'guild',name:['กิลด์แสงรุ่งอรุณ','หน่วยสำรวจเส้นทาง','กิลด์คุ้มกันพ่อค้า','กลุ่มนักล่าป่าเหนือ','กิลด์ผู้ใช้เวท','ปาร์ตี้แผนที่จันทร์'][i],description:'เปิดรับเพื่อนร่วมทางตามบทบาทที่ประกาศ',requirements:['ติดต่อหัวหน้าก่อนออกเดินทาง']}))]}
  });
  const missionCard=thaiBoards.locator('.trpg-mission-board'),groupCard=thaiBoards.locator('.trpg-group-board');await missionCard.waitFor();await groupCard.waitFor();assert.equal(await thaiBoards.locator('.trpg-system-status').count(),0);
  assert.match(await page.evaluate(()=>window.lastNormalPrompt),/REQUIRED THIS REPLY: missionBoard, groupBoard/);
  assert.equal(await groupCard.locator('.trpg-group-board-card').count(),3);await groupCard.locator('.trpg-group-board-pager button').last().click();assert.match(await groupCard.locator('.trpg-group-board-pager').innerText(),/หน้า 2 \/ 3/);await groupCard.locator('.trpg-group-board-pager button').first().click();
  await groupCard.locator('.trpg-group-board-inspect').first().click();assert.match(await groupCard.locator('.trpg-group-board-detail').innerText(),/แบ่งผลประโยชน์เท่ากัน/);await groupCard.locator('.trpg-group-board-actions button').first().click();
  assert.deepEqual(await page.evaluate(()=>({calls:window.calls,normal:window.normalCalls,user:document.querySelector('#send_textarea').value,quests:window.host.chatMetadata.tretaresia_rpg_state.quests})),{...beforeBoards,normal:beforeBoards.normal+1});
  if(width===390&&process.env.BOARD_ARTIFACT_DIR){await captureCard(missionCard,`${process.env.BOARD_ARTIFACT_DIR}/mission-board-390.png`);await captureCard(groupCard,`${process.env.BOARD_ARTIFACT_DIR}/party-guild-board-390.png`);}
  const incomplete=await receive(page,'ยืนอ่านกระดานภารกิจ','แผ่นประกาศภารกิจที่ติดอยู่ระดับสายตาระบุงานและเงินรางวัล',{sceneTracker:{loc:'Guild'},ops:[]});await incomplete.locator('.trpg-system-status').waitFor();assert.equal(await incomplete.locator('.trpg-system-status button').count(),0);assert.doesNotMatch(await incomplete.innerText(),/เตรียมข้อความขอดูรายการ/);
  // Exact failure pattern: an auctioneer quotes prices but the final reply
  // contains no patch, even if provider reasoning promises to emit one.
  const beforeOpening=await page.evaluate(()=>({calls:window.calls,wallet:JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.progression.currency),items:JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.inventory)}));
  await page.evaluate(()=>window.responses.push({auction:{location:'Guild',evidence:'Blade เริ่มต้นที่ 5 เหรียญเงิน',denomination:'silver',lots:[{id:'blade',name:'Blade',openingBid:5,minIncrement:1,bidders:[{name:'Fat Merchant',budget:18}],currentBid:6,currentBidder:'Fat Merchant'}]}}));
  const proseOnly='<tr-dialogue name="Auctioneer">Blade เริ่มต้นที่ 5 เหรียญเงิน</tr-dialogue><tr-dialogue name="Fat Merchant">6 เหรียญเงิน!</tr-dialogue>';
  const repaired=await receive(page,'เข้าร่วมประมูล',proseOnly);
  await bar.locator('[data-commerce-action="bid"]').waitFor();assert.equal(await bar.getAttribute('data-kind'),'auction');assert.equal(await bar.locator('.rf-commerce-amount').inputValue(),'7');assert.match(await bar.innerText(),/6 เงิน/);assert.match(await bar.innerText(),/Fat Merchant/);assert.equal(await page.evaluate(()=>window.calls),beforeOpening.calls+1);assert.match(await page.evaluate(()=>window.lastTaskSystem),/Recover ONE missing/);
  assert.equal(await page.evaluate(()=>window.host.chat.at(-1).mes),proseOnly);assert.equal(await page.evaluate(()=>JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.progression.currency)),beforeOpening.wallet);assert.equal(await page.evaluate(()=>JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.inventory)),beforeOpening.items);assert.doesNotMatch(await repaired.innerText(),/(?:^|\n)null(?:\n|$)/u);
  await bar.locator('.rf-commerce-summary').click();assert.match(await bar.innerText(),/18 เงิน/);
  if(width===390&&process.env.COMMERCE_ARTIFACT_DIR)await bar.screenshot({path:`${process.env.COMMERCE_ARTIFACT_DIR}/auction-auto-recovered-390.png`});
  await action('bid',{outcome:'open',participants:[{name:'Fat Merchant',action:'bid',amount:8,reason:'The blade fits my collection'}]},'<tr-dialogue name="Fat Merchant">Eight silver for my collection.</tr-dialogue>');assert.match(await bar.innerText(),/8 เงิน/);assert.equal(await bar.locator('.rf-commerce-amount').inputValue(),'9');
  await action('leave',{outcome:'left'},'The auctioneer allows you to leave after the merchant outbids you.');assert.equal(await bar.count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.progression.currency)),beforeOpening.wallet);
  const beforeFailure=await page.evaluate(()=>window.calls);await page.evaluate(()=>window.responses.push('The NPC only speaks; no structured data.'));
  await receive(page,'เข้าร่วมประมูล',proseOnly);await bar.locator('[role="alert"]').waitFor();assert.equal(await bar.getAttribute('data-kind'),'auction');assert.equal(await page.evaluate(()=>window.calls),beforeFailure+1);assert.equal(await bar.locator('[data-commerce-action]').count(),0);
  await bar.locator('.rf-commerce-diagnostics summary').click();const openingReport=JSON.parse(await bar.locator('.rf-commerce-diagnostic-report').inputValue());assert.equal(openingReport.channel,'opening');assert.equal(openingReport.error,'opening-data');assert.match(openingReport.rawResponse,/no structured data/);
  await page.evaluate(async()=>{await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,window.host.chat.length-1,'normal');});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.calls),beforeFailure+1);assert.equal(await bar.count(),1);
  await receive(page,'เข้าร่วมประมูล','<tr-dialogue name="Auctioneer">มาเริ่มกันที่ชิ้นแรกของวันนี้</tr-dialogue>');await bar.locator('.rf-commerce-pending-title').waitFor();assert.equal(await bar.count(),1);assert.equal(await page.evaluate(()=>window.calls),beforeFailure+1);
  await page.evaluate(()=>window.host.isGenerating=true);
  const missing=await receive(page,'ขอดูสินค้า','Rally แสดงสินค้าที่ขายในร้านให้ดู แต่ยังไม่ระบุราคา',{sceneTracker:{loc:'Guild'},ops:[]});await bar.locator('.rf-commerce-pending-title').waitFor();assert.equal(await missing.locator('.trpg-system-status').count(),0);assert.doesNotMatch(await missing.innerText(),/(?:^|\n)null(?:\n|$)/u);assert.equal(await bar.locator('button').count(),0);assert.doesNotMatch(await bar.innerText(),/รอ NPC/);assert.equal(await bar.getAttribute('aria-busy'),'false');await page.evaluate(()=>window.host.isGenerating=false);
  await page.evaluate(()=>window.TretaresiaRpgGenerateInterceptor());assert.match(await page.evaluate(()=>[...window.prompts.values()].join('\n')),/MAIN CHAT INTERACTION CHECK/);
  // The provider normalizes a quoted gold offer to silver, joins paragraphs,
  // and uses smart quotes. Validate the reported clause without another task.
  await receive(page,'เข้าร่วมประมูล','<tr-dialogue name="Mira">สิบเหรียญเงิน!</tr-dialogue>',{sceneTracker:{loc:'Guild'},auction:{id:'reported-evidence',location:'Guild',evidence:'สิบเหรียญเงิน!',denomination:'silver',lots:[{id:'evidence-lot',name:'Silver Compass',openingBid:5,minIncrement:1,bidders:[{name:'Mira',budget:18}],currentBid:10,currentBidder:'Mira'}]},ops:[]});
  const reportedSession=await liveSession(),reportedCalls=await page.evaluate(()=>({private:window.calls,normal:window.normalCalls}));
  await receive(page,'"1 เหรียญทอง"\n\nฉันชูป้ายก่อนจะเอ่ยขึ้นเบาๆแบบไม่แสดงใบหน้าเพราะเงามันทับช่วงหน้าผากไม่ให้เห็นดวงตา ฉันค่อยๆวางป้ายลงหลังจากเสนอราคา','<tr-dialogue name="Auctioneer">หนึ่งเหรียญทองจากด้านหลัง!</tr-dialogue>',{commerce:{sessionId:reportedSession.id,revision:reportedSession.revision,evidence:'“1 เหรียญทอง” ฉันชูป้ายก่อนจะเอ่ยขึ้นเบาๆ',action:'bid',amount:100,denomination:'silver',decision:{outcome:'open',participants:reportedSession.participants.map(p=>({id:p.id,action:'pass',reason:'The gold offer exceeds my funds'}))}},ops:[]});
  assert.equal(await bar.locator('.rf-commerce-error').count(),0);assert.match(await bar.locator('.rf-commerce-price').innerText(),/100 เงิน/);assert.equal((await liveSession()).revision,reportedSession.revision+2);assert.equal((await liveSession()).lots[0].leader,'player');assert.equal(await page.evaluate(()=>window.calls),reportedCalls.private);assert.equal(await page.evaluate(()=>window.normalCalls),reportedCalls.normal+1);await action('wait',{outcome:'sold',participants:(await liveSession()).participants.map(p=>({id:p.id,action:'withdraw',reason:'Cannot afford this price'}))});assert.equal(await bar.count(),0);
  for(const mode of ['roleforge','native','preserved']){
   if(mode==='roleforge')await page.addStyleTag({content:'button,input[type=number],select{min-height:44px!important}select{width:100%!important}'});
   await page.evaluate(mode=>{const s=window.host.extensionSettings.tretaresia_rpg;s.chatPresentation=mode!=='native';s.preserveNativeChat=mode==='preserved';},mode);
   const oldBubble=await receive(page,'ขอดูประมูลอีกรอบ','<tr-dialogue name="Mira">สิบเหรียญเงิน!</tr-dialogue>',{sceneTracker:{loc:'Guild'},auction:{id:`latest-anchor-${mode}`,location:'Guild',evidence:'สิบเหรียญเงิน!',denomination:'silver',lots:[{id:'anchor-lot',name:`Test Compass ${mode}`,openingBid:5,minIncrement:1,bidders:[{name:'Mira',budget:18}],currentBid:10,currentBidder:'Mira'}]},ops:[]});
   const s=await liveSession(),oldId=Number(await oldBubble.getAttribute('mesid')),oldText=await page.evaluate(id=>window.host.chat[id].mes,oldId);
   const user='"1 เหรียญทอง" ฉันชูป้าย',recent=await receive(page,user,'<tr-dialogue name="Auctioneer">ข้าเห็นป้ายจากด้านหลังแล้ว</tr-dialogue>',{commerce:{sessionId:s.id,revision:s.revision,action:'bid',amount:100,denomination:'silver',evidence:'2 เหรียญทอง',decision:{outcome:'open',participants:s.participants.map(p=>({id:p.id,action:'pass',reason:'Cannot afford it'}))}},ops:[]});
   assert.equal(await bar.locator('.rf-commerce-error').count(),1);
   const recentId=Number(await recent.getAttribute('mesid')),original=await page.evaluate(id=>{const m=window.host.chat[id];m.extra={display_text:'รูปแบบที่โฮสต์แสดงอยู่ก่อนกด Bid',custom:'preserved'};window.host.updateMessageBlock(id,m);return{text:m.mes,len:window.host.chat.length,calls:window.calls,wallet:JSON.stringify(window.host.chatMetadata.tretaresia_rpg_state.progression.currency)};},recentId);
   await bar.locator('.rf-commerce-unit').selectOption('gold');await bar.locator('.rf-commerce-amount').fill('1');
   assert.equal(await bar.locator('.rf-commerce-price-field .rf-commerce-amount').count(),1);assert.equal(await bar.locator('.rf-commerce-price-field .rf-commerce-unit').count(),1);
   assert.equal(await bar.locator('.rf-commerce-controls').evaluate(row=>{const field=row.querySelector('.rf-commerce-price-field'),buttons=[...row.querySelectorAll('button')],nodes=[field,...buttons];return row.getBoundingClientRect().width<=390&&buttons.every(button=>button.getBoundingClientRect().width<=96)&&nodes.every(node=>Math.abs(node.getBoundingClientRect().top-field.getBoundingClientRect().top)<1&&node.getBoundingClientRect().height===32);}),true,`A controls stay compact on one row at ${width}px`);
   const narrative=`<tr-dialogue name="Auctioneer">หนึ่งทองครั้งที่สาม ขายแล้ว รับเข็มทิศของเจ้าได้เลย ${mode}</tr-dialogue>`;
   await action('bid',{outcome:'sold',participants:s.participants.map(p=>({id:p.id,action:'withdraw',reason:'One gold is beyond my budget'}))},narrative);
   await page.waitForFunction(id=>document.querySelector(`#chat .mes[mesid="${id}"] .mes_text`)?.textContent.includes('ขายแล้ว รับเข็มทิศ'),recentId);
   const after=await page.evaluate(({oldId,recentId})=>({old:window.host.chat[oldId].mes,current:window.host.chat[recentId],user:window.host.chat[recentId-1].mes,len:window.host.chat.length,calls:window.calls,state:window.host.chatMetadata.tretaresia_rpg_state}),{oldId,recentId});
   assert.equal(after.old,oldText);assert.equal(after.current.mes,original.text+'\n\n'+narrative);assert.equal(after.current.swipes[after.current.swipe_id],after.current.mes);assert.equal(after.current.extra.display_text,'รูปแบบที่โฮสต์แสดงอยู่ก่อนกด Bid\n\n'+narrative);assert.equal(after.current.extra.custom,'preserved');assert.equal(after.user,user);assert.equal(after.len,original.len);assert.equal(after.calls,original.calls+1);assert.equal(after.state.inventory.filter(i=>i.name===`Test Compass ${mode}`)[0].quantity,1);assert.equal(await bar.count(),0);
   if(mode==='roleforge'&&process.env.COMPACT_ARTIFACT_DIR){await mkdir(process.env.COMPACT_ARTIFACT_DIR,{recursive:true});await recent.screenshot({path:`${process.env.COMPACT_ARTIFACT_DIR}/auction-continuation-${width}.png`});}
  }
  await page.evaluate(()=>{const s=window.host.extensionSettings.tretaresia_rpg;s.chatPresentation=true;s.preserveNativeChat=false;});
  const value=()=>page.evaluate(()=>{const c=window.host.chatMetadata.tretaresia_rpg_state.progression.currency;return c.gold*10000+c.silver*100+c.copper;});
  const beforeNew=await value();
  await receive(page,'เข้าร่วมประมูล','<tr-dialogue name="Mira">สิบเหรียญเงิน!</tr-dialogue>',{sceneTracker:{loc:'Guild'},auction:{id:'mixed-money',location:'Guild',evidence:'สิบเหรียญเงิน!',denomination:'silver',entryFee:1,deposit:2,lots:[{id:'mixed-lot',name:'Silver Compass',openingBid:5,minIncrement:1,bidders:[{name:'Mira',budget:18}],currentBid:10,currentBidder:'Mira'}]},ops:[]});
  await bar.locator('[data-commerce-action="bid"]').waitFor();assert.equal(await bar.locator('.rf-commerce-glyph svg').count(),1);assert.equal(await bar.locator('.rf-commerce-price svg[data-currency="silver"]').count(),1);
  await bar.locator('.rf-commerce-unit').selectOption('gold');await bar.locator('.rf-commerce-amount').fill('1');await action('bid',{outcome:'open',participants:[{name:'Mira',action:'withdraw',reason:'My funds are below one gold'}]},'<tr-dialogue name="Mira">หนึ่งเหรียญทองสูงกว่างบข้า ข้าถอนตัว</tr-dialogue>');assert.match(await bar.locator('.rf-commerce-price').innerText(),/100 เงิน/);assert.equal(await value(),beforeNew-100);
  if(process.env.COMPACT_ARTIFACT_DIR)await bar.screenshot({path:`${process.env.COMPACT_ARTIFACT_DIR}/auction-compact-${width}.png`});
  await bar.locator('.rf-commerce-summary').click();if(process.env.BASKET_ARTIFACT_DIR){await mkdir(process.env.BASKET_ARTIFACT_DIR,{recursive:true});await bar.screenshot({path:`${process.env.BASKET_ARTIFACT_DIR}/auction-gold-${width}.png`});}
  await action('wait',{outcome:'sold',participants:[]});assert.equal(await value(),beforeNew-10100);
  await receive(page,'ขอซื้อ Potion และ Rope','<tr-dialogue name="Rally">Potion สามเหรียญเงิน Rope สิบเหรียญเงิน</tr-dialogue>',{sceneTracker:{loc:'Guild'},marketplace:{kind:'npcShop',id:'basket-buy',location:'Guild',seller:{name:'Rally'},denomination:'silver',evidence:'Potion สามเหรียญเงิน Rope สิบเหรียญเงิน',items:[{itemId:'bp',name:'Potion',price:3,stock:5},{itemId:'br',name:'Rope',price:10,stock:2}]},ops:[]});await bar.locator('.rf-commerce-summary').click();await bar.getByLabel('เลือก Rope',{exact:true}).check();await bar.getByLabel('จำนวน Potion',{exact:true}).fill('2');await bar.getByLabel('จำนวน Potion',{exact:true}).blur();assert.match(await bar.locator('.rf-commerce-price').innerText(),/16 เงิน/);if(process.env.BASKET_ARTIFACT_DIR)await bar.screenshot({path:`${process.env.BASKET_ARTIFACT_DIR}/buy-list-${width}.png`});if(process.env.COMPACT_ARTIFACT_DIR){await bar.locator('.rf-commerce-summary').click();await bar.screenshot({path:`${process.env.COMPACT_ARTIFACT_DIR}/buy-compact-${width}.png`});}await action('confirm',{outcome:'accept',amount:16});assert.equal(await value(),beforeNew-11700);
  const owned=await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.filter(i=>['Potion','Rope'].includes(i.name)));assert.equal(owned.find(i=>i.name==='Potion').quantity,2);assert.equal(owned.find(i=>i.name==='Rope').quantity,1);
  await receive(page,'ให้ Mira ดู Potion และ Rope','<tr-dialogue name="Mira">ข้ารับซื้อ Potion สองชิ้น หกเหรียญเงิน และ Rope สิบเหรียญเงิน</tr-dialogue>',{sceneTracker:{loc:'Guild'},marketplace:{kind:'npcPurchase',id:'basket-sell',location:'Guild',buyer:{name:'Mira',budget:20},denomination:'silver',evidence:'ข้ารับซื้อ Potion สองชิ้น หกเหรียญเงิน และ Rope สิบเหรียญเงิน',items:owned.map(item=>({itemId:item.id,itemName:item.name,quantity:item.quantity,askPrice:item.name==='Potion'?6:10}))},ops:[]});await bar.locator('.rf-commerce-summary').click();assert.match(await bar.locator('.rf-commerce-price').innerText(),/16 เงิน/);await bar.getByLabel('เลือก Rope',{exact:true}).uncheck();assert.match(await bar.locator('.rf-commerce-price').innerText(),/6 เงิน/);if(process.env.BASKET_ARTIFACT_DIR)await bar.screenshot({path:`${process.env.BASKET_ARTIFACT_DIR}/sell-list-${width}.png`});if(process.env.COMPACT_ARTIFACT_DIR){await bar.locator('.rf-commerce-summary').click();await bar.screenshot({path:`${process.env.COMPACT_ARTIFACT_DIR}/sell-compact-${width}.png`});}await action('confirm',{outcome:'accept',amount:6});assert.equal(await value(),beforeNew-11100);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.find(i=>i.name==='Rope').quantity),1);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.some(i=>i.name==='Potion')),false);
  await page.evaluate(()=>{document.querySelector('#tretaresia-rpg-wand-launcher').click();document.querySelector('[data-tab="inventory"]').click();});await page.locator('.rf-inventory-wallet').waitFor();assert.equal(await page.locator('.rf-inventory-wallet svg').count(),3);if(process.env.BASKET_ARTIFACT_DIR)await page.locator('.rf-inventory-wallet').screenshot({path:`${process.env.BASKET_ARTIFACT_DIR}/inventory-wallet-${width}.png`});await page.evaluate(()=>document.querySelector('#tretaresia-control-trigger').click());await page.locator('[data-ui-setting="coinStyle"]').waitFor();const beforeStyle=await page.evaluate(()=>window.calls);for(const style of ['minted','outline','stack']){await page.locator('[data-ui-setting="coinStyle"]').selectOption(style);assert.equal(await page.locator(`.rf-inventory-wallet svg[data-coin-style="${style}"]`).count(),3);assert.equal(await page.evaluate(()=>window.host.extensionSettings.tretaresia_rpg.coinStyle),style);assert.equal(await page.evaluate(()=>window.calls),beforeStyle);}if(process.env.BASKET_ARTIFACT_DIR)await page.locator('[data-ui-setting="coinStyle"]').locator('..').screenshot({path:`${process.env.BASKET_ARTIFACT_DIR}/coin-sets-${width}.png`});await page.locator('[data-action="close-control-center"]').click();if(process.env.BASKET_ARTIFACT_DIR)await page.locator('.rf-inventory-wallet').screenshot({path:`${process.env.BASKET_ARTIFACT_DIR}/inventory-wallet-${width}.png`});await page.evaluate(()=>document.querySelector('#tretaresia-rpg-close').click());
  assert.equal(await page.evaluate(()=>window.legacyCommerceCalls),0);assert.match(await page.evaluate(()=>window.lastTaskSystem),/not a new normal role-play turn|not a new story turn/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(errors,[]);
  console.log(`PASS hybrid role-play/buttons, automatic one-call missing opening recovery, standing NPC price retained, non-looping failure diagnostics, latest-bubble continuation, mixed-currency payment, buy/sell baskets, SVG wallet, consent settlement, all story cards and boards at ${width}px`);await page.close();
 }
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
