import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {oneCardFixture} from './fixtures/one-card.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`:'playwright');
const root=new URL('../',import.meta.url),base='/scripts/extensions/third-party/rpg-systems/',artifacts=process.env.PRESET_ARTIFACT_DIR||'/tmp/roleforge-presets-preview';
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path.startsWith('/api/')){res.setHeader('content-type','application/json');res.end('[]');return;}if(!path.startsWith(base)||path.includes('..')){res.writeHead(404).end();return;}const file=path.slice(base.length);res.setHeader('content-type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.json')?'application/json':'image/webp');res.end(await readFile(new URL(file,root)));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));await mkdir(artifacts,{recursive:true});let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const width of [320,390,1280]){
  const page=await browser.newPage({viewport:{width,height:1100},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('https://**/*',r=>r.abort());
  await page.addInitScript(()=>localStorage.setItem('roleforge-hstats-preview-settings',JSON.stringify({tretaresia_rpg:{language:'en',autoTrack:false,autoContinuity:false,enableMemorySummaries:false}})));
  await page.goto(`http://127.0.0.1:${server.address().port}${base}docs/previews/preview-h-stats.html?lang=en`);await page.waitForFunction(()=>window.hStatsPreview?.ready);await page.waitForSelector('#roleforge-preset-editor',{state:'attached'});
  await page.evaluate(async card=>{document.querySelector('#tretaresia-rpg-close').click();document.querySelector('.preview-host').style.display='none';document.querySelector('#extensions_settings2').style.display='block';document.querySelector('#tretaresia-rpg-settings .inline-drawer-content').style.display='block';window.host.characters=[{avatar:'madoka.png',data:card.data,json_data:JSON.stringify(card)},{avatar:'mushoku.png',data:{extensions:{}}}];window.host.characterId=0;window.host.groupId=null;window.aiCalls=0;window.host.generateQuietPrompt=async()=>{window.aiCalls++;throw Error('Preset management must not call AI');};await window.hStatsPreview.switchChat('A',{});document.querySelectorAll('#tretaresia-rpg-settings details').forEach(n=>n.open=true);},oneCardFixture());
  const editor=page.locator('#roleforge-preset-editor'),powers=page.locator('#roleforge-power-editor');
  await powers.locator('.rf-power-workspace > input:not([type=file])').fill('Madoka A');await powers.locator('.rf-power-workspace > button').first().click();
  await page.waitForFunction(()=>window.host.chatMetadata.roleforge_chat_presets?.config.powerPreset.name==='Madoka A');
  await page.evaluate(()=>{const s=window.host.chatMetadata.tretaresia_rpg_state;s.player.hp.max=142;s.customPowers.soul_gem=22;s.progression.currency.silver=2;s.progression.currency.copper=8;window.chatA=structuredClone(window.host.chatMetadata);});
  await editor.locator('[data-preset-name]').fill('Madoka saved');await editor.locator('[data-preset-action=create]').click();await page.waitForFunction(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary?.length===1);
  let libraryId=await page.evaluate(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary[0].id);
  await page.evaluate(async()=>{await window.hStatsPreview.switchChat('B',{});document.querySelectorAll('#tretaresia-rpg-settings details').forEach(n=>n.open=true);});
  assert.equal(await powers.locator('.rf-power-workspace > input:not([type=file])').inputValue(),oneCardFixture().data.extensions.roleforge_character_pack.powerPreset.name);
  await page.locator('#roleforge-currency-editor [name=currencyName]').fill('Unsaved currency draft');
  await editor.locator('[data-preset-select]').selectOption(libraryId);await editor.locator('[data-preset-action=load]').click();await page.waitForFunction(()=>window.host.chatMetadata.roleforge_chat_presets?.config.powerPreset.name==='Madoka A');
  await page.waitForFunction(()=>document.querySelector('#roleforge-currency-editor [name=currencyName]').value===window.host.chatMetadata.tretaresia_rpg_state.progression.currency.name);
  assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.hp.max),100,'loading a preset does not copy HP progress');assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),0,'loading a preset does not copy money amounts');
  await editor.locator('[data-preset-action=delete]').click();await page.waitForFunction(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary.length===0);assert.equal(await powers.locator('.rf-power-workspace > input:not([type=file])').inputValue(),'Madoka A','loaded copy survives deletion');
  await editor.locator('[data-preset-name]').fill('Reusable world');await editor.locator('[data-preset-action=create]').click();await page.waitForFunction(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary.length===1);libraryId=await page.evaluate(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary[0].id);await editor.locator('[data-preset-select]').selectOption(libraryId);
  await editor.locator('[data-preset-name]').fill('Mushoku template');await editor.locator('[data-preset-action=rename]').click();await page.waitForFunction(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary[0].name==='Mushoku template');
  const exported=page.waitForEvent('download');await editor.locator('[data-preset-action=export]').click();const data=JSON.parse(await readFile(await (await exported).path(),'utf8'));assert.equal(data.format,'roleforge-world-preset');assert.equal(data.config.currencyPreset.scheme.units.length,3);assert.equal(data.config.player,undefined);assert.equal(data.config.progression,undefined);
  data.name='Imported template';await editor.locator('[data-preset-import]').setInputFiles({name:'template.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary.length===2);
  await page.evaluate(()=>{window.beforeFailedPreset=JSON.stringify(window.host.chatMetadata);window.savedMetadataFn=window.host.saveMetadata;window.host.saveMetadata=async()=>{throw Error('Offline preset save');};});await editor.locator('[data-preset-action=reset]').click();await page.waitForFunction(()=>document.querySelector('#roleforge-preset-editor [role=status]').textContent.includes('Offline'));assert.equal(await page.evaluate(()=>JSON.stringify(window.host.chatMetadata)===window.beforeFailedPreset),true);await page.evaluate(()=>window.host.saveMetadata=window.savedMetadataFn);
  await page.evaluate(async()=>{await window.hStatsPreview.switchChat('A',structuredClone(window.chatA));document.querySelectorAll('#tretaresia-rpg-settings details').forEach(n=>n.open=true);});assert.equal(await powers.locator('.rf-power-workspace > input:not([type=file])').inputValue(),'Madoka A');assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.hp.max),142);
  const currency=page.locator('#roleforge-currency-editor');await currency.locator('[data-currency-preset]').selectOption('credits');await currency.locator('[name=currencyName]').fill('Credits');const moneyExport=page.waitForEvent('download');await currency.locator('[data-currency-action=export]').click();const money=JSON.parse(await readFile(await (await moneyExport).path(),'utf8'));assert.equal(money.format,'roleforge-currency-preset');assert.equal(money.preset.scheme.units.length,1);assert.equal(money.preset.gold,undefined);
  await currency.locator('[data-currency-import]').setInputFiles({name:'credits.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(money))});await page.waitForFunction(()=>document.querySelector('#roleforge-currency-editor [role=status]').textContent.includes('Draft imported'));assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),2);await currency.locator('button[type=submit]').click();await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.scheme?.units.length===1);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.copper),208);
  await page.evaluate(async()=>{window.host.characterId=1;await window.hStatsPreview.switchChat('Mushoku',{});document.querySelectorAll('#tretaresia-rpg-settings details').forEach(n=>n.open=true);});assert.equal(await powers.locator('select[aria-label="Power preset"]').inputValue(),'tretaresia');assert.equal(await page.evaluate(()=>window.host.extensionSettings.tretaresia_rpg.roleforgePresetLibrary.length),2);
  assert.equal(await editor.evaluate(n=>n.scrollWidth>n.clientWidth+1),false,'native preset controls fit the viewport');assert.equal(await page.evaluate(()=>window.aiCalls),0);assert.deepEqual(errors,[]);await editor.screenshot({path:`${artifacts}/presets-${width}.png`});console.log(`PASS ${width}px: chat isolation, card fallback, library create/rename/delete, JSON export/import, failure rollback and currency-only drafts`);await page.close();
 }
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
