// Production loader: scene completion, current geography and paged location UI.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=new URL('../',import.meta.url),base='/scripts/extensions/third-party/rpg-systems/',out=process.env.LOCATIONS_SCREENSHOT_DIR||'/workspace/artifacts/locations-05811';await mkdir(out,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');res.end('[]');return;}if(!u.pathname.startsWith(base)||u.pathname.includes('..')){res.writeHead(404).end();return;}const path=u.pathname.slice(base.length);res.setHeader('content-type',path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.json')?'application/json':path.endsWith('.js')?'text/javascript':'image/webp');res.end(await readFile(new URL(path,root)));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
const full={dn:'Day 1',d:1,mo:'Harvest',yr:'1006',er:'Medieval',cal:'Standard',t:'19:00',per:'Night',se:'Spring',loc:'Cave near River',reg:'Kingsberg River',con:'Central Continent',pos:'At the entrance',w:'Clear',temp:12,light:'Lanterns',who:['Venus'],goal:'Rest',safe:'Safe',mood:'Quiet',dt:'25m'};
try{for(const width of [320,390,1280]){
 const p=await browser.newPage({viewport:{width,height:950},hasTouch:width<600,reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);await p.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
 await p.addInitScript(()=>localStorage.setItem('roleforge-hstats-preview-settings',JSON.stringify({tretaresia_rpg:{language:'en',themePreset:'forge',autoTrack:true,autoContinuity:false,chatPresentation:false,showSceneTracker:true,eventNotifications:false,enableMemorySummaries:false,npcDiaryFrequency:'off'}})));
 await p.goto(`http://127.0.0.1:${server.address().port}${base}docs/previews/preview-h-stats.html?lang=en`);await p.waitForFunction(()=>window.hStatsPreview?.ready);await p.locator('#tretaresia-control-trigger').evaluate(n=>n.click());await p.locator('[data-ui-setting=themePreset]').selectOption('verdant');await p.locator('[data-action=close-control-center]').click();await p.addStyleTag({content:'#chat{display:block;max-width:800px;margin:20px auto;padding:16px}.mes[mesid=\"0\"]{display:none}'});
 await p.evaluate(async full=>{
  const metadata=window.host.chatMetadata;metadata.tretaresia_rpg_state={player:{name:'Nova'},location:{place:'Cave near River',region:'',continent:''},scene:{position:'At the entrance',weather:'Clear',temperature:12},worldClock:{day:1,dayName:'Day 1',time:'19:00',phase:'Night'},onboarding:{identitySeeded:true,locationSeeded:true,loadoutSeeded:true},progression:{currency:{silver:25}},locationMemory:[{id:'bridge',name:'Kingsberg Bridge',parentName:'Kingsberg River'},{id:'village',name:'Riverside Village',parentName:'Kingsberg River'},...Array.from({length:11},(_,i)=>({name:'Trail '+(i+1),region:'Kingsberg River',continent:'Central Continent'}))]};
  window.host.chat=[{is_user:true,mes:'I enter the cave.'},{is_user:false,mes:'Cave near River lies by Kingsberg River in Central Continent. Kingsberg Bridge is 500 m from the cave. Riverside Village is a short walk away.'}];
  const chat=document.getElementById('chat');chat.replaceChildren(...window.host.chat.map((m,i)=>{const row=document.createElement('div');row.className='mes';row.setAttribute('mesid',i);const text=document.createElement('div');text.className='mes_text';text.textContent=m.mes;row.append(text);return row;}));
  window.sceneCalls=0;window.host.generateRaw=async()=>{window.sceneCalls++;const evidence='Cave near River lies by Kingsberg River in Central Continent.';return JSON.stringify({sceneTracker:full,locations:[{id:'realm',name:'Central Continent',kind:'Realm',evidence},{id:'river',name:'Kingsberg River',kind:'Region',parentName:'Central Continent',evidence},{id:'cave',name:'Cave near River',parentName:'Kingsberg River',evidence,connections:[{to:'Kingsberg Bridge',distance:'500 m',estimated:false,bidirectional:true,route:'River path'},{to:'Riverside Village',distance:'1.2 km',estimated:true,bidirectional:true,route:'River path'}]},{id:'bridge',name:'Kingsberg Bridge',parentName:'Kingsberg River',evidence:'Kingsberg Bridge is 500 m from the cave. Riverside Village is a short walk away.'}],ops:[['inc','progression.currency.silver',999]]});};
  await window.host.eventSource.emit('CHAT_CHANGED');
 },full);
 await p.locator('[data-tab=scene]').evaluate(n=>n.click());await p.locator('[data-action=complete-scene]').waitFor();await p.locator('[data-action=complete-scene]').click();
 await p.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.location.continent==='Central Continent');assert.equal(await p.evaluate(()=>window.sceneCalls),1);assert.equal(await p.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.silver),25);
 const scene=p.locator('[data-panel=scene]');assert.match(await scene.innerText(),/Kingsberg River/);assert.match(await scene.innerText(),/Location List/);
 const ledger=p.locator('#chat .mes[mesid="1"] .trpg-scene-ledger');await ledger.waitFor();assert.match(await ledger.innerText(),/Central Continent/);assert.match(await ledger.innerText(),/SCENE STATUS \/ LIVE/);
 const list=scene.locator('.rf-location-list'),toggle=list.locator(':scope > summary');const search=scene.locator('[data-location-search]');let row=scene.locator('.rf-location-list-row');
 assert.equal(await list.getAttribute('open'),null);assert.equal(await search.isVisible(),false);assert.equal(await row.count(),10);await list.evaluate(n=>n.scrollIntoView({block:'center'}));await p.screenshot({path:out+'/location-list-collapsed-'+width+'.png'});
 await toggle.click();assert.equal(await search.isVisible(),true);assert.equal(await row.first().getAttribute('open'),null);await toggle.focus();await p.keyboard.press('Enter');assert.equal(await search.isVisible(),false);await p.keyboard.press('Enter');assert.equal(await search.isVisible(),true);
 await search.fill('Cave');assert.equal(await row.count(),1);assert.equal(await row.locator('.rf-location-list-detail').isVisible(),false);await row.locator(':scope > summary').click();assert.equal(await row.locator('.rf-location-list-detail').isVisible(),true);assert.match(await row.innerText(),/Central Continent.*Kingsberg River.*Cave near River/s);assert.match(await row.innerText(),/You are here/);await row.locator(':scope > summary').click();assert.equal(await row.locator('.rf-location-list-detail').isVisible(),false);
 await search.fill('Bridge');assert.match(await scene.locator('.rf-location-list-row').innerText(),/500 m/);await search.fill('Village');assert.match(await scene.locator('.rf-location-list-row').innerText(),/Approx\. 1.2 km/);await search.fill('Trail 1');assert.match(await scene.locator('.rf-location-list-row').first().innerText(),/Distance unknown/);
 await search.fill('');assert.equal(await row.count(),10);await scene.locator('[data-location-page="1"]').click();assert.ok(await row.count()<10);await scene.locator('[data-location-page="-1"]').click();
 await search.fill('');await list.evaluate(n=>n.scrollIntoView({block:'start'}));await p.screenshot({path:out+'/location-list-all-'+width+'.png'});await search.fill('Cave');await row.locator(':scope > summary').click();await row.evaluate(n=>n.scrollIntoView({block:'center'}));await p.screenshot({path:out+'/location-list-'+width+'.png'});assert.equal(await p.evaluate(()=>window.sceneCalls),1);
 const geometry=await p.locator('.rf-location-list').evaluate(n=>({client:n.clientWidth,scroll:n.scrollWidth,page:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(geometry.scroll<=geometry.client+1,JSON.stringify(geometry));assert.ok(geometry.page<=geometry.viewport+1,JSON.stringify(geometry));
 await p.locator('#tretaresia-rpg-close').click();await ledger.evaluate(n=>n.scrollIntoView({block:'center'}));await ledger.screenshot({path:out+'/scene-tracker-'+width+'.png'});assert.deepEqual(errors,[]);await p.close();console.log('PASS scene completion, ledger, compact/expanded lists, paths, distance, pagination, search and mobile fit:',width);
}}finally{await browser.close();await new Promise(r=>server.close(r));}
