// Real loader, production state/prompt pipeline, native drawer and composer.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`:'playwright');
const root=new URL('../',import.meta.url),base='/scripts/extensions/third-party/rpg-systems/',artifacts='/workspace/artifacts/stats-currency-pending';
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith(base)||url.pathname.includes('..')){res.writeHead(404).end();return;}const path=url.pathname.slice(base.length);res.setHeader('content-type',path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.json')?'application/json':'text/javascript');res.end(await readFile(new URL(path,root)));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));await mkdir(artifacts,{recursive:true});
const url=`http://127.0.0.1:${server.address().port}${base}docs/previews/preview-h-stats.html?lang=en`;
async function prepare(page){
 await page.evaluate(async()=>{
  document.querySelector('#tretaresia-rpg-close').click();document.querySelector('.preview-host').hidden=true;
  const style=document.createElement('style');style.textContent='html,body{height:100%;overflow:hidden;background:#191919}#chat{display:block!important;box-sizing:border-box;height:60vh;overflow:auto;padding:16px;color:#ddd}#send_form{position:fixed;bottom:0;left:0;width:100%;padding:10px;box-sizing:border-box;background:#202020;display:flex;gap:8px}#send_textarea{display:block!important;width:100%;height:65px;box-sizing:border-box;border:1px solid #555;border-radius:12px;background:#151515;color:#ddd;padding:10px;font-size:16px}#send_but{background:#444;color:#eee;border:1px solid #666;border-radius:10px}.text_pole{box-sizing:border-box;width:100%;min-width:0;background:#161616;border:1px solid #555;border-radius:6px;color:#eee;padding:8px;font:inherit}.menu_button{background:#2a2a2a;color:#eee;border:1px solid #555;border-radius:6px;padding:8px}#extensions_settings2{display:none;box-sizing:border-box;height:100dvh;overflow-y:auto;padding:12px;background:#202020;color:#ddd;font:14px system-ui}#extensions_settings2 [hidden]{display:none!important}#extensions_settings2.is-preview-open{display:block!important;position:fixed;inset:0;z-index:20000}';document.head.append(style);
  const form=document.createElement('form');form.id='send_form';form.append(document.querySelector('#send_textarea'));const send=document.createElement('button');send.type='button';send.id='send_but';send.textContent='Send';form.append(send);document.body.append(form);
  window.notices=[];window.toastr.success=(message,title,options)=>window.notices.push({message,title,options});window.toastr.warning=(message)=>window.lastWarning=message;
  window.prompts={};window.calls=0;window.host.setExtensionPrompt=(key,value)=>window.prompts[key]=value;
  window.host.generateRaw=window.host.generateQuietPrompt=async()=>{window.calls++;throw Error('Stat practice must use the normal main chat, without a metadata API.');};
  const s=window.host.chatMetadata.tretaresia_rpg_state;s.player={...s.player,name:'Noah',hp:{current:60,max:100},mp:{current:70,max:100},stamina:{current:80,max:100},survival:{hunger:85,thirst:75},party:'Dawnlight',profession:'Mage'};s.progression={...s.progression,currency:{name:'Coins',gold:1,silver:23,copper:45}};s.onboarding={identitySeeded:true,locationSeeded:true,loadoutSeeded:true};
  window.host.chat=[{is_user:true,mes:'Hello'},{is_user:false,mes:'Noah is in the training yard.'}];document.querySelector('#chat').textContent='Noah\nThe training yard is quiet. Choose an exercise when ready.';
  window.sent=[];send.addEventListener('click',()=>{const message=document.querySelector('#send_textarea').value;window.sent.push(message);window.host.chat.push({is_user:true,mes:message});document.querySelector('#send_textarea').value='';send.disabled=true;window.host.eventSource.emit(window.host.eventTypes.MESSAGE_SENT,window.host.chat.length-1);window.host.eventSource.emit(window.host.eventTypes.GENERATION_STARTED,'normal',{},false);});
  await window.host.eventSource.emit(window.host.eventTypes.CHAT_CHANGED);
 });
}
async function receive(page,user,story,patch){
 await page.evaluate(async({user,story,patch})=>{
  if(user!==null){window.host.chat.push({is_user:true,mes:user});await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_SENT,window.host.chat.length-1);await window.host.eventSource.emit(window.host.eventTypes.GENERATION_STARTED,'normal',{},false);}
  await window.TretaresiaRpgGenerateInterceptor(structuredClone(window.host.chat),100000,()=>{},'normal');
  const id=window.host.chat.length,mes=story+'<!--tretaresia_patch:'+JSON.stringify(patch)+'-->';window.host.chat.push({is_user:false,mes,swipe_id:0,swipes:[mes]});const row=document.createElement('div');row.className='mes';row.setAttribute('mesid',id);const text=document.createElement('div');text.className='mes_text';text.textContent=story;row.append(text);document.querySelector('#chat').append(row);
  await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,id,'normal');await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);document.querySelector('#send_but').disabled=false;
 },{user,story,patch});
 await page.waitForTimeout(120);
}
async function openSettings(page){await page.locator('#extensions_settings2').evaluate(root=>{root.classList.add('is-preview-open');root.querySelectorAll('.inline-drawer-content').forEach(el=>el.style.display='block');});}
async function closeSettings(page){await page.locator('#extensions_settings2').evaluate(root=>root.classList.remove('is-preview-open'));}
let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const width of [320,390,1280]){
  const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(12000);
  await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
  await page.addInitScript(()=>localStorage.setItem('roleforge-hstats-preview-settings',JSON.stringify({tretaresia_rpg:{language:'en',themePreset:'verdant',accentColor:'#79b463',accentAltColor:'#c6f0a8',inkColor:'#e8f0e2',surfaceColor:'#030704',autoTrack:true,autoContinuity:false,eventNotifications:false,notifyStatGrowth:true,enableMemorySummaries:false,showTravelTracker:false,enableMarketplace:true,enableAuctions:true,enableIncantation:true,npcDiaryFrequency:'off',showStatusComposer:true,showStatTrainingComposer:true}})));
  await page.goto(url);await page.waitForFunction(()=>window.hStatsPreview?.ready);await prepare(page);
  assert.equal(await page.locator('.rf-composer-dock').evaluate(el=>el.classList.contains('is-minimized')),true,'fresh chat starts minimized');
  await page.locator('[data-dock-panel=status]').click();assert.equal(await page.locator('.rf-user-status [data-vital]').count(),5);assert.match(await page.locator('.rf-user-status').textContent(),/Noah/);
  const theme=await page.locator('.rf-user-status').evaluate(el=>({radius:getComputedStyle(el).borderRadius,font:getComputedStyle(el).fontFamily,accent:getComputedStyle(el.querySelector('.rf-stat-track i')).backgroundColor}));assert.equal(theme.radius,'10px');assert.match(theme.font,/system-ui/);assert.equal(theme.accent,'rgb(121, 180, 99)');assert.equal(await page.locator('.rf-user-status .rf-ability-heading svg').count(),1);
  assert.equal(await page.evaluate(()=>{const a=getComputedStyle(document.querySelector('.rf-incantation')),b=getComputedStyle(document.querySelector('.rf-user-status'));return a.backgroundImage===b.backgroundImage&&a.borderColor===b.borderColor&&a.borderRadius===b.borderRadius&&a.fontFamily===b.fontFamily;}),true,'status shares the existing Incantation shell');
  await page.locator('.rf-user-status').screenshot({path:`${artifacts}/status-${width}.png`});
  assert.equal(await page.locator('.rf-user-status').getAttribute('data-layout'),'C','status defaults to selected Tactical Strip');
  for(const layout of ['A','B','C']){
   await openSettings(page);await page.locator('#tretaresia-rpg-status-layout').selectOption(layout);await page.locator('#tretaresia-rpg-stat-training-layout').selectOption(layout);await closeSettings(page);
   await page.locator('[data-dock-panel=status]').click();assert.equal(await page.locator('.rf-user-status').getAttribute('data-layout'),layout);assert.equal(await page.locator('.rf-user-status [data-vital]').count(),5);
   const stroke=await page.locator('.rf-stat-wallet svg').first().evaluate(n=>({root:getComputedStyle(n).stroke,rect:getComputedStyle(n.querySelector('rect')).stroke,filter:getComputedStyle(n).filter}));assert.deepEqual(stroke,{root:'none',rect:'none',filter:'none'},'pixel art stays sharp inside the shared Incantation shell');
   await page.locator('.rf-user-status').screenshot({path:`${artifacts}/status-${layout}-${width}.png`});
   await page.locator('[data-dock-panel=stats]').click();assert.equal(await page.locator('.rf-stat-training').getAttribute('data-layout'),layout);assert.equal(await page.locator('[data-stat-select]').count(),7);
   await page.locator('.rf-stat-training').screenshot({path:`${artifacts}/training-${layout}-${width}.png`});
   const fit=await page.locator('.rf-composer-dock').evaluate(n=>({width:n.clientWidth,scroll:n.scrollWidth,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right}));assert.ok(fit.scroll<=fit.width+1&&fit.left>=0&&fit.right<=width+1,JSON.stringify({layout,width,fit}));
  }
  await page.locator('[data-dock-panel=stats]').click();assert.equal(await page.locator('[data-stat-select]').count(),7);
  await page.locator('[data-stat-select=hp]').hover();const selected=await page.locator('[data-stat-select=hp]').evaluate(el=>({background:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color}));assert.equal(selected.background,'rgb(222, 222, 222)');assert.equal(selected.color,'rgb(27, 27, 27)');
  await page.locator('.rf-stat-training').screenshot({path:`${artifacts}/training-${width}.png`});
  await page.locator('[data-stat-select=hp]').click();await page.locator('[data-stat-method-choice="1"]').click();await page.locator('[data-stat-details] summary').click();assert.match(await page.locator('[data-stat-details]').textContent(),/Safe resistance work/);await page.locator('[data-stat-start]').dblclick();assert.equal(await page.evaluate(()=>window.sent.length),1,'one normal-chat action');assert.match(await page.evaluate(()=>window.sent[0]),/I begin HP training/);assert.match(await page.evaluate(()=>window.sent[0]),/Safe resistance work/);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.hp.max),100,'click cannot grant growth');
  await receive(page,null,'<tr-narrative>Noah completed successful HP training in the yard.</tr-narrative>',{ops:[['inc','player.hp.max',40,{category:'training'}],['inc','player.stamina.current',-5]]});
  assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.hp.max),102);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.hp.current),60);assert.equal(await page.evaluate(()=>window.notices.length),1);assert.match(await page.evaluate(()=>window.notices[0].message),/HP \+2/);
  await page.evaluate(async()=>{await window.host.eventSource.emit(window.host.eventTypes.MESSAGE_RECEIVED,window.host.chat.length-1,'normal');await window.host.eventSource.emit(window.host.eventTypes.GENERATION_ENDED);});assert.equal(await page.evaluate(()=>window.notices.length),1);
  await receive(page,'How do I train STR?','Noah discusses successful STR training.',{ops:[['inc','player.attributes.strength',20,{category:'training'}]]});assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.attributes.strength),10);
  await openSettings(page);await page.locator('#roleforge-stat-editor').evaluate(el=>el.closest('details').open=true);
  const add=page.locator('[data-stat-add]');await add.evaluate(el=>el.closest('details').open=true);await add.locator('[name=name]').fill('Spirit');await add.locator('[name=description]').fill('Spiritual focus and concentration');await add.locator('[name=methods]').fill('Meditation with controlled breathing');await add.locator('[name=initial]').fill('5');await add.locator('[name=max]').fill('30');await add.locator('[type=submit]').click();await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.statTraining.definitions.length===1);
  const id=await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.statTraining.definitions[0].id);await closeSettings(page);await page.locator('[data-dock-panel=stats]').click();assert.equal(await page.locator('[data-stat-select]').count(),8);
  await receive(page,'I train Spirit with meditation.','Noah completed successful Spirit training.',{ops:[['inc',`player.customStats.${id}`,7,{category:'training'}]]});assert.equal(await page.evaluate(id=>window.host.chatMetadata.tretaresia_rpg_state.player.customStats[id],id),6);
  await openSettings(page);const config=page.locator('[data-stat-config]');await config.locator(`[name=show-${id}]`).uncheck();await config.locator('[name=show-strength]').uncheck();await config.locator('[type=submit]').click();await page.waitForFunction(id=>!window.host.chatMetadata.tretaresia_rpg_state.statTraining.definitions.find(d=>d.id===id).showTraining,id);await closeSettings(page);assert.equal(await page.locator('[data-stat-select]').count(),6);
  await receive(page,'I train STR with lifting.','Noah completed successful STR training.',{ops:[['inc','player.attributes.strength',1,{category:'training'}]]});assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.player.attributes.strength),11);
  await openSettings(page);await page.locator('#tretaresia-rpg-status-composer').uncheck();await closeSettings(page);assert.equal(await page.locator('[data-dock-panel=status]').count(),0);await openSettings(page);await page.locator('#tretaresia-rpg-status-composer').check();
  await page.locator('#roleforge-currency-editor').evaluate(el=>el.closest('details').open=true);const currency=page.locator('.rf-currency-editor');await currency.locator('[data-currency-preset]').selectOption('banknotes');await currency.locator('[name=currencyName]').fill('Dollars');await currency.locator('[type=submit]').click();await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.scheme?.units.length===1);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.copper),12345);
  await currency.locator('[data-currency-preset]').selectOption('modern');await currency.locator('[name=rate-silver]').fill('10');await currency.locator('[name=set-silver]').selectOption('neon');await currency.locator('[name=set-copper]').selectOption('pixel');await currency.locator('[type=submit]').click();await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.scheme.units[0].value===10);
  assert.deepEqual(await page.evaluate(()=>{const c=window.host.chatMetadata.tretaresia_rpg_state.progression.currency;return[c.silver,c.copper,c.gold];}),[1234,5,0]);assert.equal(await currency.locator('[data-money-set]').count(),8);
  // Every approved set moves through all four frames under production CSS.
  await page.emulateMedia({reducedMotion:'no-preference'});
  const galleryFrames=await currency.locator('.rf-money-set-gallery svg').evaluateAll(icons=>icons.map(svg=>{
   const frames=[...svg.querySelectorAll('.px-frame')],animations=svg.getAnimations({subtree:true});
   const samples=[0,601,1201,1801].map(time=>{animations.forEach(a=>{a.pause();a.currentTime=time;});return frames.filter(f=>Number(getComputedStyle(f).opacity)>.99).map(f=>f.dataset.frame);});
   animations.forEach(a=>a.play());return {set:svg.dataset.coinStyle,samples};
  }));
  for(const row of galleryFrames)assert.deepEqual(row.samples,[['0'],['1'],['2'],['3']],`${row.set} animates all pixel frames`);
  await page.emulateMedia({reducedMotion:'reduce'});
  const stopped=()=>currency.locator('.rf-money-set-gallery svg').evaluateAll(icons=>icons.every(svg=>[...svg.querySelectorAll('.px-frame')].every(frame=>getComputedStyle(frame).animationName==='none')&&[...svg.querySelectorAll('.px-frame')].filter(frame=>Number(getComputedStyle(frame).opacity)>.99).map(frame=>frame.dataset.frame).join(',')==='0'));
  assert.equal(await stopped(),true,'Reduce Motion stops all eight sets at frame zero');
  await page.emulateMedia({reducedMotion:'no-preference'});await currency.locator('[name=animated]').uncheck();
  assert.equal(await stopped(),true,'the native motion switch stops every set without an API call');
  await currency.locator('[name=animated]').check();
  // Unsaved edits survive live state refresh and count/preset switching.
  await currency.locator('[name=currencyName]').fill('Pocket Money');await currency.locator('[data-currency-count]').selectOption('1');assert.equal(await currency.locator('[name=currencyName]').inputValue(),'Pocket Money');await currency.locator('[data-currency-count]').selectOption('2');assert.equal(await currency.locator('[name=name-silver]').inputValue(),'Dollar');assert.equal(await currency.locator('[name=set-silver]').inputValue(),'neon');await currency.locator('[name=rate-silver]').fill('10');await currency.locator('[type=submit]').click();await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.progression.currency.name==='Pocket Money');
  const markup=await currency.evaluate(el=>el.outerHTML),capture=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const css=(await readFile(new URL('styles/stat-composer.css',root),'utf8'))+(await readFile(new URL('styles/commerce-composer.css',root),'utf8'));await capture.setContent(`<meta charset="utf-8"><style>html,body{margin:0;background:#202020;color:#ddd;font:14px system-ui}body{padding:12px;box-sizing:border-box}.text_pole{box-sizing:border-box;width:100%;background:#161616;border:1px solid #555;border-radius:6px;color:#eee;padding:8px;font:inherit}.menu_button{background:#292929;color:#eee;border:1px solid #555;border-radius:6px;padding:8px}.checkbox_label{margin:8px 0}${css}</style>${markup}`);await capture.locator('.rf-currency-editor').screenshot({path:`${artifacts}/currency-settings-${width}.png`});await capture.close();await closeSettings(page);await page.locator('[data-dock-panel=status]').click();assert.equal(await page.locator('.rf-stat-wallet>span').count(),2);
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.rf-stat-wallet .px-frame').first().evaluate(el=>getComputedStyle(el).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
  const animated=await page.locator('.rf-stat-wallet svg').first().evaluate(svg=>{
   const frames=[...svg.querySelectorAll('.px-frame')],sample=time=>{svg.getAnimations({subtree:true}).forEach(a=>{a.pause();a.currentTime=time;});return frames.filter(f=>Number(getComputedStyle(f).opacity)>.99).map(f=>f.dataset.frame);};
   const first=sample(0),next=sample(601);svg.getAnimations({subtree:true}).forEach(a=>a.play());return {first,next};
  });assert.deepEqual(animated,{first:['0'],next:['1']},'currency actually advances pixel frames in the live dock');
  await page.locator('.rf-composer-dock').screenshot({path:`${artifacts}/configured-status-${width}.png`});
  const fit=await page.evaluate(()=>{const dock=document.querySelector('.rf-composer-dock'),r=dock.getBoundingClientRect(),form=document.querySelector('#send_form').getBoundingClientRect();return{left:r.left,right:r.right,width:innerWidth,overflow:dock.scrollWidth-dock.clientWidth,bottom:r.bottom,top:form.top};});assert.ok(fit.left>=0&&fit.right<=fit.width+1&&fit.overflow<=1,JSON.stringify(fit));assert.ok(fit.bottom<=fit.top+1);
  if(width===390){
   // A real story offer uses configured money throughout the shop and rental UI.
   const location=await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.location.place),quote='Training blade rental costs $3 for twenty minutes, with a refundable deposit of $2.';
   await receive(page,'I want to rent Training blade.',`<tr-dialogue name="Mira">${quote}</tr-dialogue>`,{marketplace:{kind:'npcShop',id:'configured-rental',location,seller:{name:'Mira'},denomination:'silver',evidence:quote,items:[{id:'rental',name:'Training blade',category:'Weapon',description:'A balanced blade for practice.',rarity:'Common',properties:['Training equipment'],price:3,stock:1,stockKnown:true,terms:{mode:'rental',scope:'Training blade',durationMinutes:20,deposit:2,delivery:{name:'Training blade',category:'Weapon'}},usage:{action:'use',consumable:false,effect:'Practice equipment with no direct stat changes.',conditions:[],target:'training partner',cooldown:{unit:'none',value:0},charges:null,stats:[],learns:[]}}]},ops:[]});
   await page.locator('[data-dock-panel=commerce]').click();const trade=page.locator('.rf-commerce-composer');await trade.locator('[data-commerce-action=confirm]').waitFor();await trade.locator('.rf-commerce-summary').click();
   assert.deepEqual(await trade.locator('.rf-commerce-unit option').allTextContents(),['$','¢']);assert.match(await trade.innerText(),/Additional deposit\s+2 \$/);assert.doesNotMatch(await trade.innerText(),/\b(?:gold|silver|copper)\b/iu);
   await page.locator('.rf-composer-dock').screenshot({path:`${artifacts}/configured-rental-${width}.png`});const sessionId=await trade.getAttribute('data-session');assert.ok(sessionId);
   await receive(page,'I confirm the rental for $3.','<tr-dialogue name="Mira">I receive $3 and the $2 refundable deposit. Here is Training blade for twenty minutes.</tr-dialogue>',{commerce:{sessionId,revision:0,action:'confirm',amount:3,denomination:'silver',evidence:'I confirm the rental for $3.',decision:{outcome:'accept',amount:3}},ops:[]});
   await page.waitForFunction(()=>window.host.chatMetadata.tretaresia_rpg_state.commerce?.receipts.length===1);assert.deepEqual(await page.evaluate(()=>{const c=window.host.chatMetadata.tretaresia_rpg_state.progression.currency;return[c.silver,c.copper];}),[1229,5]);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.commerce.rights[0].depositPaid),2);assert.equal(await page.evaluate(()=>window.host.chatMetadata.tretaresia_rpg_state.inventory.find(i=>i.name==='Training blade').quantity),1);
  }
  await page.evaluate(async()=>{const m=structuredClone(window.host.chatMetadata);await window.hStatsPreview.switchChat('second-chat',m);});assert.equal(await page.locator('.rf-composer-dock').evaluate(el=>el.classList.contains('is-minimized')),true,'chat entry resets to minimized');
  if(width===390){
   const lifecycle=await page.evaluate(async()=>{
    const {createStatComposer}=await import('./../../src/stat-composer.js');const panels=new Map();let resolve;
    const component=createStatComposer({document,dock:{panel:(id,n)=>panels.set(id,n),remove:id=>panels.delete(id),minimize:()=>{}},settings:()=>({showStatusComposer:true,showStatTrainingComposer:true,statusComposerLayout:'C',statTrainingLayout:'C'}),train:()=>new Promise(done=>{resolve=done;})});
    component.update(structuredClone(window.host.chatMetadata.tretaresia_rpg_state),'deferred');panels.get('stats').querySelector('[data-stat-start]').click();component.update(null,'');resolve();await Promise.resolve();await Promise.resolve();const remaining=panels.size;component.destroy();return remaining;
   });assert.equal(lifecycle,0,'finishing an old practice request cannot reopen panels in a closed chat');
  }
  assert.equal(await page.evaluate(()=>window.calls),0,'new stats/settings add no metadata calls');assert.deepEqual(errors,[]);
  await page.reload();await page.waitForFunction(()=>window.hStatsPreview?.ready);await prepare(page);assert.equal(await page.locator('.rf-composer-dock').evaluate(el=>el.classList.contains('is-minimized')),true,'restart remains minimized');
  console.log(`PASS stats/currency production UI at ${width}px: normal chat, bounds, custom definitions, hidden buttons, exact money, native settings, reduced motion, reload, no overflow`);await page.close();
 }
}finally{await browser?.close();server.close();}
