from pathlib import Path
import json, html
O=Path(__file__).resolve().parent
G='currentColor'; K='#101822'
def p(d,f='none',s=G,w=1.8): return f'<path d="{d}" fill="{f}" stroke="{s}" stroke-width="{w}" stroke-linecap="round" stroke-linejoin="round"/>'
def c(x,y,r,f='none',w=1.5): return f'<circle cx="{x}" cy="{y}" r="{r}" fill="{f}" stroke="currentColor" stroke-width="{w}"/>'
D=json.loads((O/'npc-medallions.json').read_text())[:47]
def add(key,th,name,shape): D.append(dict(id=key,th=th,name=name,shape=shape,kind='New detailed'))
add('politician','นักการเมือง','Politician',p('M10 31 48 9 86 31ZM15 76H81V84H15ZM20 36H30V70H20ZM43 36H53V70H43ZM66 36H76V70H66Z',G)+p('M25 27 48 15 71 27ZM24 41V65M47 41V65M70 41V65M21 80H75',K,K,1.3)+p('M54 53H84V77H54Z',G)+p('M59 59H78M59 64H74M59 69H69',K,K,1.5)+c(78,76,6,G)+p('M78 72V79M75 75H81',K,K,1))
add('knight','อัศวิน','Knight',p('M30 36Q26 14 48 10Q71 14 67 36L62 61 48 72 34 61Z',G)+p('M34 34 48 29 63 34 60 43 36 43ZM39 47V57M45 46V62M51 46V62M57 47V57',K,K,2.2)+p('M48 12V29M31 28H65',K,K,1.2)+p('M48 9Q58 0 71 7L78 20 65 15 61 24Z',G)+p('M31 62 15 70 9 87H39L48 77 57 87H87L81 70 65 62 48 75Z',G)+p('M18 76 34 71M62 71 78 76M22 81H34M62 81H74',K,K,1.4))
add('prisoner','นักโทษ','Prisoner',p('M16 86V31Q16 7 48 7Q80 7 80 31V86Z',G)+p('M23 80V32Q23 15 48 15Q73 15 73 32V80Z',K,K)+c(48,37,10,G)+p('M29 71Q28 52 48 52Q68 52 67 71Z',G)+p('M31 21V83M48 16V83M65 21V83M21 47H75M21 76H75',w=3.2)+p('M18 31H22M74 31H78',K,K,1.2)+c(70,63,5,K)+p('M70 60V66',w=1.2))
add('slave','ทาส','Slave',p('M10 22 18 16 36 25 32 47 22 55 9 46Z',G)+p('M15 25 19 22 29 28 26 43 22 47 15 42Z',K,K)+p('M60 25 78 16 86 22 87 46 74 55 64 47Z',G)+p('M67 28 77 22 81 25 81 42 74 47 70 43Z',K,K)+p('M24 53V65Q24 73 32 73H39M72 53V65Q72 73 64 73H57',w=4)+p('M40 67H55Q63 67 63 74Q63 81 55 81H40Q32 81 32 74Q32 67 40 67Z',w=3)+p('M13 34H29M67 34H83',w=1)+c(22,50,2,K)+c(74,50,2,K))
add('master','นาย / เจ้านาย','Master',p('M18 82 63 21',w=5)+p('M55 13 65 5 77 14 73 28 61 31 52 24Z',G)+p('M60 15 65 11 71 16 67 24 60 24Z',K,K)+p('M21 76 27 81M25 70 31 75',K,K,1.5)+c(61,64,23,G)+c(61,66,16,K)+p('M48 50 61 44 74 50V63L61 73 48 63Z',G)+p('M53 55 57 58 61 51 65 58 69 55 67 64H55Z',K,K)+p('M41 79 45 84M78 79 74 84',K,K,1.4)+p('M18 19V31M12 25H24',w=1.3))
add('clergyman','บาทหลวง','Clergyman',c(48,26,15,G)+p('M33 23Q32 10 48 10Q64 10 63 23L56 18 48 21 40 18Z',K,K)+p('M34 44 48 49 62 44 77 61 83 88H13L19 61Z',G)+p('M33 45 42 57 42 85H29L28 58M63 45 54 57 54 85H67L68 58',K,K,1.8)+p('M42 46H54V52H42Z',K,K)+p('M45 47H51V51H45Z',G)+p('M48 57V78M41 67H55',K,K,2.5)+p('M38 29H42M54 29H58M43 37Q48 40 53 37',K,K,1.2)+p('M19 83H25M71 83H77',K,K,1.3))
add('nun','แม่ชี','Nun',p('M14 87 22 32Q24 7 48 6Q72 7 74 32L82 87Z',G)+p('M20 82 29 32Q30 14 48 13Q66 14 67 32L76 82Z',K,K)+p('M30 28Q48 13 66 28L62 53 48 66 34 53Z',G)+p('M35 29Q48 24 61 29L58 46Q48 59 38 46Z',K,K)+p('M32 55 48 69 64 55 68 82H28Z',G)+p('M48 65V81M42 73H54',K,K,2)+p('M39 34H42M54 34H57M44 46Q48 49 52 46',w=1.1)+p('M25 47 21 75M71 47 75 75',w=1.1))
assert len(D)==len({d['id'] for d in D})==54
(O/'npc-medallions.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
frame=c(64,64,59,w=1.7)+c(64,64,54,w=.65)+p('M64 1 68 5 64 9 60 5ZM64 119 68 123 64 127 60 123ZM1 64 5 60 9 64 5 68ZM119 64 123 60 127 64 123 68Z',G)+p('M23 17 27 21M101 21 105 17M23 111 27 107M101 107 105 111',w=1.2)
module='// Generated by design/build-medallions.py. Trusted static artwork only.\nexport const MEDALLION_ROLES = '+json.dumps({d['id']:{'label':d['th']+' / '+d['name'],'shape':d['shape']} for d in D},ensure_ascii=False)+';\nexport const MEDALLION_FRAME = '+json.dumps(frame)+';\n'
(O.parent/'src/npc-medallions.js').write_text(module)
board=['<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="850" viewBox="0 0 1440 850"><rect width="1440" height="850" fill="#101822"/><text x="40" y="60" fill="#e5c48a" font-size="32" font-family="serif">TRETARESIA — Seven new role medallions</text>']
for i,d in enumerate(D[-7:]):
 x=60+(i%4)*350;y=100+(i//4)*360
 board.append(f'<g transform="translate({x+55} {y}) scale(1.5)" color="#e5c48a">{frame}<g transform="translate(24 24) scale(.8333333)">{d["shape"]}</g></g><text x="{x+150}" y="{y+240}" text-anchor="middle" fill="#e5c48a" font-size="26" font-family="serif">{d["name"]}</text>')
board.append('</svg>');(O/'NPC-Seven-New-Medallions.svg').write_text(''.join(board))
